### PR TITLE
Update of Muller & Mandel SN remnants and kicks

### PR DESCRIPTION
**Pull request by ilyamandel**
Moved constants to constants.h, other minor clean-up

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
@ilyamandel , do you have a latex'd version of the kick prescription we can compare to?

**Comment by ilyamandel** [comment]
@reinhold-willcox :  Preliminary version, still working on this:

[remnants.pdf](https://github.com/TeamCOMPAS/COMPAS/files/4532764/remnants.pdf)

**Comment by ilyamandel** [comment]
Hold off on reviewing this for now, I may need to implement a small tweak.

**Comment by ilyamandel** [comment]
Should be OK now.

**Pull request merged**
