### PR TITLE
directory restructuring

### PR DESCRIPTION
**Pull request by reinhold-willcox**
renamed example_plots to examples, and moved into it the python scripts which we do not guaruntee are maintained

### CODE REVIEW

**Review by ilyamandel — CHANGES_REQUESTED** [review]
@reinhold-willcox -- can you please check the Files Changed tab?  I see things like Untitled.ipynb and Untitled1.ipynb -- should those at least be given meaningful names?

**Comment by reinhold-willcox** [comment]
Those are notebooks spun up for quick testing purposes and not meant to be included. Thanks for catching, they are removed now.

**Review by ilyamandel — COMMENTED** [review]
- utils/PythonScripts/outputConverter.py seems to be deleted rather than moved -- is that intentional?

- utils/examples/methods_paper_plots/detailed_evolution/runSubOptions.txt -- what is this and does it need to be under version control?

- are some of the things under utils/examples really examples (e.g., h5rewrite.py)?  I am not sure that's a good name.  Perhaps the core scripts that we stand by should just live under utils, not examples?

**Comment by reinhold-willcox** [comment]
> * utils/PythonScripts/outputConverter.py seems to be deleted rather than moved -- is that intentional?

Yes, that was the script that combined csv output into hdf5, you suggested we dump it. 

> * utils/examples/methods_paper_plots/detailed_evolution/runSubOptions.txt -- what is this and does it need to be under version control?

My mistake, that was not meant to be included in the PR, it is now removed.

> * are some of the things under utils/examples really examples (e.g., h5rewrite.py)?  I am not sure that's a good name.  Perhaps the core scripts that we stand by should just live under utils, not examples?

Agreed that they do not belong in `examples/`. These are PythonScripts that we are not ensuring are up to date. Maybe we could put them in a subfolder `PythonScripts/additional_untracked_scripts`?

**Comment by ilyamandel** [comment]
How about having utils/examples, utils/untracked_scripts, and a few key things that we are really standing behind that just live under utils?

**Comment by reinhold-willcox** [comment]
Done - let me know if there are other remaining TODOs for this PR, but I think it's good to go.

**Comment by reinhold-willcox** [comment]
@ilyamandel pinging you, if this PR looks good, could you merge it in?

**Comment by ilyamandel** [comment]
Sorry, @reinhold-willcox .  I thought the idea was to do away with utils/PythonScripts altogether (since that's not very descriptive) and to have utils/examples, utils/untracked_scripts, and a few key things that we are really standing behind that just live under utils.

**Comment by reinhold-willcox** [comment]
I might have misunderstood before. All files in 'utils/PythonScripts' are now moved up a level and sit just in 'utils'. Is that what you're looking for?

**Review by ilyamandel — APPROVED** [review]
Looks great -- thank you, @reinhold-willcox !

**Pull request merged**
