### PR TITLE
update COMPAS workflows with newer versions of actions

### PR DESCRIPTION
**Pull request by avivajpeyi**
- Updated to latest action versions (e.g., actions/checkout@v4, actions/setup-python@v5)
- Switched to Ubuntu 22.04
- Added concurrency to prevent redundant workflow runs
- Replaced manual Docker login with docker/login-action@v3
- Use docker/setup-buildx-action@v3 for more efficient builds
- use docker/build-push-action@v5 for better performance and caching
- Removed LaTeX-COMPAS action (unused)

### CODE REVIEW

**Comment by avivajpeyi** [comment]
@jeffriley, is the `latex-compas-ci` even being used? `docs/COMPAS_LaTeX` does not exist... Should we get rid of this yaml? 


--- 

Jeff confirmed that it is not being used. Getting rid of it.

**Comment by avivajpeyi** [comment]
Ah I can't trigger the docker-build from my Fork/branch (don't have the COMPAS credentials)... We'll have to test that from a branch within TEAMCompas/COMPAS

**Comment by avivajpeyi** [comment]
Im not having much luck with the PR-commenter (yet again). 

If the detailedEvol plot (generated in the CI) is indeed useful, we could get the CI to upload the image to the repo. 
```
0: DCO formed: (Main_Sequence_>_0.7 -> Black_Hole) + (Main_Sequence_>_0.7 -> Black_Hole)
```
detailedEvolutionPlot



This would then be a tracked file and will show up in the git-diff : 
https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files


I'll leave this for a future PR, and would like to hear from @ilyamandel / @jeffriley if this is a feature that might be useful.

**Comment by ilyamandel** [comment]
Thank you, @avivajpeyi!   I am OK with just testing that we succeed in generating the plot; not critical to be able to review it.

**Review by ilyamandel — APPROVED** [review]
Thank you very much for the rapid fix, @avivajpeyi !

**Pull request merged**
