### PR TITLE
Update to Picker+ (2024) fits for Hirai & Mandel 2-stage CE; exposure of functionality needed for tidal computations

### PR DESCRIPTION
**Pull request by ilyamandel**
Initial push; compiles, but yet to be tested.

### CODE REVIEW

**Comment by ilyamandel** [comment]
@veome22 -- I am flagging you because this will show you which functions I am exposing. 
@jeffriley & @ryosuke-hirai -- I'll eventually ask for your review, but need to test first.

**Comment by ilyamandel** [comment]
@jeffriley , @veome22 , @ryosuke-hirai -- this runs and does sensible things; still testing, but removing Draft status so you can review (and Veome can see what the API will look like).

**Comment by veome22** [comment]
Hi @ilyamandel! 

In line 30 of MainSequence.h, why does `CalculateConvectiveEnvelopeMass()` return (0.0, 0.0)? 
Based on Hurley (2000), shouldn't the initial envelope mass be $M_\*$ for $M_* < 0.35 M_\odot$, and gradually decrease for $0.35 M_\odot < M_* < 1.25 M_\odot$ for a Main Sequence star? (This is all in addition to the time evolution).

**Comment by ilyamandel** [comment]
Good catch, @veome22!  Fixed.

**Comment by ryosuke-hirai** [comment]
I don't quite understand why in various places there is something like
`RadialExtentConvectiveEnvelope = Radius - ConvectiveCoreRadius`
Judging from the name, the right hand side will give the depth of a radiative envelope.
I haven't followed how this is used, but is this just a confusing variable name?

**Comment by ilyamandel** [comment]
@ryosuke-hirai : Indeed, for evolved giants (FGB, CHeB, HeGB) we assume that the radial extent of the radiative intershell is negligible.  We don't have fits for it, so it's the best we could do right now (and matches Hurley's recommendation).

**Comment by ryosuke-hirai** [comment]
Ok, I now see that `ConvectiveCoreRadius` basically points to `RemnantRadius` for evolved stars. So it is just slightly confusing because the variable name is re-used for something else.

**Comment by jeffriley** [comment]
@ilyamandel you pushed you Makefile - that's why the build is failing.

Also, re the Makefile, see slack https://compashq.slack.com/archives/CMCEQ0RS8/p1673941394742069

**Comment by ilyamandel** [comment]
@veome22 , @jeffriley , @ryosuke-hirai -- thanks to all of you for great comments!
I've uploaded some fixes and would be grateful for a review so we can pull this in (if it's acceptable, of course).
I note that I already have some promising preliminary results, where the 2-stage CE is doing exactly what we expected: killing off the CE channel for BBH formation and enhancing it for DNS formation (see attached plot).

image (3)

**Review by jeffriley — CHANGES_REQUESTED** [review]
Just a few comments @ilyamandel 

BaseBinaryStar.cpp
Line 1602 - Not a big deal, but you don't need the enclosing parentheses (I'll sometimes put parentheses where the compiler doesn't really need them just to make something easier for a human to parse, but I don't think you need them here).

BaseStar.cpp
CalculateConvectiveEnvelopeLambdaPicker(), args could be const, function could be const
Line 3836 - use class variable m_Log10Metallicity instead

FGB.h
Line 59 - small point: function calls incur overhead (to build and collapse the stack frame at least, though in this case a good optimising compiler would optimise the call away) - why use Radius() when m_Radius is available?  Radius() is just a getter for m_Radius - I'd be surprised if we ever changed it.

GiantBranch.cpp
Is it worth moving CalculateRadialExtentConvectiveEnvelope() to GiantBranch.h?
Line 1056 - change `1` to `1.0`

GiantBranch.h
Why is CalculateConvectiveEnvelopeLambdaPicker() declared here?  I don't see a definition in the .cpp file (am I just missing it?)

HG.cpp
Is it worth moving CalculateRadialExtentConvectiveEnvelope() to HG.h?

MainSeuqnce.cpp
Line 493 - change `0` to `0.0`

Star.h
CalculateConvectiveEnvelopeLambdaPicker(), args could be const, function could be const

**Comment by ilyamandel** [comment]
Thank you very much for the review, @jeffriley !  All requested changes made.

**Review by veome22 — CHANGES_REQUESTED** [review]
Hi @ilyamandel , the PR looks mostly great! Here are a few minor things I thought to change:

MainSequence.cpp
- `CalculateConvectiveEnvelopeMass()` currently sets `massEnvelope0 = 0.35` by default. For a star below 0.35 M_sun, the envelope mass would be greater than the total stellar mass.

TPAGB.h
- `CalculateConvectiveCoreRadius()` probably needs to check that `5.0 * CalculateRemnantRadius <= m_Radius` (also from Hurley (2000), last sentence of Sec. 6

**Comment by ilyamandel** [comment]
@veome: thank you, very nicely spotted!

**Review by veome22 — APPROVED** [review]

**Review by jeffriley — APPROVED** [review]
Thanks @ilyamandel !

**Pull request merged**
