### PR TITLE
Modified single line from pythonSubmit.py, set circualrisation from F…

### LINKED ISSUE #564: Change the tides default description in the pythonSubmit
Currently, in the `pythonSubmit.py`:
> circularise_binary_during_mass_transfer = False

Change to:
> circularise_binary_during_mass_transfer = True

### PR DESCRIPTION
**Pull request by avigna**
…alse to True

### CODE REVIEW

**Review by ilyamandel — COMMENTED** [review]
The change looks great.  But since we've been not circularising recently, it would be very nice to test the impact of this change at a population level.

**Comment by avigna** [comment]
COMPAS_number_all_DCOSs
COMPAS_number_merging_DCOSs

Here a comparison using v02.19.04 for the non-circularised vs v02.19.01 for circularised. Results seem to match... even more than I naively expected. In both plots, circularisation leads to more non-merging and merging DCOs.

Circularisation decreases the orbit to periastron. Therefore it could enhance stellar mergers, but also enable non-merging DCOs to become merging DCOs. It seems that overall circularisation enhances rates.

**Comment by avigna** [comment]
Evidence of comparison:
```
[avignago@farnarkle1 rwillcox]$ diff ./alej_runs_MTcirc-false/Z0.0001/batch_0/Run_Details ./alej_runs_MTcirc-fix/Z0.00
01/batch_0/Run_Details
2c2
< COMPAS v02.19.04
---
> COMPAS v02.19.01
7c7
< Start generating binaries at Sun May 30 11:16:07 2021
---
> Start generating binaries at Wed May  5 12:04:06 2021
11c11
< End generating binaries at Sun May 30 15:44:20 2021
---
> End generating binaries at Wed May  5 16:35:52 2021
13,14c13,14
< Clock time = 16050.9 CPU seconds
< Wall time  = 0004:28:13 (hhhh:mm:ss)
---
> Clock time = 16230.5 CPU seconds
> Wall time  = 0004:31:46 (hhhh:mm:ss)
32c32
< circularise-binary-during-mass-transfer = FALSE, USER_SUPPLIED, BOOL
---
> circularise-binary-during-mass-transfer = TRUE, USER_SUPPLIED, BOOL
62c62
< grid = '/home/rwillcox/output_oz101/alej_runs_MTcirc-false/Z0.0001/grid_0.csv', USER_SUPPLIED, STRING
---
> grid = '/home/rwillcox/output_oz101/alej_runs_MTcirc-fix/Z0.0001/grid_0.csv', USER_SUPPLIED, STRING
144c144
< output-path = '/home/rwillcox/output_oz101/alej_runs_MTcirc-false/Z0.0001', USER_SUPPLIED, STRING
---
> output-path = '/home/rwillcox/output_oz101/alej_runs_MTcirc-fix/Z0.0001', USER_SUPPLIED, STRING
188c188
< actual-output-path = /home/rwillcox/output_oz101/alej_runs_MTcirc-false/Z0.0001, CALCULATED, STRING
---
> actual-output-path = /home/rwillcox/output_oz101/alej_runs_MTcirc-fix/Z0.0001, CALCULATED, STRING
190c190
< Actual random seed = 1622337366, CALCULATED, UNSIGNED_LONG
---
> Actual random seed = 1620180245, CALCULATED, UNSIGNED_LONG
```

**Review by ilyamandel — APPROVED** [review]
Thank you very much for the comparison, @avigna !  It looks awesome.

**Comment by ilyamandel** [comment]
I approved the commit, but there now seems to be a conflict, presumably due to new changes since your initial PR.  @avigna -- can you please pull the latest dev into your branch and re-commit?

**Comment by TomWagg** [comment]
@avigna, could you also show how the eccentricity of the sources at DCO formation changes for that run? Just wondering how strong an effect this has 🙂

**Comment by avigna** [comment]
@ilyamandel done (I think)!
@TomWagg, will do, ping me if I haven't done it in a couple days.

**Comment by avigna** [comment]
@TomWagg here a couple of CDFs showing eccentricty at DCO formation for BBHs, which are the most representative sample because they are more prone to experience complete fallback. They look quite alright/similar to me particularly taking into account I just did the CDF without accounting for yields or so (but with runs using effectively identical parameters).

eccentricity_all_BBHs
eccentricity_merging_BBHs

**Pull request merged**
