### PR TITLE
Git workflow update

### LINKED ISSUE #325: Git workflow instructions refer to master, not production
https://github.com/TeamCOMPAS/COMPAS/blob/dev/docs/dev-git-workflow.md refers to master, which has now been replaced by production.  Should be updated.

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Cleaned up the git workflow doc

- Edited sections to match the current COMPAS git workflow, since it has evolved somewhat over the past year
- Added images and other icons to guide the eye (and make it more readable)
- Updated references from `master` to `production`
- Moved all image files to `docs/media/` and updated relevant links elsewhere in the repo

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
@themikelau good catch, thanks for fixing those

**Review by ilyamandel — APPROVED** [review]
I wouldn't put this in the changelog -- since the code hasn't changed, just the workflow documentation (what are your thoughts, @jeffriley ? ) -- but happy to approve either way.  Nicely done, @reinhold-willcox !

**Comment by jeffriley** [comment]
I tend to agree re changelog.h.  The LateX COMPAS manual has its own revision history page.  Maybe other documentation should maintain its own revision history (not in the code changelog).

**Comment by reinhold-willcox** [comment]
@ilyamandel @jeffriley makes sense, though I'm not too fussed about making a changelog for all the little documentation bits. 

Changelog has been reupdated.

**Review by ilyamandel — APPROVED** [review]
Thanks, looks great!

**Pull request merged**
