### PR TITLE
Add compas spin prescriptions

### PR DESCRIPTION
**Pull request by FloorBroekgaarden**

### CODE REVIEW

**Comment by FloorBroekgaarden** [comment]
don't review this yet, work in progress

**Comment by FloorBroekgaarden** [comment]
adding @veome22 as reviewer

**Comment by reinhold-willcox** [comment]
@FloorBroekgaarden, these same files are included in PR #887. It's a bit redundant to keep both. Would you be ok with removing either this PR or these two files in the other PR?

**Review by blazehoulden — COMMENTED** [review]
Everything looked good and worked when I ran the notebook and looked through the python file. I tried it with some previous COMPAS data on hand as well as the files you suggested, with no problems. Only thing was in the jupyter notebook, the 16th cell plotting the Bavera et al 2021 fits had an extra bit of code that stopped it from executing at the end: #<div class="alert alert-block alert-warning">. When commenting this out everything worked perfectly, probably just a typo that can be removed.

**Comment by ilyamandel** [comment]
@FloorBroekgaarden -- note comments above, I think this is ready to go once those are addressed.

**Comment by ilyamandel** [comment]
@FloorBroekgaarden -- note the merge conflict above.  I am putting this into draft mode for now, please remove draft mode when it's ready.

**Comment by FloorBroekgaarden** [comment]
yes, I think this PR can be removed once PR 887 is submitted..?

**Comment by FloorBroekgaarden** [comment]
Ah! Sorry now I see that the PR #887 is merged into dev. Reinhold was right: I had already earlier merged these updates into the same update as the CHE demo PR. So this PR is redundant. Will close it now,

**Pull request closed without merging**
