### PR TITLE
Updates to Demo Plot

### LINKED ISSUE #523: Demo plotting file not updated to take h5 output
**Is your feature request related to a problem? Please describe.**
Title says it all - the plotting file in docs/demo/ which is used to generate the plot in the COMPAS paper, reads in the old csv output format, but we now output hdf5 by default. 

**Describe the solution you'd like**
The file should be updated to reflect this. 

**Describe alternatives you've considered**
If a user wants to use the plotter, we could require that they do a run with the output type set to csv (non-default).

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Moved demo/ folder to root level, and updated the plotting script to read in h5 data.

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
@themikelau I didn't touch the chirpmass jupyter notebook, but that may also be out of sync.

**Comment by themikelau** [comment]
@reinhold-willcox : The getting_started instructions for the demo needs to be updated accordingly. I have already made some changes. Can you check these changes and also update Section 2.2?

I've checked that the single_sys_plotter.py script works and the pythonSubmitDemo.py works.

**Review by themikelau — CHANGES_REQUESTED** [review]
See above.

**Comment by themikelau** [comment]
What is gw151226evol.eps? Was it committed by mistake and can be deleted?

**Comment by themikelau** [comment]
I don't think the chirp mass Jupyter notebook needs to be updated, because it is designed to read a H5 file that will be made available from Zenodo.

**Comment by reinhold-willcox** [comment]
@themikelau The eps file is the image generated by the script - eps files are vectorized so they scale better. It is the same one used in the paper, so I think it makes sense to include it.

**Comment by reinhold-willcox** [comment]
@themikelau Are there other issues with this PR you would like me to address, or is it safe to pull this in?

**Comment by themikelau** [comment]
> @reinhold-willcox : The getting_started instructions for the demo needs to be updated accordingly. I have already made some changes. Can you check these changes and also update Section 2.2?

Have you done this?

**Review by themikelau — APPROVED** [review]
Happy with everything here.

**Pull request merged**
