### PR TITLE
Fix core and envelope calculations: HeHG and TPAGB

### PR DESCRIPTION
**Pull request by SimonStevenson**
This PR addresses issue #105 

See that issue for a description of the problem (including plots).

Up to the EAGB, the envelope and cores look ok. Then, for type 6 (TPAGB) things go wrong.

For this 7.5 Msol Star, McBAGB ~2 Msol

See Section 5.4 in the SSE paper (Hurley et al. 2000, https://ui.adsabs.harvard.edu/abs/2000MNRAS.315..543H/abstract)

Using current dev, I tried simulating the following mass stars: 7.0, 7.1, 7.2, 7.3, 7.4, 7.5, 7.6 Msol , all at solar metallicity.

Here is the output:

0: RandomSeed = 1, Initial Mass = 7,   Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
1: RandomSeed = 2, Initial Mass = 7.1, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
2: RandomSeed = 3, Initial Mass = 7.2, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
3: RandomSeed = 4, Initial Mass = 7.3, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
4: RandomSeed = 5, Initial Mass = 7.4, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
5: RandomSeed = 6, Initial Mass = 7.5, Metallicity = 0.0142, Neutron_Star
6: RandomSeed = 7, Initial Mass = 7.6, Metallicity = 0.0142, Neutron_Star

Looks like currently in COMPAS, the stars up to (and including) 7.4 Msol form ONeWDs, whilst the stars 7.5 Msol and above form NSs. 

It seems that this issue is only really an issue with book-keeping (properly calculating and recording the envelope mass), and does not affect the evolution of the stars.

On the EAGB:
- Mc = McHe = McBAGB
- CO core mass increases from 0 for the first time. Should increase to McDU (roughly 1.328 Msol). When it reaches this point, second dredge up happens, reducing Mhe to McDU and we switch to the TPAGB. This all looks correct, as far as I can tell.

On the TPAGB:
- CO core mass, He core mass and core mass are not the same, should be I think (check Hurley 2000). Previously, CalculateHeCoreMassOnPhase was simply doing return m_HeCoreMass; , which meant that m_HeCoreMass was not being updated.
Solution :
CalculateHeCoreMassOnPhase should return CoreMass

This is the bug responsible for the titular issue in #105 (orange curve above blue curve in the plots).

- envelope mass at this stage should be total mass - core mass
Solution :
CalculateEnvelopeMassOnPhase return Mass - CoreMass

This resolves the green curve being above the blue curve in the plots.

- star should be stripped/become WD when Env mass = 0 (or alternatively, where currently core mass > total mass)
Solution :
ResolveEnvelopeMassOnPhase should check when core mass > mass (or equivalently, when envelope mass <= 0)

Previously checked for stuff to do with supernovae (McSN). I wasn't sure if this should remain, so I have removed it.

Peforming the same run of 7.0-7.6 Msol stars as above including these fixes yields:

0: RandomSeed = 1, Initial Mass = 7, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
1: RandomSeed = 2, Initial Mass = 7.1, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
2: RandomSeed = 3, Initial Mass = 7.2, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
3: RandomSeed = 4, Initial Mass = 7.3, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
4: RandomSeed = 5, Initial Mass = 7.4, Metallicity = 0.0142, Oxygen-Neon_White_Dwarf
5: RandomSeed = 6, Initial Mass = 7.5, Metallicity = 0.0142, Neutron_Star
6: RandomSeed = 7, Initial Mass = 7.6, Metallicity = 0.0142, Neutron_Star

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
@SimonStevenson 

Thanks for doing this! I'm not sure I fully follow your comments though.

Your before and after runs appear to be the same, unless I'm missing something. I'm also not clear on what the correct answer should be (i.e what is the minimum single star zams mass at solar metal. that we expect theoretically should become a NS?)

**Comment by SimonStevenson** [comment]
Indeed, them being the same before/after is evidence that this issue was not affecting the evolution of these stars, just the book keeping of their core/envelope masses. Regarding the separation between WD/NS (which is not exactly the point of this issue), I'm also not sure what the "right" answer is, but this seems reasonable (we expect the transition around 8 Msol), and my changes don't affect it. To see the impact of the changes, see the plots in the issue.

**Comment by SimonStevenson** [comment]
@jeffriley version bumped, please check :)

**Comment by SimonStevenson** [comment]
I don't follow your concern @ilyamandel . These are the functions which calculate these quantities.

**Comment by ilyamandel** [comment]
@SimonStevenson -- you replaced 

double          CalculateEnvelopeMassOnPhase(const double p_Tau)                                 { return m_EnvMass; } 

with

double          CalculateEnvelopeMassOnPhase(const double p_Tau)                                 { return m_Mass - std::max(m_COCoreMass, m_HeCoreMass);}       

in TPAGB.h.  Great, I agree this function returns the right quantity -- but it doesn't seem to update m_EnvMass.  So after running this function, can it be that it's output is different from m_EnvMass?  Can you be sure that the if statement check you use in TPAGB.cpp, "(utils::Compare(m_EnvMass, 0.0) <= 0)", is using the correct envelope mass?

**Comment by ilyamandel** [comment]
What if we do away with m_EnvMass altogether?  It seems superfluous since we can always get the correct value by calling CalculateEnvelopeMassOnPhase, so it only makes life needlessly complicated by requiring us to sync another variable which doesn't hold any info that can be readily obtained...

**Comment by SimonStevenson** [comment]
ResolveEnvelopeMassOnPhase in BaseStar is the function that updates EnvMass by calling CalculateEnvelopeMassOnPhase. In particular:
ResolveEnvelopeMassOnPhase(const double p_Tau){ m_EnvMass = CalculateEnvelopeMassOnPhase(p_Tau); }
I pointed this out in the issue.
All I did was fix the implementation of  CalculateEnvelopeMassOnPhase. Previously, it wasn't doing anything, now it does the right thing.

**Comment by SimonStevenson** [comment]
> What if we do away with m_EnvMass altogether? It seems superfluous since we can always get the correct value by calling CalculateEnvelopeMassOnPhase, so it only makes life needlessly complicated by requiring us to sync another variable which doesn't hold any info that can be readily obtained...

This is beside the point. Either way, it still wasn't being calculated properly; it wouldn't matter if this was precomputed, or calculated when needed, its still wrong

**Comment by ilyamandel** [comment]
I agree that you are fixing things, I am just thinking that we should fix it for good once we are at it. :) 

Your TPAGB.h ResolveEnvelopeMassOnPhase will override the definition of ResolveEnvelopeMassOnPhase from the parent class BaseStar.h -- so, unless I am mistaken, you are no longer updating the m_EnvMass variable when calling ResolveEnvelopeMassOnPhase for TPAGB stars.

**Comment by SimonStevenson** [comment]
There is no implementation of ResolveEnvelopeMassOnPhase in TPAGB. I didn't edit one in this PR, so not sure what you are referring to.

I thought TPAGB will use the BaseStar one. I must admit I did get a bit lost in inheritance and had to ask @jeffriley for help on this.

**Comment by ilyamandel** [comment]
You are fine, I got confused between the Resolve... and Calculate... functions.  Spotted my mistake already before your response. :D Mea culpa.

**Comment by SimonStevenson** [comment]
Thanks @ilyamandel . If you still think that we should reconsider how we calculate envelope masses (or whether we should calculate them at all) please feel free to raise a new issue, and we can figure out if there is an alternate proposal that makes more sense than what we are doing now.

**Comment by SimonStevenson** [comment]
@jeffriley no I added it in response to your comment, you're not going crazy :)

**Pull request merged**
