### PR TITLE
add Spell check CI

### PR DESCRIPTION
**Pull request by avivajpeyi**
Requires #902 

There are some spelling errors in the codebase. This adds a spell-check CI tool.

To fix the spelling mistakes, one can interactively go through the mistakes with:
``` 
 codespell -i 3 -L nd --ignore-words=.dictionary.txt --skip '*.eps,*.svg ,*.ipynb' -w .` 
```

Some of the spelling errors: 
https://github.com/TeamCOMPAS/COMPAS/actions/runs/4465730679/jobs/7843079610?pr=940#step:4:59
```python
online-docs/notebooks/DataAnalysis.ipynb:131: occured ==> occurred
online-docs/notebooks/DataAnalysis.ipynb:133: occured ==> occurred
online-docs/notebooks/DataAnalysis.ipynb:2923: succint ==> succinct
online-docs/notebooks/DataAnalysis.ipynb:3003: Retrive ==> Retrieve
online-docs/notebooks/DataAnalysis.ipynb:3106: corrresponding ==> corresponding
online-docs/notebooks/DataAnalysis.ipynb:3172: occurence ==> occurrence
online-docs/notebooks/DataAnalysis.ipynb:3190: occurence ==> occurrence
online-docs/notebooks/DataAnalysis.ipynb:3337: Retrive ==> Retrieve
online-docs/notebooks/DataAnalysis.ipynb:3488: specifc ==> specific
online-docs/notebooks/DataAnalysis.ipynb:4794: occurences ==> occurrences
online-docs/notebooks/DataAnalysis.ipynb:4798: occured ==> occurred
online-docs/notebooks/DataAnalysis.ipynb:5461: aquired ==> acquired
online-docs/notebooks/DataAnalysis.ipynb:5488: asthetic ==> aesthetic
online-docs/notebooks/DataAnalysis.ipynb:5559: Tht ==> The, That
compas_python_utils/cosmic_integration/totalMassEvolvedPerZ.py:121: indepent ==> independent
online-docs/pages/User guide/Pre-processing/pre-processing-sampling.rst:61: overriden ==> overridden
online-docs/pages/User guide/Pre-processing/pre-processing-sampling.rst:77: relevent ==> relevant
online-docs/pages/User guide/Pre-processing/pre-processing-sampling.rst:101: relevent ==> relevant
compas_python_utils/preprocessing/runSubmit.py:160: Exectute ==> Execute
src/BaseBinaryStar.cpp:292: alread ==> already
src/BaseBinaryStar.cpp:303: alread ==> already
src/BaseBinaryStar.cpp:715: retireved ==> retrieved
src/BaseBinaryStar.cpp:913: properites ==> properties
src/BaseBinaryStar.cpp:951: prevous ==> previous
src/BaseBinaryStar.cpp:1400: transfering ==> transferring
src/BaseBinaryStar.cpp:2358: documetation ==> documentation
src/changelog.h:60: alwas ==> always
src/changelog.h:101: orginally ==> originally
src/changelog.h:111: occurences ==> occurrences
src/changelog.h:128: occurences ==> occurrences
src/changelog.h:201: extention ==> extension
src/changelog.h:253: errorneously ==> erroneously
src/changelog.h:382: superceeded ==> superseded
src/changelog.h:442: functionaltiy ==> functionality
src/changelog.h:565: fron ==> from, front
src/changelog.h:675: accreting ==> accrediting
src/changelog.h:740: chunck ==> chunk
src/changelog.h:743: ouput ==> output
src/changelog.h:860: occurences ==> occurrences
src/changelog.h:861: occurences ==> occurrences
src/changelog.h:876: occuring ==> occurring
src/changelog.h:979: calulated ==> calculated
src/changelog.h:980: accomodate ==> accommodate
src/changelog.h:991: Modifed ==> Modified
src/EAGB.cpp:995: shoule ==> should
online-docs/notebooks/WorkingWithHDF5.ipynb:1389: paramter ==> parameter
online-docs/pages/User guide/COMPAS output/standard-logfiles-annotations.rst:78: anotations ==> annotations
online-docs/pages/User guide/COMPAS output/standard-logfiles-annotations.rst:112: specfied ==> specified
src/typedefs.h:120: objec ==> object
online-docs/pages/Developer guide/developer-guide.rst:8: scrpts ==> scripts
compas_python_utils/cosmic_integration/ClassCOMPAS.py:68: assumming ==> assuming
misc/examples/Tutorials/DataAnalysis.py:80: occured ==> occurred
misc/examples/Tutorials/DataAnalysis.py:82: occured ==> occurred
misc/examples/Tutorials/DataAnalysis.py:136: succint ==> succinct
misc/examples/Tutorials/DataAnalysis.py:176: Retrive ==> Retrieve
misc/examples/Tutorials/DataAnalysis.py:236: corrresponding ==> corresponding
misc/examples/Tutorials/DataAnalysis.py:276: occurence ==> occurrence
misc/examples/Tutorials/DataAnalysis.py:289: Retrive ==> Retrieve
misc/examples/Tutorials/DataAnalysis.py:377: specifc ==> specific
misc/examples/Tutorials/DataAnalysis.py:393: occurences ==> occurrences
misc/examples/Tutorials/DataAnalysis.py:397: occured ==> occurred
misc/examples/Tutorials/DataAnalysis.py:426: aquired ==> acquired
misc/examples/Tutorials/DataAnalysis.py:442: asthetic ==> aesthetic
compas_python_utils/h5copy.py:190: datset ==> dataset
compas_python_utils/h5copy.py:205: chunck ==> chunk
compas_python_utils/h5copy.py:208: unecessary ==> unnecessary
compas_python_utils/h5copy.py:225: performace ==> performance
compas_python_utils/h5copy.py:243: analagous ==> analogous
compas_python_utils/h5copy.py:577: propertly ==> properly, property
src/profiling.cpp:151: recored ==> recorded
src/HG.cpp:913: unknow ==> unknown
src/HG.cpp:1083: shoule ==> should
src/HeHG.h:42: defintion ==> definition
src/Makefile.docker:6: instaed ==> instead
online-docs/pages/User guide/Running COMPAS/running-via-docker.rst:7: beween ==> between
online-docs/pages/User guide/Post-processing/post-processing-hdf5-info.rst:30: datset ==> dataset
online-docs/pages/User guide/Post-processing/post-processing-hdf5-info.rst:46: unecessary ==> unnecessary
online-docs/pages/User guide/Post-processing/post-processing-hdf5-info.rst:61: performace ==> performance
online-docs/pages/User guide/Post-processing/post-processing-hdf5-info.rst:78: analagous ==> analogous
src/utils.cpp:354: wich ==> which
src/utils.cpp:500: succussfully ==> successfully
src/utils.cpp:532: succussfully ==> successfully
src/utils.cpp:564: succussfully ==> successfully
src/utils.cpp:596: succussfully ==> successfully
src/utils.cpp:628: succussfully ==> successfully
src/utils.cpp:660: succussfully ==> successfully
src/utils.cpp:714: alread ==> already
src/utils.cpp:731: alread ==> already
src/utils.cpp:995: convienience ==> convenience
src/utils.cpp:1002: specificed ==> specified
online-docs/pages/User guide/Program options/program-options-list-defaults.rst:124: Deafult ==> Default
online-docs/pages/User guide/Program options/program-options-list-defaults.rst:388: Paramter ==> Parameter
online-docs/pages/User guide/Program options/program-options-list-defaults.rst:841: degnerate ==> degenerate
misc/examples/methods_paper_plots/fig_8_initial_core_final_mass_relations/pythonSubmitFryerRapid.py:98: amoungst ==> amongst
misc/examples/methods_paper_plots/fig_8_initial_core_final_mass_relations/pythonSubmitFryerRapid.py:808: exectute ==> execute
online-docs/notebooks/CosmicIntegration.ipynb:272: acces ==> access
online-docs/notebooks/CosmicIntegration.ipynb:693: densitity ==> density
online-docs/notebooks/CosmicIntegration.ipynb:1398: LoD ==> load, loud, lode
online-docs/notebooks/CosmicIntegration.ipynb:1398: Fo ==> Of, For, To, Do, Go
online-docs/notebooks/CosmicIntegration.ipynb:1398: oLY ==> only
online-docs/notebooks/CosmicIntegration.ipynb:1628: indiviual ==> individual
online-docs/notebooks/CosmicIntegration.ipynb:1778: quicly ==> quickly
online-docs/notebooks/CosmicIntegration.ipynb:1811: nNumber ==> number
online-docs/notebooks/CosmicIntegration.ipynb:1992: reight ==> right, eight, freight
online-docs/notebooks/CosmicIntegration.ipynb:2280: everthing ==> everything
online-docs/notebooks/CosmicIntegration.ipynb:3187: Ot ==> To, Of, Or, Not
online-docs/notebooks/CosmicIntegration.ipynb:3221: distrbution ==> distribution
online-docs/notebooks/CosmicIntegration.ipynb:3258: UE ==> USE, DUE
online-docs/notebooks/CosmicIntegration.ipynb:3305: distrbution ==> distribution
misc/examples/methods_paper_plots/fig_16_Chirpmass_distribution/Fig16_pythonSubmit.py:71: amoungst ==> amongst
misc/examples/methods_paper_plots/fig_16_Chirpmass_distribution/Fig16_pythonSubmit.py:782: exectute ==> execute
misc/examples/methods_paper_plots/fig_16_Chirpmass_distribution/stroopwafel_interface.py:266: parellel ==> parallel
misc/examples/methods_paper_plots/fig_16_Chirpmass_distribution/stroopwafel_interface.py:323: Adaptaion ==> Adaptation
src/BaseStar.cpp:171: detais ==> details
src/BaseStar.cpp:404: retireved ==> retrieved
src/BaseStar.cpp:1374: indeces ==> indices
src/BaseStar.cpp:2048: paramaters ==> parameters
src/BaseStar.cpp:2385: inital ==> initial
src/BaseStar.cpp:3076: necesarily ==> necessarily
src/BaseStar.cpp:3239: recalulate ==> recalculate
src/BaseStar.cpp:3242: abvious ==> obvious
misc/unsupported_utils/compasUtils.py:224: icludes ==> includes
compas_python_utils/cosmic_integration/FastCosmicIntegration.py:169: initalise ==> initialise
compas_python_utils/cosmic_integration/FastCosmicIntegration.py:178: occured ==> occurred
compas_python_utils/cosmic_integration/FastCosmicIntegration.py:322: intput ==> input
compas_python_utils/cosmic_integration/FastCosmicIntegration.py:596: wan't ==> want, wasn't
compas_python_utils/cosmic_integration/FastCosmicIntegration.py:611: seperate ==> separate
compas_python_utils/cosmic_integration/FastCosmicIntegration.py:731: distrbution ==> distribution
paper.md:135: NWO ==> NOW
compas_python_utils/cosmic_integration/ClassMSSFR.py:31: amongs ==> among
compas_python_utils/cosmic_integration/ClassMSSFR.py:200: amongs ==> among
compas_python_utils/cosmic_integration/ClassMSSFR.py:246: fuction ==> function
compas_python_utils/cosmic_integration/ClassMSSFR.py:333: happpens ==> happens
src/HeHG.cpp:255: unknow ==> unknown
src/MainSequence.cpp:106: Calcluate ==> Calculate
src/MainSequence.cpp:579: instaed ==> instead
compas_python_utils/detailed_evolution_plotter/plot_detailed_evolution.py:675: synopsys ==> synopsis
compas_python_utils/preprocessing/sampleMoeDiStefano.py:454: mye ==> may, my
compas_python_utils/preprocessing/sampleMoeDiStefano.py:486: mye ==> may, my
compas_python_utils/preprocessing/sampleMoeDiStefano.py:488: mye ==> may, my
src/Log.h:103: datset ==> dataset
src/Log.h:122: unecessary ==> unnecessary
src/Log.h:139: performace ==> performance
src/Log.h:157: analagous ==> analogous
src/Log.h:194: outher ==> other, outer
src/Log.h:299: anotations ==> annotations
src/Log.h:328: idenitify ==> identify
src/Log.h:460: swithcing ==> switching
src/Log.h:463: swithcing ==> switching
src/Log.h:572: defauts ==> defaults
src/Log.h:620: detials ==> details
src/BaseBinaryStar.h:333: asume ==> assume
src/BaseBinaryStar.h:334: asume ==> assume
src/BaseBinaryStar.h:403: orginal ==> original
src/BaseBinaryStar.h:599: Initally ==> Initially
misc/unsupported_utils/magnitude_module.py:248: definte ==> definite, define
src/yaml.h:22: writte ==> write, written
src/Options.h:43: enetered ==> entered
src/Options.h:48: sepcified ==> specified
src/Options.h:815: ammount ==> amount
src/Options.h:1013: valies ==> values
misc/examples/methods_paper_plots/fig_8_initial_core_final_mass_relations/pythonSubmitMandelMueller.py:98: amoungst ==> amongst
misc/examples/methods_paper_plots/fig_8_initial_core_final_mass_relations/pythonSubmitMandelMueller.py:808: exectute ==> execute
online-docs/pages/User guide/docker.rst:8: beween ==> between
online-docs/pages/User guide/docker.rst:118: availabe ==> available
online-docs/pages/User guide/docker.rst:181: anthing ==> anything
online-docs/pages/User guide/docker.rst:230: supressed ==> suppressed
misc/examples/methods_paper_plots/fig_6_max_R/pythonSubmit.py:98: amoungst ==> amongst
misc/examples/methods_paper_plots/fig_6_max_R/pythonSubmit.py:808: exectute ==> execute
src/CHeB.cpp:1471: shoule ==> should
src/main.cpp:61: vie ==> via
src/GiantBranch.cpp:765: paramaters ==> parameters
src/GiantBranch.cpp:798: paramaters ==> parameters
src/Star.cpp:418: aboslute ==> absolute
src/Star.cpp:442: discared ==> discarded
online-docs/pages/User guide/Running COMPAS/running-via-cmdline.rst:6: ouput ==> output
online-docs/pages/Developer guide/changelog.rst:37: automaticall ==> automatically, automatic
online-docs/pages/Developer guide/changelog.rst:52: whenver ==> whenever
src/yaml.cpp:178: alreay ==> already
src/Errors.cpp:23: obejcts ==> objects
src/Errors.cpp:85: retreives ==> retrieves
src/Errors.cpp:104: nmae ==> name
src/BinaryConstituentStar.cpp:112: accreting ==> accrediting
src/BinaryConstituentStar.cpp:131: UNIFROM ==> UNIFORM
src/BinaryConstituentStar.cpp:302: accreting ==> accrediting
src/BinaryConstituentStar.cpp:303: accreting ==> accrediting
src/BinaryConstituentStar.cpp:309: consisten ==> consistent
src/HG.h:42: defintion ==> definition
src/HG.h:157: Initally ==> Initially
online-docs/pages/Getting started/dev-git-workflow.rst:226: interferring ==> interfering
online-docs/pages/Getting started/dev-git-workflow.rst:481: uncommited ==> uncommitted
online-docs/pages/Getting started/dev-git-workflow.rst:588: readded ==> read
online-docs/pages/Getting started/dev-git-workflow.rst:966: editted ==> edited
online-docs/pages/Getting started/dev-git-workflow.rst:973: editting ==> editing
online-docs/pages/Getting started/dev-git-workflow.rst:1043: occured ==> occurred
src/TPAGB.cpp:890: shoule ==> should
online-docs/pages/User guide/Post-processing/post-processing-h5view.rst:113: argement ==> argument
misc/examples/methods_paper_plots/fig_16_Chirpmass_distribution/make_fig_16.py:74: setttings ==> settings
misc/examples/methods_paper_plots/fig_8_initial_core_final_mass_relations/pythonSubmitDefaults.py:98: amoungst ==> amongst
misc/examples/methods_paper_plots/fig_8_initial_core_final_mass_relations/pythonSubmitDefaults.py:808: exectute ==> execute
compas_python_utils/h5view.py:77: argement ==> argument
compas_python_utils/h5view.py:141: datsets ==> datasets
utils/examples/methods_paper_plots/detailed_evolution/runSubmitDemo.py:161: exectute ==> execute
src/HeMS.cpp:87: Seqeuence ==> Sequence
src/HeMS.cpp:380: shoule ==> should
src/Options.cpp:1114: paramter ==> parameter
src/Options.cpp:1949: specifed ==> specified
src/Options.cpp:2199: Seconday ==> Secondary
src/Options.cpp:2200: Seconday ==> Secondary
src/Options.cpp:2445: specfied ==> specified
src/Options.cpp:2485: retreived ==> retrieved
src/Options.cpp:2627: sourrounding ==> surrounding
src/Options.cpp:2795: maxmimum ==> maximum
src/Options.cpp:3121: beteen ==> between
src/Options.cpp:3487: parm ==> param, pram, parma
misc/examples/methods_paper_plots/README.md:5: guaruntee ==> guarantee
misc/examples/methods_paper_plots/fig_5_HR_diagram/pythonSubmit.py:98: amoungst ==> amongst
misc/examples/methods_paper_plots/fig_5_HR_diagram/pythonSubmit.py:808: exectute ==> execute
online-docs/pages/User guide/Running COMPAS/running-via-python.rst:49: exceuted ==> executed
online-docs/pages/User guide/COMPAS output/standard-logfiles-format.rst:80: datset ==> dataset
online-docs/pages/User guide/Tutorial/example-compas-run-grid.rst:46: turtorial ==> tutorial
py_tests/test_run_submit.py:29: defualt ==> default
online-docs/index.rst:13: bject ==> object
src/HeGB.cpp:52: lamda ==> lambda
src/HeGB.cpp:54: lamda ==> lambda
src/HeGB.cpp:54: lamda ==> lambda
misc/unsupported_utils/README.md:3: guaruntee ==> guarantee
src/NS.cpp:325: recyled ==> recycled
src/NS.cpp:371: accreting ==> accrediting
src/NS.cpp:383: accreting ==> accrediting
online-docs/pages/User guide/COMPAS output/standard-logfiles-record-specification.rst:11: availabe ==> available
misc/unsupported_utils/h5rewrite.py:112: Everytime ==> Every time
src/Log.cpp:218: loggging ==> logging
src/Log.cpp:458: containg ==> containing
src/Log.cpp:814: ouput ==> output
src/Log.cpp:1525: sould ==> could, should, sold
src/Log.cpp:1557: sould ==> could, should, sold
src/Log.cpp:1884: deatils ==> details
src/Log.cpp:1946: defaut ==> default
src/Log.cpp:1949: correspoding ==> corresponding
src/Log.cpp:1969: defaut ==> default
src/Log.cpp:1972: correspoding ==> corresponding
src/Log.cpp:2297: datset ==> dataset
src/Log.cpp:2625: proerty ==> property, poetry
src/Log.cpp:2757: accomodates ==> accommodates
src/Log.cpp:2773: fromat ==> format
src/Log.cpp:2773: accomodates ==> accommodates
src/Log.cpp:2774: accomodates ==> accommodates
src/Log.cpp:2790: accomodates ==> accommodates
src/Log.cpp:3185: propert ==> property
src/Log.cpp:3245: completley ==> completely
src/Log.cpp:3353: bale ==> able, bail
src/Log.cpp:3362: bale ==> able, bail
src/Log.cpp:3380: initally ==> initially
online-docs/pages/User guide/Running COMPAS/running-via-docker-running.rst:29: availabe ==> available
online-docs/pages/User guide/Running COMPAS/running-via-docker-running.rst:31: whem ==> when
online-docs/pages/User guide/Running COMPAS/running-via-docker-running.rst:139: supressed ==> suppressed
online-docs/pages/User guide/COMPAS output/standard-logfiles-record-specifiers.rst:25: idenitify ==> identify
compas_python_utils/cosmic_integration/ClassCosmicIntegrator.py:36: inidividual ==> individual
compas_python_utils/cosmic_integration/ClassCosmicIntegrator.py:38: seperate ==> separate
compas_python_utils/cosmic_integration/ClassCosmicIntegrator.py:253: wich ==> which
compas_python_utils/cosmic_integration/ClassCosmicIntegrator.py:255: Calcultate ==> Calculate
src/utils.h:61: defaut ==> default
src/utils.h:64: correspoding ==> corresponding
compas_python_utils/preprocessing/stroopwafelInterface.py:222: parellel ==> parallel
compas_python_utils/preprocessing/stroopwafelInterface.py:234: overriden ==> overridden
compas_python_utils/preprocessing/stroopwafelInterface.py:280: Adaptaion ==> Adaptation
online-docs/pages/User guide/Pre-processing/pre-processing-yaml.rst:94: writte ==> write, written
online-docs/pages/Developer guide/Developer build/COMPAS-local-build.rst:31: exectuable ==> executable
src/FGB.cpp:32: performence ==> performance
src/FGB.cpp:171: shoule ==> should
src/FGB.cpp:223: begining ==> beginning
compas_python_utils/cosmic_integration/selection_effects.py:229: bondary ==> boundary
src/constants.h:532: valuse ==> values, value
src/constants.h:544: suppoted ==> supported
src/constants.h:671: tyoe ==> type, toey, toe
src/constants.h:1087: tranfer ==> transfer
online-docs/pages/User guide/COMPAS output/standard-logfiles-record-specification-stellar.rst:1676: accreting ==> accrediting
misc/examples/Tutorials/CosmicIntegration.py:193: acces ==> access
misc/examples/Tutorials/CosmicIntegration.py:398: densitity ==> density
misc/examples/Tutorials/CosmicIntegration.py:987: indiviual ==> individual
misc/examples/Tutorials/CosmicIntegration.py:1075: quicly ==> quickly
misc/examples/Tutorials/CosmicIntegration.py:1091: nNumber ==> number
misc/examples/Tutorials/CosmicIntegration.py:1128: reight ==> right, eight, freight
misc/examples/Tutorials/CosmicIntegration.py:1314: everthing ==> everything
misc/examples/Tutorials/CosmicIntegration.py:1762: distrbution ==> distribution
misc/examples/Tutorials/CosmicIntegration.py:1823: distrbution ==> distribution
src/BaseStar.h:366: enery ==> energy
src/BaseStar.h:377: relevent ==> relevant

```

Users can also configure this to run locally before any commit with 
```
pip install -e .[dev]
pre-commit install
```

Then, before every commit, the `.pre-commit` file is automatically run (and will block your commit until you fix your spelling mistakes).

### CODE REVIEW

**Comment by avivajpeyi** [comment]
To fix the spelling mistakes, one can interactively go through the mistakes with smth like: ` codespell -i 3 -L nd --ignore-words=.dictionary.txt --skip '*.eps *.svg *.ipynb'`

**Comment by ilyamandel** [comment]
This looks very cool, @avivajpeyi !  And yes, we should just start fixing the mistakes you already identified, even before you are ready to take this out of draft form and make it available for merging. :)

**Review by ilyamandel — APPROVED** [review]
Thanks for all of the spell-checking, @avivajpeyi!  This is awesome!

[Though I wish you hadn't replaced all instances of "accreting" with "accrediting" (even if the spell checker doesn't know the word, stars definitely accrete, not accredit -- took me a while to find/fix all of them :) ).]

**Comment by ilyamandel** [comment]
@avivajpeyi -- I am not merging this yet because you may have to do a merge from dev (I just pulled in Robert's long-delayed PR) -- but there also seem to be some weird unrelated issues with automated checks?

**Comment by avivajpeyi** [comment]
> [Though I wish you hadn't replaced all instances of "accreting" with "accrediting" (even if the spell checker doesn't know the word, stars definitely accrete, not accredit -- took me a while to find/fix all of them :) ).]

OMG my apologies! I think I just hit accept without thinking about some of the suggested fixes!  Thanks for catching this! 


>  there also seem to be some weird unrelated issues with automated checks?

1) the spell-check is failing atm because it thinks 'accreting' is not a word 😅 Not too much of an issue -- ill add it to the local dictionary file to prevent the spell-checker thinking this is incorrect
2) The docs are failing due to a bizarre error... These are unrelated to Roberts' changes I think...

**Comment by ilyamandel** [comment]
Thanks for looking into this, @avivajpeyi .  Can you add accrete and its variants to the local dictionary as part of this PR, merge in dev (just to ensure that there are no issues) -- and then we can merge this in?

**Pull request merged**
