### PR TITLE
Sync with dev

### PR DESCRIPTION
**Pull request by jeffriley**
The hotfix (PR#221) was into dev - to pick up the previous couple of changes to makefile.  This is to sync to master

### CODE REVIEW

**Comment by ilyamandel** [comment]
Now this seems to be trying to pull all of the changes made to dev in the last few days into master; do we really want to do that?

**Comment by ilyamandel** [comment]
@jeffriley -- is the intent of this to merge all of dev into master, or just a particular hot fix?  Currently, it seems it would do the former.  If the goal is to do the latter, let's adjust and get this approved ASAP.

**Comment by jeffriley** [comment]
It was ostensibly just to merge the hotfix, but I built the hotfix off dev, not master, so the intent now is to merge dev with master - I don't think there's anything in dev that shouldn't be in master is there?

**Comment by ilyamandel** [comment]
OK, I am fine with merging dev into master.

**Comment by ilyamandel** [comment]
@reinhold-willcox -- can't you cherry-pick the commits from dev to be pulled into master rather than creating another branch?

**Comment by jeffriley** [comment]
This was originally for hotfix (PR#221) 

Haven't all the other commits been reviewed and approved (for dev)?

**Comment by jeffriley** [comment]
So are we going to merge this request as is or do you want me to cherry pick just the hotfix?

**Comment by ilyamandel** [comment]
I'd say we wait until we have fixed the missing WR and LBV winds in SSE (which is a known bug), then re-test and pull everything to master.

**Comment by ilyamandel** [comment]
@SimonStevenson -- now that the wind fix PR is done, can you approve this so we can merge into Master?

**Pull request merged**
