### PR TITLE
Proper aliases for imports used in CHE demo

### PR DESCRIPTION
**Pull request by ana-lam**
Some import issues in the `old_FastCosmicIntegration.py` that is used in @FloorBroekgaarden's `CHE_evolution_demo.ipynb`. With these changes, you can run the last problem in the CHE Evolution Demo.

- For `old_ClassCOMPAS.py`: `import totalMassEvolvedPerZ as MPZ` - > `import old_totalMassEvolvedPerZ as MPZ`
- For `old_FastCosmicIntegration.py`: `import old_ClassCOMPAS` -> `import old_ClassCOMPAS as ClassCOMPAS` and `import old_selection_effects` -> `import old_selection_effects as selection_effects`

### CODE REVIEW

**Comment by FloorBroekgaarden** [comment]
will look at this in the coming days!

**Review by ilyamandel — APPROVED** [review]
This seems to be a good work around for getting older demos working -- thank you very much for contributing this, @ana-lam !

**Comment by ilyamandel** [comment]
@ana-lam -- there seem to be conflicts: are your changes based off the latest version of dev?  If not, you may need to pull the latest dev and merge that into your branch.

**Comment by ana-lam** [comment]
@ilyamandel All set to merge!

**Comment by FloorBroekgaarden** [comment]
merged. looks good!

**Pull request merged**
