### PR TITLE
Post processing updates

### LINKED ISSUE #525: Improve the MT donor history parameter
The MT donor history parameter currently records all MT events from a given star as vector of stellar types. As a string, it might look something like "2-7-8" to represent 3 different MT episodes where the donor was consecutively a type 2, 7, and 8 star. This is useful, but it breaks down for CE events and does not give any information about the companion.

It would be useful to expand this parameter to include more information. One possible option is for the final output to take something like the form: "2>1_8=2_13<8".

In this notation, `_` separates distinct events, the number on the left is the primary star (1), the number on the right is the secondary (2), and the symbol between them identifies whether the primary is MTing onto secondary `>` or vice versa `<`, or whether there was a common envelope `=`. I'm keen to hear other's thoughts on this, whether this is clear and sufficiently informative. This parameter would also only apply to a binary, since MT history is pretty dull for single stars.

### LINKED ISSUE #558: Post-processing testing
Since many of us do not usually run jupyter notebooks but may from time to time inadvertently impact them with other code changes, it would be great to have a simple test script that would:
1. Compile COMPAS
2. Do a small run of COMPAS
3. Run post-processing via Jupyter notebooks 
4. Create a log of any issues encountered

This wouldn't check for correctness, merely execution failures.  A future option would be to create a couple of simple plots that could be used for visual regression testing.

### LINKED ISSUE #682: [DOCS] 1_Slicing_Data.ipynb  | KeyError: "Unable to open object
_This issue is submitted as part of the JOSS review [#3838](https://github.com/openjournals/joss-reviews/issues/3838)_

### :bug:  description
I got a `KeyError: "Unable to open object (object 'DoubleCompactObjects' doesn't exist)"` on cell 5, evidently because the COMPAS_Ouptut file i generated with one of my test runs does not have double compact objects. 

### Recommendation
This notebook has some untold expectations of the output to process - I recommend the developers choose one output example and provide a link to it for the user to run this notebook with. I did see the link to the general compas website to download data, but as a new user  (and not knowing what the notebook expects) I wouldn't know what to chose to ensure proper running. 

**Note**
@ilyamandel @jeffriley, If i encounter other issues in the jupyter notebooks/tutorials would you like me to collate them in this issue or make new ones for each?

### LINKED ISSUE #686: Clean documentation in docs/
There is some documentation in docs (rather than docs/online-docs) that is outdated and no longer needed. For example, https://github.com/TeamCOMPAS/COMPAS/blob/dev/docs/getting_started.md is out of date (see, e.g., reference to non-existing .pdf file in the final paragraph).  Rather than updating it, and always remembering that we have two versions to update, we should check that it's not referenced elsewhere and delete it.

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Several big-ish related changes in this PR
- Clean up of post-processing notebooks and general postProcessing directory
- Addition of new useful python scripts for data analysis, including printCompasDetails and getEventHistoryString
- All post-processing python files are now in one folder for easy retrieval
- Updated the references to the notebooks in the online-docs
- Added line to the online-docs Makefile to copy over the post-processing notebooks before compiling website (so we don't have multiple copies of the notebooks floating around)
- Added the remaining markdown files (docker.md, sampling.md, dev-git-workflow.md) in the docs/ folder into the website
- Moved online-docs/, requirements.txt, and media/ out of docs/ and into the root dir, and deleted docs/ folder

### CODE REVIEW

**Review by jeffriley — COMMENTED** [review]
Couple of first things:

I get these warning when I compile the html:

/d/DocsTest/online-docs/notebooks/CosmicIntegration.ipynb:13: WARNING: File not found: 'notebooks/WorkingWithHDF5.py'
/d/DocsTest/online-docs/notebooks/CosmicIntegration.ipynb:722: WARNING: image file not readable: notebooks/media/SFRplot.png
/d/DocsTest/online-docs/notebooks/CosmicIntegration.ipynb:722: WARNING: image file not readable: notebooks/media/SFRplot.png
/d/DocsTest/online-docs/notebooks/DataAnalysis.ipynb:280: WARNING: Title level inconsistent:

printCompasDetails
~~~~~~~~~~~~~~~~~~
/d/DocsTest/online-docs/notebooks/DataAnalysis.ipynb:3472: WARNING: Title level inconsistent:

getEventHistory
~~~~~~~~~~~~~~~
/d/DocsTest/online-docs/notebooks/DataAnalysis.ipynb:5851: WARNING: Title level inconsistent:

Example 2
~~~~~~~~~
/d/DocsTest/online-docs/notebooks/DataAnalysis.ipynb:115: WARNING: File not found: 'notebooks/WorkingWithHDF5.py'
/d/DocsTest/online-docs/notebooks/Overview.ipynb:10: WARNING: image file not readable: notebooks/media/COMPASlogo.png
/d/DocsTest/online-docs/notebooks/Overview.ipynb:10: WARNING: image file not readable: notebooks/media/COMPASlogo.png
/d/DocsTest/online-docs/notebooks/WorkingWithHDF5.ipynb:3491: WARNING: Bullet list ends without a blank line; unexpected unindent.
/d/DocsTest/online-docs/notebooks/WorkingWithHDF5.ipynb:3494: WARNING: Bullet list ends without a blank line; unexpected


There also seem to be some broken links when navigating through the HDF5 pages using the "NEXT" button.  

Just a first brief look - more tomorrow.

**Review by jeffriley — COMMENTED** [review]
Just a couple more comments (more later):

"Git Workflow for COMPAS software developers" should be in the developer guide - it's not required to get started using COMPAS, so I don't think it belongs in "Getting started".  Maybe we need a "getting started"-like section in the developer guide.

I would also break the page into smaller pages i.e. put the content for each(?) of the sections into separate .rst files, and put them in a toctree rather than have readers scroll over what amounts to many pages.

**Review by jeffriley — COMMENTED** [review]
If we're going to document stroopwafel here, and consider it part of the COMPAS suite, when are we bringing the stroopwafel code into the COMPAS repo (were you working on that @ilyamandel )?

**Comment by reinhold-willcox** [comment]
Thanks @jeffriley for the feedback.

Regarding the warnings, I'm not sure of the best way to deal with this for the website. The online-docs/ folder in theory is supposed to contain all the material that needs to be compiled for the website, but some of the files (e.g notebooks and image files) really belong outside of the online-docs/ folder. My script to copy them in before compiling is a hacky workaround, but I'm very open to alternatives. What do you think?

The git workflow I just threw in without comparing it to the other git sections, so there's certainly room for improvement. It has good information for both users and developers, but I agree we can/should split those off into separate files for the two groups. 

For stroopwafel, perhaps you are right we should hold off until we have found a way to incorporate sw into compas. It's easy enough to leave the rst file there, but not reference it until later. However, it seems to me that the JOSS review provides a good excuse to bring in the SW functionality, and get it up to the COMAS standard. I'm not sure what the status is of SW at the moment, I had thought they were nearly ready to showcase it a few months ago, but I haven't heard anything since. 

Generally, it would probably be good for many of us to have a chat about how to layout the website, including breaking long pages into several shorter ones. I personally find the current layout to have too many very short files, so that it's a bit hard to navigate, but I'm sure we can find a solution that works for everyone.

**Comment by jeffriley** [comment]
> The online-docs/ folder in theory is supposed to contain all the material that needs to be compiled for the website, 
> but some of the files (e.g notebooks and image files)

You can reference them just with a relative path can't you?  I think readthedocs will access anything in the docs directory - not sure it will copy anything outside the docs directory.  But whether readthedocs will copy it or not, readthedocs isn't involved yet - I was just compiling the html files locally, so "file not found" means the reference (path) is wrong, or the file doesn't exist, doesn't it?

And, should this:

'notebooks/WorkingWithHDF5.py'

be a .py file or a notebook (.ipynb)?  I just assumed it should have been a notebook, but after reading your response maybe it really is supposed to be a python file.

> For stroopwafel, perhaps you are right we should hold off until we have found a way to incorporate sw into compas. 

I think stroopwafel is a good idea, but if we start putting it in our documentation, someone is going to open an issue against it - and if we don't have the code in our repo there's not much we can do.  Either bring stroopwafel  in, or create stroopwafel readthedocs documentation and we just point to that - stroopwafel is either in or it's not (in terms of being the responsibility of the COMPAS development group).  I'd love it to be in - I think it's a useful tool for the COMPAS suite.

> how to layout the website, including breaking long pages into several shorter ones

Yeah.  I don't think we should have lots of short pages, but if we have a few really long pages we might just as well post a pdf file with the documentation and let readers scroll through that.  There's a balance somewhere.  I'm having lunch this weekend with a UX consultant - I'll see what he says and if there are any guidelines we can look at.

**Comment by ilyamandel** [comment]
Thank you very much for all of this work, @reinhold-willcox !  I am still a bit confused regarding what python scripts and notebooks we are undertaking to test and maintain.  I thought we were planning to restructure the code to distinguish the core scripts which we stand behind and the scripts which we are providing on an as-available basis, with all notebooks falling into the latter category.  Is my understanding accurate?  
On Stroopwafel, I suggest we point to the Stroopwafel library.  If I understand correctly, the reason that Stroopwafel developers want it to sit separately is that they want it to be a tool for a range of pop synth codes, not just COMPAS.  I think it's fine to provide the documentation for how to interface COMPAS with Stroopwafel by stating that this is accurate for a particular version of the Stroopwafel library.
Otherwise, I am happy with these commits once any remaining issues pointed out by @jeffriley are addressed.

**Comment by jeffriley** [comment]
I spoke to a UX consultant over the weekend.  He'll try to find some useful documentation/guidelines and send me a link.  He doesn't have direct experience with documentation, but his opinion was that most webpages should be a couple of screens of content at the most - more than that and you should consider breaking it into smaller pieces.  There are always exceptions of course, but the general rule is that for web content, one or two pages of content is about as big as you should go - if there are lots of diagrams/graphs/photos etc., maybe it could be longer, but for mainly text, a couple of pages at most.

I think getting a few interested people together to discuss and set general guidelines for the documentation is a good idea - otherwise as different people update the documentation we risk having a(n online) document that is not consistent or coherent.  As always, I'm perfectly happy for the style/convention we settle on to be different from the one I used when I created the documentation - I just think we should settle on a single style/convention (or set of conventions that support the style), and stick to that (it almost doesn't matter what it is as long as we stick to it).

**Comment by reinhold-willcox** [comment]
@ilyamandel I may also be confused, I had thought the notebooks were to be maintained (alongside some of the standalone postprocessing scripts), and it was the methods paper plotting routines that were "as available". I have spoken to Avi about ways to test that the notebooks at least _compile_ which just means the parameter names haven't changed - and I've tried to write the notebooks in such fashion that the output isn't directly referenced unless the input was from the included COMPAS_Tutorial_Output.h5 file. 

Regarding the points you and @jeffriley brought up re: the web-docs, I agree that a simple reference to SW should suffice (along with a link to their github). Setting up the UI to be user-friendly is definitely a priority, and specifically a priority for the Joss review, but I think it might be useful to address those in a separate PR, so that these changes can be merged in. I still have a few more changes I want to make here first (updating the eventHistoryString script, fixing references Jeff mentioned above, adding the notebooks to a CI pipeline, etc.), but I'm happy to do those independently of a clean up of the web docs. Does that suit?

**Comment by ilyamandel** [comment]
@reinhold-willcox -- sorry for the slow response, and for creating merge conflicts by merging @jeffriley 's latest change out of turn.  

My vision of what we could do was described in https://github.com/openjournals/joss-reviews/issues/3838#issuecomment-967787717 .  In particular, see " I would be quite happy writing in big red letters that the only processing files we are providing as part of the core COMPAS distribution and take full responsibility for are h5copy.py, selection_effects.py, and FastCosmicIntegration.py. Everything else (including pythonSubmit.py) are just examples that the user may find helpful, but if not, they are not necessary for single or binary evolution or for processing the results."

In any case, I am fine with doing things a step at a time, so happy to accept the PR once the changes are merged in.

**Comment by reinhold-willcox** [comment]
@ilyamandel Latest merge should fix conflicts, but I haven't addressed all the TODOs above.

**Comment by ilyamandel** [comment]
Huge PRs become difficult to check and merge, so I am happy to accept and merge this one.  Can you create an issue listing what you see as the remaining to-do items, @reinhold-willcox ?

**Review by ilyamandel — APPROVED** [review]

**Comment by jeffriley** [comment]
@reinhold-willcox @ilyamandel The online documentation doesn't compile after merging this PR.

To see the errors, logon to the readthedocs COMPAS project page - see https://compashq.slack.com/archives/CMCUK1G69/p1635754297004900

**Comment by reinhold-willcox** [comment]
One of the todos was to make a CI check that the online docs compile, haha! I'll do that one today and fix these issues, then resubmit the pr

**Comment by jeffriley** [comment]
They don't compile automatically (upon change to the source) at the moment - that's because of the permissions thing we talked about.  Maybe while you're adding the CI check you can look at the permissions problem and fix that?  (I don't think I have the right permissions to the COMPAS github account to do that anyway).  I think the readthedocs user has to have permissions to set up the webhooks to notify readthedocs that there was a change to the files on github (but I'm not sure - everything worked without any configuration changes when I tested it with a github repo that I owned...).

Also, I think the problem with the compile at the moment is that you moved the requirements file to the root directory.  The readthedocs documentation says it expects to find the requirements file in the root directory (or what they call the 'top-level' directory I think - I assume that's the root directory, but maybe they have a different thing in mind), or in the 'docs' directory.  The COMPAS readthedocs project points to the docs directory of the COMPAS github page - I wonder if that needs to change if the requirements file is moved to the root directory?  I have no idea - I am a readthedocs novice.

**Pull request merged**
