### PR TITLE
Fix typo in changelog.h

### PR DESCRIPTION
**Pull request by jeffriley**

### CODE REVIEW

**Review by ilyamandel — APPROVED** [review]
Looks good!

**Comment by avivajpeyi** [comment]
Looks like 
```
py_tests/test_plot_detailed_evolution.py
```
failed due to a latex issue? This is bizarre -- nothing was changed in the python code...

**Comment by jeffriley** [comment]
Odd.  Related to the docs build failure (which is now passing)?  Both seemed to involve latex.  Intermittent resource issue maybe?

**Comment by jeffriley** [comment]
@avivajpeyi Any ideas on this?  Maybe we just turn the pytests off until we figure out what's going on?

**Comment by avivajpeyi** [comment]
Hey jeff, sure we can turn the pytest off -- or maybe just the detailed-plotter (that's where the error is being raised).

I've opened a new issue regarding this error #989

**Comment by ilyamandel** [comment]
I am going to merge this in despite the nominal fail, since this clearly isn't the issue.

**Pull request merged**
