### PR TITLE
Option to specify '--muller-mandel-sigma-kick' for Natal kicks

### PR DESCRIPTION
**Pull request by veome22**
Added the option for users to specify the kick scatter (--muller-mandel-sigma-kick) when using the Mandel & Mueller 2020 natal kick distribution. Also updated the program option list in the online docs.

The default value for sigma is chosen to be 0.3 (unchanged from the previous default).

NOTE: There are still some doc pages that can be updated, such as the Running COMPAS from the command line doc which contains the output of `./compas --help`. Since these aren't critical to understanding the usage, they can be updated later.

### CODE REVIEW

**Review by jeffriley — COMMENTED** [review]
A couple of first comments - I haven't looked at the functionality of the code changes, but at first glance they look good.

1. changelog and version number need to be updated
2. The changes to the Makefile for:

GSLINCDIR := /opt/apps/intel19/gsl/2.6/include 
GSLLIBDIR := /opt/apps/intel19/gsl/2.6/lib 
BOOSTINCDIR := /opt/apps/intel19/python3_7/boost/1.72/include 
BOOSTLIBDIR := /opt/apps/intel19/python3_7/boost/1.72/lib 
HDF5INCDIR := /opt/apps/intel19/hdf5/1.10.4/x86_64/include 
HDF5LIBDIR := /opt/apps/intel19/hdf5/1.10.4/x86_64/lib 

are fairly specific, both with WRT location of the files and versions installed.  Are these directories specific to your system?  Note that those variables can be defined on the command line when you run make if your installation doesn't match the generic Makefile.

**Review by jeffriley — CHANGES_REQUESTED** [review]
The build failed - possibly because the dependencies are not installed where the Makefile expects.

**Comment by veome22** [comment]
Hi, sorry about the Makefile-- I had mine set up for my HPC. It should be fixed now!

I also updated the changelog with my best interpretation of the recommended syntax. Please let me know if I should make any other changes to the pull request.

**Review by jeffriley — APPROVED** [review]
Approved.

**Pull request merged**
