### PR TITLE
Winds patch 2

### PR DESCRIPTION
**Pull request by jmerritt1**
-Changed the logic applying RSG winds to include a stellar type check for HG or `GIANTS`, preventing GB winds from being applied to high-mass(20-40), high-Z HG stars in the RSG parameter space. This issue came up in the fix for WR winds being applied during CHeB [(Issue 502)](https://github.com/TeamCOMPAS/COMPAS/issues/502).

-Changed all FLEXIBLE2023 wind prescription naming to MERRITT2024, as suggested in Ilya's comment on the paper draft. 

-Will need to generate a new default .yaml, and change examples.

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
Changes look ok, thanks JD.

As you noted, you'll need to create a new default yaml file (use `./compas --create-yaml-file filename.yaml`, and move `filename.yaml` into the appropriate directory to replace the default yaml file).  You'll also need to merge dev and resolve any conflicts.

Interestingly, the online documentation for `--mass-loss-prescription` does not mention `BELCZYNSKI2010` or `FLEXIBLE2023` (now replaced by `MERRITT2024`).  That needs to be updated (in file `program-options-list-defaults.rst`) - I'm surprised we let that through last time...

Ordinarily I'd be concerned about changing option values that people might have in configuration files etc., especially the default value, but since it was never documented maybe it is ok to just change it here and hope it doesn't break anyone's configuration files.  You might want to add a `What's New` entry to announce that `FLEXIBLE2023` has changed to `MERRITT2024` (even though it wasn't changed in the documentation for `--mass-loss-prescription`).

EDIT: I forgot to add that I'm not completely happy with this construct:

    (IsOneOf(GIANTS) || m_StellarType == STELLAR_TYPE::HERTZSPRUNG_GAP))

(because I don't like code that picks out a specific stellar type - if we can avoid that we should) but it's ok for now - one day when I get time I might try to rationalise the initialiser lists (and hopefully create a list that covers this circumstance).

**Review by ilyamandel — COMMENTED** [review]
In the documentation, NONE vs ZERO:

Options: { ZERO, HURLEY, BELCZYNSKI2010, MERRITT2024 } |br|
``NONE``          : No wind mass loss |br|

**Review by ilyamandel — COMMENTED** [review]
From changelog:

"// - Related to issue #502: added HG to allowed RSG stellar type check, preventing GB winds from being applied during HG."

Aren't you now *allowing* GB winds to be applied during HG?

**Comment by jmerritt1** [comment]
> From changelog:
> 
> "// - Related to issue #502: added HG to allowed RSG stellar type check, preventing GB winds from being applied during HG."
> 
> Aren't you now _allowing_ GB winds to be applied during HG?

We are allowing RSG winds to be applied, where appropriate, rather than the older GB (which, depending on the stellar type may take the greatest of NJ, VW, KR, WR winds).

**Review by jeffriley — CHANGES_REQUESTED** [review]
Changes look good thanks JD.  Just one thing: you pushed your Makefile - you need to remove it.

**Review by jeffriley — APPROVED** [review]
All good :-)

**Comment by ilyamandel** [comment]
> In the documentation, NONE vs ZERO:
> 
> Options: { ZERO, HURLEY, BELCZYNSKI2010, MERRITT2024 } |br| `NONE` : No wind mass loss |br|

@jeffriley , @jmerritt1 -- this request seems to have been missed; just mentioning it here so I don't forget to add it in another PR.

**Pull request merged**
