### PR TITLE
Multiple updates: 2-stage CE, winds, mass transfer timescale recording, bug fixes

### PR DESCRIPTION
**Pull request by ilyamandel**
- Continue evolution on merger at birth (stars touching) if --resolve-main-sequence-merger
- Change behavior of Sabhahit+ 2023 VMS winds to default to current OB wind prescription if Gamma threshold is not met
- Add recording of MASS_TRANSFER_TIMESCALE (NONE, NUCLEAR, THERMAL, CE), resolving issue #1217 
- Correct (re-)setting of MassLossRateInRLOF, resolving issue #1225 
- Correct behaviour of the second stage of 2-stage CE to first transfer mass from the star that initiated RLOF (see #1215 )
- Correct behaviour of the second stage of 2-stage CE to ensure that the accretor's mass is correctly adjusted
- Correct code comments, update documentation where it fell behind

### CODE REVIEW

**Comment by SimonStevenson** [comment]
Thanks Ilya, the changes look good. I'm running a quick population test to see if this makes any difference to #1215 . Will comment again and sign off once that's done.

**Comment by ilyamandel** [comment]
Thank you, @SimonStevenson !
Sorry for adding one more change while you were testing -- I figured I'd just stick a few things I meant to do into the same PR while it looked like nobody was looking, only noticed now that you started a test.
I promise, no more additions -- done for the day. :)

**Comment by ilyamandel** [comment]
Note: I am not promising this will completely fix #1215 or #1180 , but it does implement some changes that needed to be made anyway, were discussed as part of those issues, and may help to address them.  It does address #1213 , #1217 , #1225, as well as some of the wind discussions that never made it as official issues and a bit of other cleanup in the documentation and elsewhere.

**Comment by SimonStevenson** [comment]
All good, will pull these in and restart the test (hadn't been going long)

**Comment by SimonStevenson** [comment]
Here is the result of the test (merging BBH yield as a function of metallicity):
two_stage_CE_yields

No real change, still a large peak at low metallicity.

**Review by SimonStevenson — APPROVED** [review]
Changes look good to me. Test ran fine.

**Comment by jeffriley** [comment]
@SimonStevenson can you send me the commandline, or the yaml file, you used to produce the plot above?

**Comment by SimonStevenson** [comment]
@jeffriley 

```
./COMPAS -n 100000 --metallicity-distribution LOGUNIFORM --common-envelope-formalism ENERGY --initial-mass-min 10.0 --output-container DEFAULT > default.out &
./COMPAS -n 100000 --metallicity-distribution LOGUNIFORM --common-envelope-formalism TWO_STAGE --initial-mass-min 10.0 --output-container CHECK2CE > check2CEchanges.out &
```

**Review by jeffriley — APPROVED** [review]
Looks good - thanks @ilyamandel

**Comment by ilyamandel** [comment]
Thank you for the additional plot, @SimonStevenson .   Definitely more work required to understand this behaviour.

**Pull request merged**
