### PR TITLE
Small update thermal timescale

### LINKED ISSUE #570: change pre-factor in thermal (kelvin-helmholtz) timescale calculation
**Is your feature request related to a problem? Please describe.**
The function `CalculateThermalTimescale` uses a pre-factor of GMsun^2 / Rsun Lsun = 30.0 Myr, but when you calculate this it should actually be 31.4 Myr (see attachment) so why not update this? I also updated the documentation

**Describe the solution you'd like**
I am changing the 30.0 to 31.4 Myr. Since both numbers have the same precision , and hence the same computational cost, I do not see a (big) problem. 

Screen Shot 2021-05-24 at 10 43 29 AM

### PR DESCRIPTION
**Pull request by FloorBroekgaarden**
closes #570 

I updated the pre-factor and added documentation. I updated the log file accordingly

### CODE REVIEW

**Comment by ilyamandel** [comment]
While looking at this, I started wondering if HeHG.h correctly overwrites the "no-envelope" behaviour of HeMS.h for CalculateThermalTimescale(const double p_Mass,
                                                      const double p_Radius,
                                                      const double p_Luminosity).  
@jeffriley , would you mind taking a quick look?

**Comment by jeffriley** [comment]
HeHG inherits CalculateThermalTimescale() from HeMS.  HeMS::CalculateThermalTimescale() calls MainSequence::CalculateThermalTimescale() which ignores the p_EnvMass parameter.

So, I think from your question, HeHG should implement it's own version of CalculateThermalTimescale(), calling GiantBranch::CalculateThermalTimescale() which does not ignore the p_EnvMass parameter?

HeGB inherits from HeHG (so currently ignores p_EnvMass) - so if we change HeHG we'll need to decide what to do with HeGB

**Comment by FloorBroekgaarden** [comment]
good point @jeffriley @ilyamandel , it actually also made me wonder whether the MainSequence::CalculateThermalTimescale() needs to pass the variable p_EnvMass? It currently does, but there's no need to? Or is it preferred to keep them the same?

**Comment by jeffriley** [comment]
> it actually also made me wonder whether the MainSequence::CalculateThermalTimescale() needs to pass the variable p_EnvMass?
> It currently does, but there's no need to? Or is it preferred to keep them the same?

The signature needs to be the same for inheritance - I think that's why I did it that way

**Comment by jeffriley** [comment]
(And because p_EnvMass has a default value in MainSequence.h, callers don't need to pass the value - it's just there to satisfy the signature requirement)

**Comment by ilyamandel** [comment]
Cleaner alternative: since each star knows whether it has an envelope (whether m_Mass == m_CoreMass), why not just have a single function in the base class that will use m_Mass if m_Mass == m_CoreMass, and  the envelope mass, m_Mass - m_CoreMass, otherwise?  That way, we won't need multiple overrides in the inheritance tree.

**Comment by jeffriley** [comment]
@FloorBroekgaarden  Is this still a WIP?  Should we mark it as a draft?

**Comment by FloorBroekgaarden** [comment]
I'm not sure what we decided? My part (changing the pre factor) is good to go. But @ilyamandel do we want to then implement your suggestion?

**Comment by jeffriley** [comment]
@ilyamandel I was just looking at implementing your suggestion, but noticed that Remnants.h has CalculateThermalTimescale() call CalculateDynamicalTimescale(), which ultimately calls BaseStar::CalculateDynamicalTimescale_Static().

So, just to be sure, implement your suggestion for everything except remnants, and leave the override in Remnants.h?

**Comment by ilyamandel** [comment]
Hi @jeffriley , @FloorBroekgaarden -- sorry for the silence.  Yes to @jeffriley 's last suggestion.  @jeffriley , I leave it to you whether it's easier to accept this change first or implement the more general one we discussed above. :)

**Comment by jeffriley** [comment]
Ok, I'll take a look.  What makes this a little more problematic is the docs - we need to update the online docs, but we don't yet have them in the COMPAS repo.  I can do that separately.  I'll look at how to get all this done with minimum fuss :-)

**Comment by ilyamandel** [comment]
Ping for @jeffriley  :)

**Comment by jeffriley** [comment]
That was 2 weeks ago?  Time files...  Ok, I will get to this - promise

**Comment by jeffriley** [comment]
Closed in favour of PR #646

**Pull request closed without merging**
