### PR TITLE
Added a check of neutron star mass against maximum neutron star mass 

### PR DESCRIPTION
**Pull request by SimonStevenson**
Added a check of neutron star mass against maximum neutron star mass to ShouldEvolveOnPhase in NS.h

This should resolve Issue #513

### CODE REVIEW

**Review by jeffriley — COMMENTED** [review]
Looks good.  Happy to approve once changelog.h and version string are updated.

**Comment by SimonStevenson** [comment]
Thanks Jeff! Version updated now.

**Review by jeffriley — APPROVED** [review]
All good

**Comment by ilyamandel** [comment]
@SimonStevenson -- I am not convinced by this line:

m_Mass = BH::CalculateNeutrinoMassLoss_Static(m_Mass); 

Does an accretion induced collapse of an NS into a BH involve significant mass loss in neutrinos (at the same level as normal core collapse)?  I wouldn't have thought so, but I don't know the answer...  Will ask Bernhard for his thoughts.

**Comment by ilyamandel** [comment]
Following up, here's a response from Bernhard.  The summary is that mass accretion efficiency for nearly-maximal-mass NS may be reduced (separate story from this -- it's about how we handle accretion), but that there is no appreciable neutrino mass loss during the collapse from NS to BH.  I'll put together a new PR to make this change.

"this should be easier to answer than in the case of BH formation inside a CCSN.
In the CCSN problem, the key issue is that the diffusion time scale of the PNS interior is longer
than the accretion time scale. In this case, you shouldn't have that problem. You have steady state
accretion up to the point of instability, and then the NS will collapse on a dynamical time scale, too fast
for neutrinos to do anything.

But you still get to answers, depending on whether you consider the BH mass of the total system mass.
The collapsing NS must have a mass somewhat *above* the maximum mass limit for non-rotating
NSs (depending on the degree of differential rotation). No matter what happened before, you must have got to the stability limit.

The total system mass should have decreased by O(1/2 GM/R \Delta M)  because the accreted stuff has to get rid
of its energy some way. However, if the NS is close to mass shedding, the efficiency will go down considerably.
Anyway, if you don't accrete too much, the change in mass of the total system shouldn't be overwhelming in the first place."

**Comment by SimonStevenson** [comment]
Cool, I honestly wasn't sure about that so thanks for checking!

**Pull request merged**
