### PR TITLE
Fix MassTransferTrackerHistory

### PR DESCRIPTION
**Pull request by ilyamandel**
Remove unnecessary IsPrimary() / BecomePrimary() functionality

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
@ilyamandel there are some other files included in this PR related to cosmic integration and getting_started.md. Were those meant to be included?

**Comment by ilyamandel** [comment]
Thanks, @reinhold-willcox -- apparently, I inadvertently copied some things from my another working branch, will fix in a second.

**Comment by ilyamandel** [comment]
OK, all cleaned, ready for review.

**Review by jeffriley — APPROVED** [review]
Approved

**Pull request merged**
