### PR TITLE
added orbit inclination angle to SN output

### PR DESCRIPTION
**Pull request by reinhold-willcox**

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
Documentation?

**Comment by jeffriley** [comment]
Oh, and changelog...

**Comment by jeffriley** [comment]
And just a question - does it need to be in the default record?  Can you just make it available, and users that need it can add it via the logfile definitions file at run time?  Just so we don't continue to bloat the default output files.  No problem if you think it would be useful as a default - just asking the question.

**Comment by reinhold-willcox** [comment]
It's a pretty useful output option, I would propose advocate including it by default. 

Docs and changelog updated.

**Review by jeffriley — APPROVED** [review]
All good

**Pull request merged**
