### PR TITLE
Change default LBV wind prescription 💨 

### PR DESCRIPTION
**Pull request by TomWagg**
@demink asked me to make this PR to change the default LBV wind prescription to HURLEY_ADD instead of BELCZYNSKI based on the discussion in the methods paper meeting. I *think* I changed it everywhere but hopefully the ever wise and knowledgeable @jeffriley can set me straight if not 😁 

If it's helpful, I changed it:

- in pythonSubmit.py
- in baseStar.cpp if an unknown prescription is given
- in options.cpp
- in the LaTeX file

### CODE REVIEW

**Review by ilyamandel — COMMENTED** [review]
Looks good to me, but will leave this for @jeffriley to approve.

**Comment by jeffriley** [comment]
Happy to approve, but @ilyamandel this reminds me that we have another level of defaults in the code.  Note in BaseStar.cpp the default case for the switch specifies a default LBV prescription.  This is purely defensive programming - the switch needs a default case.  When I ported the legacy code I chose to make the default case the default LBV prescription - one alternative would be to show a warning and abandon processing of the binary.  The point is, the way the code is at the moment, here and in other places, switch statement default cases may be hard-coded to use a particular, default, option value.  The question arising is whether we should endeavour to keep those in sync with the defaults in Options.cpp and pythonSubmitDefault?

**Comment by jeffriley** [comment]
@ilyamandel Also note this bumps the version number to v02.19.03 - a magic number wrt the methods paper...

**Review by jeffriley — APPROVED** [review]
Thanks @TomWagg!  Good job - and yes, I think you changed it everywhere it should be changed :-)

**Comment by ilyamandel** [comment]
@jeffriley -- well, we'll leave the methods paper number until we have pulled defaults over from pythonSubmit into Options.cpp :)

**Comment by ilyamandel** [comment]
@jeffriley -- Yes, I noticed the change in the fallback option, too.  Since this should never be encountered in practice (as you say, it's just defensive programming), I don't think it really matters what we put there.  That said, I agree that an error + abandoning the binary would not be terrible (the user should probably know that the code didn't go down the expected path).

**Pull request merged**
