### PR TITLE
Fixing "black hole mass loss" issue

### LINKED ISSUE #884: BHs are losing mass
**Describe the bug**
BHs appear to be losing mass following the Vink(?) prescription. This was discovered by Andreas Konstantinou. The m_Mdot parameter appears to have related, anomalous behavior. 

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**

```
COMPAS --random-seed 1 --number-of-systems 10000 --metallicity 0.0142 --kick-magnitude-distribution MULLERMANDEL --remnant-mass-prescription  MULLERMANDEL --muller-mandel-kick-multiplier-NS 520 --logfile-definitions COMPAS_Output_Definitions.txt
```

Together with the following `COMPAS_Output_Definitions.txt`
```
BSE_RLOF_Rec += { BINARY_PROPERTY::SYSTEMIC_SPEED, 
    STAR_1_PROPERTY::LUMINOSITY,
    STAR_2_PROPERTY::LUMINOSITY,
    STAR_1_PROPERTY::TEMPERATURE,
    STAR_2_PROPERTY::TEMPERATURE,
    STAR_1_PROPERTY::ANGULAR_MOMENTUM,
    STAR_2_PROPERTY::ANGULAR_MOMENTUM,
    STAR_1_PROPERTY::DYNAMICAL_TIMESCALE,
    STAR_2_PROPERTY::DYNAMICAL_TIMESCALE,
    STAR_1_PROPERTY::THERMAL_TIMESCALE,
    STAR_2_PROPERTY::THERMAL_TIMESCALE,
    STAR_1_PROPERTY::NUCLEAR_TIMESCALE,
    STAR_2_PROPERTY::NUCLEAR_TIMESCALE,
    STAR_1_PROPERTY::MDOT,
    STAR_2_PROPERTY::MDOT,
    STAR_1_PROPERTY::MASS_TRANSFER_DIFF,
    STAR_2_PROPERTY::MASS_TRANSFER_DIFF}
```

Then mask for accreting BHs. 

**Expected behavior**
BHs should not lose mass, and m_Mdot should accurately reflect the mass loss in a given timestep. 

**Screenshots**
image

**Versioning (please complete the following information):**
 - COMPAS v02.34.03

### PR DESCRIPTION
**Pull request by ilyamandel**
This fixes #884 .

Black holes are not losing mass and their Mdot is correctly reported as zero.

Fixes:

We did incorrectly report Mdot for single stars, because of the line void ResolveMassLoss() { } // NO-OP in Remnants.h, which meant we never called ResolveMassLoss for these, so Mdot was not being reset correctly, and just held onto its last value.  

For binaries, meanwhile, the problem was with BaseBinaryStar::CalculateWindsMassLoss(), where we stopped winds for binaries in mass transfer — but never updated Mdot.

Along with fixing these issues, I fixed a few other things, like the incorrect application of Dutch winds to remnants, a typo in the calculation of NS luminosities, and a bit of light cleaning.

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
@jeffriley This looks good to me, but the new function `SetMdot()` looks like it might not align with your preferred OOP style, so I'm deferring to you.

**Comment by jeffriley** [comment]
You're right @reinhold-willcox, I don't like it (as evidenced by the comments @ilyamandel removed for the calls to SetMassLossDiff().  I meant to find a better way  than expose setters, but I haven't got to it yet (I think we should have something somewhere that reminds us to revisit that).

@ilyamandel Rather than doing the following in BaseBinaryStar::CalculateWindsMassLoss():

    m_Star1->SetMassLossDiff(0.0);
    m_Star2->SetMassLossDiff(0.0);
    m_Star1->SetMdot(0.0);
    m_Star2->SetMdot(0.0);

what about a new virtual function in BaseStar something like:

    void BaseStar::HaltWinds() {
        m_MassLossDiff = 0.0;
        m_Mdot = 0.0;
    }

That would still leave a couple of calls to SetMassLossDiff(), but maybe we can resolve those later.

(But if you must leave SetMdot() in, can you change it to 'void SetMdot(const double p_Mdot)'?

**Comment by ilyamandel** [comment]
@jeffriley -- OK, happy to hide the setter this way. :)

Partial change made:  m_MassLossDiff is a variable of BinaryConstituentStar, while m_Mdot is a variable of BaseStar, so I kept the former to be set via  SetMassLossDiff() but replaced SetMdot() with HaltWinds() for the latter.  I also 
added a comment “// JR would prefer to avoid a Setter for aesthetic reasons” :wink:

Finally, replaced LOG10_ZSOL with pre-computed value to avoid compilation issues.  

Tested, ready for your repeat review.

**Review by reinhold-willcox — APPROVED** [review]
Looks good, thanks Ilya

**Pull request merged**
