### PR TITLE
ONeWD fix

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Addresses issue #773

I confirmed @solfreludio 's fix does allow for the formation of ONeWDs again.

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
Should fix https://github.com/TeamCOMPAS/COMPAS/pull/777 (update changelog and version number) before merging this

**Review by jeffriley — CHANGES_REQUESTED** [review]
Change is good, but version number needs updating after PR#779 was merged

**Comment by reinhold-willcox** [comment]
@jeffriley version number is now updated

**Review by jeffriley — APPROVED** [review]
All good

**Pull request merged**
