### PR TITLE
Add binned integrator (with GPU support)

### PR DESCRIPTION
**Pull request by avivajpeyi**
As discussed in #968, #972, this adds a modified version of the cosmic-integrator (that can run on GPU/CPU), which bins the chirp-mass and redshift data while computing the detection-rate matrix (this will thereby avoid the multiple large arrays of [n_binary, redshift].

This also adds a test of the binned-cosmic integrator to ensure that it produces the same output if data is binned before/after running the cosmic integrator.

Finally, this adds some additional plotting code that can be used as diagnostics (the detection-rate plot, plot of the SNR sensitivity grid, and a plot of the SFR/metallicity distributions).  

## Visual test
Below I visually compare the binned integration outputs 
1. Binning after fast cosmic integration
binned_detection_matrix_plot
2. 'binned' cosmic integrator
binned_detection_matrix_plot_v2

The pytest also checks the values in the two grids are close w/ tol 1e-5

## Requirements
- Requires #971 to be merged in
- Requires @jeffriley 's binned-integrator to be merged in

Apologies for the miscommunication, @jeffriley, and @ilyamandel! I was unaware you were still working on adding your version of the cpp `FastCosmicIntegrator` in!

### CODE REVIEW

**Comment by jeffriley** [comment]
@avivajpeyi @ilyamandel I just pushed my latest code for FastCosmicIntegration.py (I hope that's all I pushed...).

It is a monolithic file - it contains several classes.  We can separate them if required. I don't think this will merge with @avivajpeyi 's code easily.  I'm happy for you to use any, all, or none of my code.  It is documented - there is an explanation at the top of the file.

I have done some rudimentary tests and it seems to work as expected, but one of the many things I am not very good at is testing my own code, so it is very likely I have tested only the happy path...  Some further testing would be useful should you decide to use the code.

Let me know if you have any questions.

EDIT: @ilyamandel This code will produce the per-binary files according to your "Binary mergers: a common format" document, but it doesn't produce the yaml file.  I don't think this is the right vehicle for that.  I suspect it may just be better to let the user have COMPAS create a project-specific yaml file, and  then modify that to suit, but we can talk about that.

**Comment by avivajpeyi** [comment]
This is awesome! I haven't been through the entire file -- but making my way through it. I think it would be great if we can add some tests for your code (I've managed to use set up some basic unit tests for my version of the comic integrator), and I think we can merge these (will require some work). Maybe we can meet up on a call to discuss how to proceed. Ill be back in the office next week.

**Comment by avivajpeyi** [comment]
This is awesome! I haven't been through the entire file -- but making my way through it. I think it would be great if we can add some tests for your code (I've managed to use set up some basic unit tests for my version of the comic integrator), and I think we can merge these (will require some work). Maybe we can meet up on a call to discuss how to proceed. Ill be back in the office next week.

**Review by ilyamandel — APPROVED** [review]
For what it's worth, I am happy with the approach of having *both* a modified fast_cosmic_integrator as @TomWagg and @avivajpeyi have done (with a revised normalisation calculation, etc.) and @jeffriley's new binned_cosmic_integrator.  They provide a natural check on each other, have slightly different use cases, and appeal to users with different preferences.  Ultimately, we may deprecate one of them, but there's no obvious reason to merge them now.  So my approval refers to the entire PR.  

In fact, I'd be happy to pull this in now so people can start using these (which is the best way of testing them), and add further modifications/tests later, as separate PRs -- but will leave it to @jeffriley and @avivajpeyi to decide whether to press the "Pull" button. :)

**Comment by jeffriley** [comment]
I'm ok to have two versions.  I'm not sure of all the modifications @avivajpeyi and @TomWagg have made.  Users can turn binning on or off with my version, and turn the per-binary .csv file on or off, so as far as the 'standard' behaviour goes they should be the same.  @avivajpeyi added support for gpus which I think is a good thing to have - my version doesn't have that.

So, I'll leave it to @avivajpeyi whether and when to pull this in.

**Comment by avivajpeyi** [comment]
IMO i think we should return this to draft state and make some changes before merging this in.

#### 1. I think that having two versions of the same code will lead to confusion 😅 
The module I created `binned_cosmic_integrator` and Jeff's `FastCosmicIntegration.py` are doing mostly the same things.  Both have the ability to compute the detection matrix (with and without binning).  Both can store the rates to file. If we decide to merge this PR we should really try to do something about fixing this. 

#### 2. Deleting zombie-code

@jeffriley -- I noticed that both of us have some similar classes -- it seems like neither of us use `ClassCOMPAS` `ClassMSSFR`, etc. If that is the case, we should really delete these in this PR.

**Comment by jeffriley** [comment]
> I think that having two versions of the same code will lead to confusion 😅

I think that's a fair comment - and it means doubling-up on maintenance.  Maybe @ilyamandel can expand further on his reasons for suggesting we keep both versions (maybe my version imposes OO too much...?)?

> Both can store the rates to file. 

But differently.  My version will only store the per-binary merger rates, and yields to (separate) csv files, and in the format specified in @ilyamandel 's document.  I think your version will store the rates arrays as they are produced (i.e. binned or per-binary), but not in Ilya's format.  That's easily fixed though - as I mention in my documentation, providing a small script that uses my version to create the arrays and then write them to a file, to the HDF5 file (per Lieke's code), plotting functionality, etc., is not hard at all.

> Deleting zombie-code ... 
> neither of us use ClassCOMPAS ClassMSSFR, etc. If that is the case, we should really delete these in this PR.

I have no problem deleting those with one caveat: I only provide the functionality in my version that I need for FastCosmicIntegration.  I think Coen provided some other functionality in those classes, and I don't know if people use that functionality.  If they do, we shouldn't delete those files unless/until we determine if the functionality is really needed, and if it is we provide it elsewhere.

**Comment by ilyamandel** [comment]
Are ClassCOMPAS, etc.,  used in some of the Jupyter notebooks that are
provided as examples? (you can probably just do a search? not sure, since I
never use the notebooks)

**Comment by avivajpeyi** [comment]
Some more things that we should consider

#### 3. Moving Jeff's `FastCosmicIntegrator.py` into the `compas_python_utils`

If we merge this in as is, this will result in there existing 3 `cosmic-integration` codes:
- Jeff's new `FastCosmicIntegrator.py` located in the repo root, 
- my `binned_cosmic_integrator` module, and 
- the old `FastCosmicIntegrator.py`

Leaving Jeff's new `FastCosmicIntegrator.py` file outside the `compas-python-utils`  module will prevent users from importing it without hackily adding it to their path... 

If we move it in, we can also run the basic tests we already have for the previous `FastCosmicIntegrator`. 
`pytest  py_tests/test_fast_cosmic_integration.py`




#### 4. Updating Examples and documentation
If we are going to get rid of the old `FastCosmicIntegrator` code with Jeff's version, we need to update the documentation and examples accordingly.

**Comment by jeffriley** [comment]
> Are ClassCOMPAS, etc.,  used in some of the Jupyter notebooks that are provided as examples?
> (you can probably just do a search? not sure, since I never use the notebooks)

I think they are - I also never use notebooks.

**Comment by avivajpeyi** [comment]
The CosmicIntegration notebook doesnt really work atm 😅 I remember trying them out when I started working on this stuff in ~Oct. 

IDK about the others.

**Comment by jeffriley** [comment]
> Some more things that we should consider...

I'd be in favour of replacing the existing FastCosmicIntegration code with mine, except that as mine is, it doesn't provide all the functionality of the current FastCosmicIntegration code:

1. it can't be run from the command line
2. it doesn't provide plotting functionality
3. it doesn't provide Lieke's writing rates to HDF5 files
4. it doesn't write the rates arrays to file

All that is easily added, or provided as a wrapper script - but I won't have time to do it before I leave for Aspen

**Comment by ilyamandel** [comment]
So that seems like a good reason to keep both for now, and then perhaps
streamline things in the future?

**Comment by ilyamandel** [comment]
Consider moving the unnecessary classes into unsupported examples rather
than deleting them outright?

**Comment by jeffriley** [comment]
> So that seems like a good reason to keep both for now, and then perhaps streamline things in the future?

Well, yeah, but really, adding a script to do that would take maybe an hour...  If I get a spare hour between now and Wednesday I'll do it.

**Comment by jeffriley** [comment]
> Consider moving the unnecessary classes into unsupported examples rather than deleting them outright?

That's a good idea.  Just make sure we document what we do here so people know - maybe put an entry in "What's New"

**Comment by avivajpeyi** [comment]
> Consider moving the unnecessary classes into unsupported examples rather than deleting them outright?

I personally think keeping unsupported zombie code is confusing... 

Instead, it sounds like the examples just need to be updated and run as a part of the CI. Then whoever makes some changes in the code will be responsible for fixing the examples etc to ensure that their changes do not result in the CI failing. 

I can set this up for the cosmic-integration code in this PR.

**Comment by ilyamandel** [comment]
That sounds great!

**Comment by avivajpeyi** [comment]
Cool! I've just updated the CosmicIntegrator example. 

I'll add the CI test for this shortly.

**Comment by avivajpeyi** [comment]
Ok, I've updated the `CosmicIntegrator` example, and have set the CI to run the files in the `utils/examples` folder. 

I noticed that this file is not included in the online docs, but that maybe can wait for a future PR.

**Comment by avivajpeyi** [comment]
Hey @ilyamandel  and @jeffriley,  it sounds like we'll include both  `binned_cosmic_integrator` and replace the current `FastCosmicIntegrator` with Jeff's `FastCosmicIntegrator` (with optimistic intentions of `merging` these in the near future)

As we want to have Jeff's `FastCosmicIntegrator` replace the current `FastCosmicIntegrator`, it sounds like there is some work that still needs to be done with Jeff's code (involving deleting the current versions of the files that Jeff has re-written, and I think Jeff wants to add some extra stuff as mentioned above).  

To prevent further bloating in this PR, would it be ok if we handle adding Jeff's file in a new PR?

**Comment by jeffriley** [comment]
> To prevent further bloating in this PR, would it be ok if we handle adding Jeff's file in a new PR?

Ok by me.

**Comment by avivajpeyi** [comment]
@jeffriley I also updated the tutorial as discussed [(see this)](https://compas--979.org.readthedocs.build/en/979/notebooks/CosmicIntegration.html)

The `py_tests/test_examples.py` allows us to run the example (and other examples in `utils/examples/` as a unit test to ensure it works. 

This is ready to be merged in, depending on your review :)

**Review by jeffriley — CHANGES_REQUESTED** [review]
Ok, I'll get to this tomorrow probably.  This is just a placeholder.

**Review by jeffriley — APPROVED** [review]
I'm ok with this. One day we should probably rationalise the directory structure - e.g. the sampling (bootstrapping) module use cases aren't restricted to cosmic integration are they?  Yet the source file lives in a directory subordinate to the cosmic integration directory.  Perhaps it should be on the same level - CI & sampling are both tools and one doesn't depend on the other (does it? If it does it probably doesn't need to).

Thanks @avivajpeyi - good to go

**Pull request merged**
