### PR TITLE
Fix the workflow to work successfully on MacOS 12. This required chan…

### PR DESCRIPTION
**Pull request by emanehab99**
- Fix the workflow to work successfully on MacOS 12. This required chanding the dependencies and commenting plt.show() in the plotting script
- Use setup-python action to cache pip dependencies
- Use cache action to cache macos dependencies, which saved ~7mins of building time
- Restrict the paths that triggers the workflow to avoid unncessary runs not related to the workflow

### CODE REVIEW

**Review by ilyamandel — CHANGES_REQUESTED** [review]
@emanehab99 , I understand that commenting out plt.show() from plot_detailed_evolution.py may be good for automatic testing, but won't this make the script less useful for a typical user who actually wants to see the plots?

**Comment by emanehab99** [comment]
@ilyamandel I agree. Hence I suggested in my email to either use a separate copy of the script for CI/CD purposes (this needs to be maintained whenever the plotting script changes) or add comments in the script to clarify why this line is commented and it's safe to be uncommented

**Comment by ilyamandel** [comment]
@emanehab99 : Following discussion with @avivajpeyi , @jeffriley et al., we'll address this by having an optional noshow argument in the plotting script; CI will use that argument to avoid creating plots.

**Comment by ilyamandel** [comment]
@avivajpeyi -- now that PR #902 is in, can you please update this PR with the do not plot flag?

**Comment by avivajpeyi** [comment]
Hey Ilya -- will update this before the dev meeting tomorrow!

**Comment by avivajpeyi** [comment]
i _think_ the mac-os-12 container is known to be slow: https://github.com/actions/runner-images/issues/6147

This means while the CI will take ~ 1.5 min to install ubuntu CI dependencies, the CI can take > 15 min to install the mac dependencies (much better than the 1hr we noticed here https://github.com/TeamCOMPAS/COMPAS/pull/938, due to @emanehab99 's cool optimization hacks :D ) 

Maybe instead of running the mac-os checks as frequently as the ubuntu checks, we can instead do a weekly run or smth?

**Comment by avivajpeyi** [comment]
Manually canceled the macOs workflow after 1.5Hrs (offft)

**Comment by ilyamandel** [comment]
@avivajpeyi -- fine on turning off MacOS compilation for now.  But what about the detailed evolution plotter with the no plot option -- is that good?

**Comment by avivajpeyi** [comment]
yep the CI running on ubuntu runs the detailed plotter and saves the fig (not yet being deployed to the TeamCOMPAS.github.io, but downloadable) 

Turning off MacOS compilation --  cool -- in that case shall we just close this PR? I think the main thing this PR is adding is MacOS build.

**Comment by ilyamandel** [comment]
Well, let's ask  @emanehab99: is there a way to get around this taking more than 1.5 hours for MacOS?

**Comment by avivajpeyi** [comment]
@ilyamandel macos took ~35min (after caching) while ubuntu took ~8min

**Comment by ilyamandel** [comment]
I think this has been overtaken by other developments / implemented by other PRs, so closing this one.

**Pull request closed without merging**
