### PR TITLE
New grids functionality - see issue #412

### LINKED ISSUE #412: Grids-Proposal Discussion
**Discussion of the new branch `grids-proposal` that Jeff put together to expand grid functionality.**

[GridsProposal.pdf](https://github.com/TeamCOMPAS/COMPAS/files/5442633/GridsProposal.pdf)

### PR DESCRIPTION
**Pull request by jeffriley**
Minor tweaks and fixes
Changelog updated
Documentation updated

I have *not* updated the post-processing scripts - a few header strings that affect the post-processing code may have changed ('CHE_Option' changed to 'CHE_Mode', and I fixed a few typos (but not sure which of those may affect the post-processing code). I think a couple of people might be working on the post-processing code at the moment, so I propose to not change it as part of this merger of new functionality - it should be reasonably easy to pick up the header string changes as they are noticed.

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
Do you mean issue #412?

**Comment by jeffriley** [comment]
I do!  Sorry...

**Review by ilyamandel — COMMENTED** [review]
comment in python submit: 
"it was too had to locate the files" --> "it was too hard to locate the files"

-- _fixed, along with a couple of non-ASCII characters_

**Review by ilyamandel — APPROVED** [review]
Code looks good, tests look reasonable -- very nice!

**Pull request merged**
