### PR TITLE
Fixed application of WolfRayetFactor

### PR DESCRIPTION
**Pull request by LiekeVanSon**
Small changes to fix the application of OPTIONS->WolfRayetFactor() to all WR prescriptions (currently it only applies to part of the WR mass loss prescriptions in an inconsistent way)

I tried to only apply WolfRayetFactor() at the highest level possible without applying WR factor twice

(somewhat related to issue #1211; there is no 'NONE' option for WR mass loss, making WolfRayetFactor() more essential than the other wind multiplication factors)

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
Thanks Lieke.  I haven't looked at the code changes yet - I'll do that later.  Just a note to say that you need to describe the changes in changelog.h, and change COMPAS version number.

**Review by ilyamandel — COMMENTED** [review]
Hi @LiekeVanSon ,

I haven't traced through where the WR factors are applied carefully, but I trust you.  

However, from the point of future development, I find it rather confusing that some functions (with similar names) now apply this factor and some don't.  E.g., CalculateMassLossRateWolfRayetZDependent() and CalculateMassLossRateHeliumStarVink2017() do not, while CalculateMassLossRateWolfRayetShenar2019() and CalculateMassLossRateBelczynski2010() do.  This seems like an error-prone situation for future development.  Is there a way to make this more uniform?

**Comment by jmerritt1** [comment]
Thanks Lieke, we agree that moving the WR factor up a level to the wrapper functions is much clearer and less error prone.

**Comment by LiekeVanSon** [comment]
Hi All, sorry for the slow response!

 I agree with your worries that implementing the WR factor in lower levels is not what we want. 
 I removed OPTIONS->WolfRayetFactor()  from the Shenar 2019 function, but I believe the problem is that CalculateMassLossRateMerritt2024 using WR_MASS_LOSS_PRESCRIPTION::BELCZYNSKI2010 points back to the wrapper function of the overall wind prescription BELCZYNSKI2010. 

 So I think we _have_ to apply the WR factor directly in BELCZYNSKI2010, and cannot do it again in the MERRITT2024 + WR:BELCZYNSKI2010 case


I now apply the WR factor as follows in the   "HURLEY" , "BELCZYNSKI2010" , and "MERRITT2024" prescriptions as below:

**HeMS::CalculateMassLossRateHurley()** 
-  **_OPTIONS->WolfRayetFactor()** *_ CalculateMassLossRateWolfRayet(0.0)

**HeMS::CalculateMassLossRateBelczynski2010()**
- **_OPTIONS->WolfRayetFactor()** *_ CalculateMassLossRateWolfRayetZDependent(0.0);

**HeMS::CalculateMassLossRateMerritt2024()**
- case WR_MASS_LOSS_PRESCRIPTION::SANDERVINK2023:{
 MdotWR = **_OPTIONS->WolfRayetFactor()** *_ std::max(Mdot_Sander2023, Mdot_Vink2017);
 
- case WR_MASS_LOSS_PRESCRIPTION::SHENAR2019: {
MdotWR = **_OPTIONS->WolfRayetFactor()** *_  std::max(Mdot_Shenar2019, Mdot_Vink2017);

- WR_MASS_LOSS_PRESCRIPTION::BELCZYNSKI2010: {
MdotWR = CalculateMassLossRateBelczynski2010(); // OPTIONS->WolfRayetFactor() is applied in Belczynski2010 function 


let me know if this makes sense to you all :)

**Review by ilyamandel — APPROVED** [review]
Thank you, @LiekeVanSon !

**Comment by ilyamandel** [comment]
@jeffriley -- waiting for your approval.

**Comment by jeffriley** [comment]
Sorry - I was en route to Australia I think...

**Review by jeffriley — APPROVED** [review]
Thanks @LiekeVanSon !

**Pull request merged**
