### PR TITLE
Removed functions related to MassTransferCase, in favor of the MassTransferDonorHist param

### LINKED ISSUE #483: Mass transfer case labelling wrong (most notably, Case C mass transfer being labelled as Case B)
**Describe the bug**
_tldr: I think HG::DetermineMassTransferCase is overwriting GiantBranch::DetermineMassTransferCase such that case C mass transfer is always labelled as case B. But there seem to be more issues with the labelling other than this..._

@LiekeVanSon presented some work to us today and pointed out that COMPAS seems to be mislabelling mass transfer cases. Here are some lovely plots made by her that illustrate the point.

In this plot each binary is coloured based on the mass transfer case of each star in the binary (i.e. A B, means primary is case Case, secondary is case B). As you can see, there are no pink/purple points. The unique cases that show up in the results are `[‘- -’ ‘- A’ ‘- B’ ‘A B’ ‘B -’ ‘B B’]`. To further illustrate this, here is another of Lieke's plots that shows the detailed evolution of a binary labelled ["-, B"] (none, case B)

It seems from this plot that the mass transfer for each star seems to be occurring after CHeB starts and so should actually be case CC.

We looked into this further together and it seems that due to the way the inheritance works in COMPAS, the HG::DetermineMassTransferCase function is overwriting the GiantBranch::DetermineMassTransferCase function and leading to all case C being labelled case B. I think this can be fixed by moving GiantBranch::DetermineMassTransferCase to CHeB::DetermineMassTransferCase!

This does **not** explain why in the second plot, case C mass transfer is being labelled as None. So there may be further issues.

Lieke and I were also puzzled as to why HeMS and HeHG are referred to as Case A and Case B mass transfer?

**Label the issue**
`urgency_low`,`severity_moderate`

**To Reproduce**
Run a grid of binaries and check the unique mass transfer cases, case C never shows up

**Expected behavior**
Stars of CHeB and beyond should be case C.

**Versioning (please complete the following information):**
 - COMPAS - v02.17.11

### PR DESCRIPTION
**Pull request by reinhold-willcox**
I think this addresses the conversation in PR #484.

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
Nice job Reinhold.

I think there are references in the documentation to MASS_TRANSFER_CASE_INITIAL  that need to be removed.

**Review by TomWagg — COMMENTED** [review]
All compiles and runs properly, Mt_Case_Initial is gone from the output. Looks good to merge after what Jeff said about docs.

Also, to address what @avigna  was saying in the other PR, is there a reason to _not_ include the accretor information in the history? If it is useful then perhaps you could list the history as something like "1-1,2-1" where it's MS->MS and HG->MS mass transfer?

**Comment by jeffriley** [comment]
> something like "1-1,2-1" where it's MS->MS and HG->MS mass transfer

Just need to make sure we don't use a character that could possibly be a delimiter for fields in the file (currently comma, tab, and space).  So maybe "1-1:2-1".

**Comment by ilyamandel** [comment]
I would vote against including accretor information in the history without an obvious use case.   We already have that information available in the RLOF output file.  The only reason to keep it in the code is we are making "live" decisions about future evolution based on past evolution.  I don't currently see us doing that based on accretor history...  and every extra line of code is an extra line to maintain.

**Comment by reinhold-willcox** [comment]
@ilyamandel sounds good, I'll just fix the documentation then.

**Comment by reinhold-willcox** [comment]
@jeffriley Should be all set, let me know if I need to do anything else.

**Review by jeffriley — APPROVED** [review]
All good

**Pull request merged**
