### PR TITLE
Accretion-Induced Collapse

### LINKED ISSUE #827: --allow-H-rich-ECSN flag does not work
I found ECSNe labeled as H-poor (I ran with --allow-H-rich-ECSN: False ) in binaries with huge separations — sometimes >1000 AU.

This is odd, because H-poor SNe should only happen in stripped stars, and stripping can only happen in interacting binaries.

On investigation, it turns out that we assume that H-poor stars are those that formed from objects of type HeMS and later.  Of course, ECSNe are formed from ONe WDs, so always satisfy this — i.e., all ECSNe are always H-poor, and the flag is meaningless.

What the flag was supposed to represent is whether the star had been stripped of its H envelope earlier, but it does not detect this as currently implemented.

P.S. A probably unrelated issue — but still one to fix -- is that our ONeWDs can have total masses larger than He core masses.

### PR DESCRIPTION
**Pull request by reinhold-willcox**
- Added Accretion-Induced Collapse as an alternative SN, only ever applied to ONeWDs which accrete above the Chandrasekhar mass. 
- Added relevant functions for IsAIC() and ExperiencedAIC()
- Updated documentation for relevant sections
- Updated changelog, including a typo in the previous entry

### CODE REVIEW

**Review by jeffriley — COMMENTED** [review]
Changes look ok to me, with one small nit-pick:

This comment

 * @return        Stellar type of remnant (always STELLAR_TYPE::NEUTRON_STAR)
 
in ONeWD::ResolveAIC() is not strictly true.  It is true if the sanity check passes (i.e. if IsSupernova() is true), but it won't (or shouldn't) be true if not.

Otherwise, certainly from a code perspective, I approve.  The physics also looks ok, but I'm not familiar enough with AIC to comment sensibly...

Edit:

Just a thought.  Instead of this construct:

if (IsSupernova()) {
    ...
    ...
    return STELLAR_TYPE::NEUTRON_STAR;
}
else {
    return m_StellarType;
}

you could instead do this:

STELLAR_TYPE stellarType = m_StellarType;

if (IsSupernova()) {
    ...
    ...
    stellarType = STELLAR_TYPE::NEUTRON_STAR;
}

return stellarType ;

It's marginally cleaner, and more in keeping with the aim to have a single entry and single exit in any function.
If you don't like that, this is more in keeping with the way we do sanity checks at the start of a function:

if (!IsSupernova()) return m_StellarType;

...
...

return STELLAR_TYPE::NEUTRON_STAR;

so we exit immediately if we shouldn't be there.  Just a bit easier to see at a glance what's happening.

Up to you.

**Review by ilyamandel — CHANGES_REQUESTED** [review]
I second @jeffriley 's suggestions above.  Also, keep in mind that, strictly speaking, WDs can supernovae -- type IAs.  So please clarify that comment.  

Also, given other recent commits, please merge dev into this one and update changelog.h, including version number.

Otherwise, looks awesome, @reinhold-willcox !

**Comment by reinhold-willcox** [comment]
Issues should now be addressed, let me know if I missed anything.

**Review by jeffriley — CHANGES_REQUESTED** [review]
Thanks @reinhold-willcox.  You don't actually need the "else" for the sanity check.

If you just have:

if (!IsSupernova()) return m_StellarType;

as the first line of executable code, that gets you out of there if you shouldn't be there - the "else" is superfluous (because of the return).

**Review by ilyamandel — APPROVED** [review]

**Review by jeffriley — APPROVED** [review]
All good.

**Pull request merged**
