### PR TITLE
Renamed variable in dynamical tides to avoid confusion

### PR DESCRIPTION
**Pull request by veome22**
A small variable name change, as requested by @ilyamandel .

Please let me know if I should also add this to the changelog.

### CODE REVIEW

**Review by jeffriley — COMMENTED** [review]
Ok, since Ilya pointed out the variable...  why do we need it at all?  It's only in one equation isn't it?  Why not just use "envMass / m_Mass" in that equation?  I'm all for making things clearer and reducing cpu, but I don't see that we actually gain anything from declaring a new variable here.

**Comment by veome22** [comment]
@jeffriley I agree, it only shows up once. I had defined `one_minus_beta` along with the other variables before I realized this. I can remove the definition.

And just to clarify-- does this change need a note in the changelog?

**Comment by jeffriley** [comment]
> And just to clarify-- does this change need a note in the changelog?

Yes, we should.  I know it feels like it's not necessary in this case, but if we don't, then two users might have different code, but both labelled with the same version - that's not right...  Just note it as "code cleanup".

**Comment by ilyamandel** [comment]
Thank you, @veome22 , looks good!  I agree with Jeff's suggestion of removing the extra variable you don't really need and updating the changelog.  @jeffriley , I'll be traveling back to Australia over the next couple of days, so I hope you can approve.

**Review by ilyamandel — APPROVED** [review]
Looks good!

**Pull request merged**
