### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ilyamandel**
Minor fixes to documentation and python comments, not touching C++ files.

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
Looks good save for the following:

In online-docs/pages/User guide/Program options/program-options-list-defaults.rst:

Remove the apostrophe in "zeta's" on line 287:
    Warning: if running with ``--critical-mass-ratio-prescription``, zeta's will not be computed, 

Fix terminating quotes around "MULLERMANDEL" on lines 499 and 1055:
    however, if using ``MULLERMANDEL'', it is recommended to keep them consistent by doing so for both. |br|
    however, if using ``MULLERMANDEL'', it is recommended to keep them consistent by doing so for both. |br|


Edit: @ilyamandel if you're ok with the suggested changes I can make them...

**Comment by ilyamandel** [comment]
Thanks for spotting these, @jeffriley !  Fixed along with a couple of other quotation marks while I was at it. :)

**Review by jeffriley — APPROVED** [review]
Thanks @ilyamandel .  All good from me - I'll leave the final decision to @reinhold-willcox and @IsobelMarguarethe

**Comment by ilyamandel** [comment]
I'll just pull it in -- we have too many PRs hanging around, and this is documentation only, so trivial to add more things if others find more issues. :)

**Pull request merged**
