### PR TITLE
Non zams initialization

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Added option and code functionality for the user to set the stellar type they want at Zams. This is useful for anyone working with, e.g, He stars, X-ray binaries, WDs etc. who want to have more control over the initial conditions of their post-MS binary. Due to the non-trivial value of the tau age parameter, we should only allow users to initialize MS, HeMS, WD (any), NS, or BH stars.

### CODE REVIEW

**Comment by reinhold-willcox** [comment]
This PR encompasses and supercedes PR #732, which is now closed.

**Comment by SimonStevenson** [comment]
It's great that you're working on this, I think it would be a very useful feature. I'd be happy to help review this.

**Comment by reinhold-willcox** [comment]
@SimonStevenson  It should be ready to review now, if you have time.

**Review by jeffriley — CHANGES_REQUESTED** [review]
I'll review this wrt terminology and code consistency

**Comment by reinhold-willcox** [comment]
@jeffriley It says you requested changes but I don't see any requests. Is that a placeholder for future requests, or am I just not seeing existing ones?

**Comment by jeffriley** [comment]
It's a placeholder - I did it so the PR wouldn't merge until we've made some changes.  I will have time to look at this after the end of this week - but I will be travelling for most of May, so may not get much done until I get back at the start of June.

**Comment by ilyamandel** [comment]
@jeffriley -- I notice that there is a note from you from April that says you are about to look at this PR. ;-)  I am not sure if it's still relevant (@reinhold-willcox ?) but I think we should probably clean up very old PRs one way or another.

**Comment by reinhold-willcox** [comment]
@ilyamandel This functionality would be very useful in COMPAS, in my opinion, so I would advocate addressing the remaining issues and getting the code committed. 

As it stands, the code here (at some point) worked for the initialization of MS, HeMS, WD, NS, and BH. From memory, Jeff and I were debating whether to allow for the initialization of other stellar types, and stars with tau != 0 (e.g stars partway along the HG), but this could be an extension in a later PR. There was also a question about the naming convention of the variables, but this is cosmetic so I am happy to adopt whatever convention works for the majority. If now is the right time to address these issues, I'll go ahead and update this branch to the latest version of `dev`.

**Comment by ilyamandel** [comment]
I am not aware of any other major changes in progress, @reinhold-willcox , just bug fixes -- so I agree now would be a good time to do this, if you have spare cycles.  Thank you!

**Comment by reinhold-willcox** [comment]
Closing: outdated wrt PR #1036

**Pull request closed without merging**
