### PR TITLE
plotter updates

### LINKED ISSUE #814: plot_detailed_evolution.py does not display numbers on abscissa
plot_detailed_evolution.py does not display numbers on abscissa, so can't actually tell how much time passed

### PR DESCRIPTION
**Pull request by reinhold-willcox**
addresses #814 

- fixed missing time values on x-axes of plotter 
- cleaned up const radii lines in HR diags

### CODE REVIEW

**Comment by ilyamandel** [comment]
@reinhold-willcox -- this claims to have a conflict?

**Review by ilyamandel — APPROVED** [review]

**Comment by reinhold-willcox** [comment]
@ilyamandel weird, this is the second time the readthedocs check failed, and both times the changed files have been unrelated to the documentation. I'll take a look

**Comment by ilyamandel** [comment]
@reinhold-willcox -- I wasn't worried about ReadTheDocs, but about a genuine conflict:

This branch has conflicts that must be resolved
Use the [web editor](https://github.com/TeamCOMPAS/COMPAS/pull/815/conflicts) or the  to resolve conflicts.
Conflicting files
utils/plot_detailed_evolution.py

Can you please check?

**Comment by ilyamandel** [comment]
Sorry, @reinhold-willcox ,  I have one more request.  Now that we include a point for the “merger” in the detailed evolution plots, everything else becomes so compressed as to be unreadable.  I think we need to omit the merger point from the 4-panel plot…

image

**Comment by reinhold-willcox** [comment]
@ilyamandel I took a closer look at this, and got an error related to the MT_TRACKER values from PR #794 , so I'll address that now, and include these changes in that PR.

**Comment by reinhold-willcox** [comment]
Actually, @ilyamandel could you send me the grid file for the system you plotted?

**Comment by ilyamandel** [comment]
@reinhold-willcox -- I don't have the grid file (it's a system @IsobelMarguarethe generated), but it's the same one we discussed in Slack, 
image

**Comment by ilyamandel** [comment]
@reinhold-willcox -- since this is being taken care of in #794 , can we close this PR?

**Comment by reinhold-willcox** [comment]
@ilyamandel yes this should be closed when #794 is approved.

**Pull request merged**
