### PR TITLE
Fixed semi-major axis units on post-CEE logs

### PR DESCRIPTION
**Pull request by nrsegovia**
Small fix, the conversion from AU to Rsol was wrong. See #876.

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
Good catch.  The value is only used to print to the logfiles at the moment, so the defect should have had no other effects.

Need to update changelog.

**Comment by nrsegovia** [comment]
> Good catch. The value is only used to print to the logfiles at the moment, so the defect should have had no other effects.
> 
> Need to update changelog.

I just followed the style from previous updates in `changelog.h`, please let me know if further changes are needed.

**Review by jeffriley — APPROVED** [review]
Looks good - thanks!

**Comment by jeffriley** [comment]
@reinhold-willcox Looks like we're failing on one of t he dependencies - can you take a look?

**Pull request merged**
