### PR TITLE
add gitignore

### PR DESCRIPTION
**Pull request by avivajpeyi**

### CODE REVIEW

**Review by jeffriley — APPROVED** [review]
Thanks @avivajpeyi !

**Comment by reinhold-willcox** [comment]
We had a .gitignore, what happened to it?

**Comment by jeffriley** [comment]
Apparently I deleted it accidentally.  I'll figure git out one day...

**Comment by reinhold-willcox** [comment]
classic

**Comment by ilyamandel** [comment]
I asked Jeff about that when reviewing the PR that deleted .gitignore and
he convinced me that it was only on his own machine -- which doesn't make
sense in retrospect, of course.  So it's my fault too for being too easily
convinced. :)

**Pull request merged**
