### PR TITLE
Multiple enhancements

### PR DESCRIPTION
**Pull request by ilyamandel**
- Added timestep-multiplier option to adjust SSE and BSE timesteps relative to default (issue #391 )
- Added eccentricity printing to RLOF logging
- Adjusted pythonSubmitDefault.py to include PESSIMISTIC CHE
- Updated documentation

### CODE REVIEW

**Review by themikelau — APPROVED** [review]
Checked that code compiles, runs, outputs sensible pre- and post-RLOF eccentricity. Documentation pertaining to pre- and post-RLOF eccentricity also looks good.

**Review by TomWagg — APPROVED** [review]
All compiles and runs properly, timestep multiplier option works as advertised :)

**Review by jeffriley — CHANGES_REQUESTED** [review]
Looks good - apart from the year of the change in changelog.h :-)

Actually, it just occurred to me that there is no sanity check in options.cpp for a zero or negative timestep multiplier.  Can you add that please?

**Comment by ilyamandel** [comment]
Thanks, @jeffriley -- should be fixed now. :)

**Review by jeffriley — APPROVED** [review]
Approved

**Pull request merged**
