### PR TITLE
Add option flexible T convective

### PR DESCRIPTION
**Pull request by reinhold-willcox**
If we set `--envelope-state-prescription FIXED_TEMPERATURE`, we can now specify an arbitrary cutoff temperature with `--convective-envelope-temperature-threshold`

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
In program-options-list-defaults.rst

    **convective-envelope-temperature-threshold** |br|
    Temperature [K] threshold, below which the envelope's of giants are convective. 
    Requires --envelope-state-prescription is FIXED_TEMPERATURE. |br|
    Default = 5370

Remove the apostrophe

"Requires --envelope-state-prescription is FIXED_TEMPERATURE." - should that not be something like

"Only used for --envelope-state-prescription is FIXED_TEMPERATURE, ignored otherwise"

"Requires" implies the user specifying the option without also specifying "--envelope-state-prescription is FIXED_TEMPERATURE" will result in an error

What about the options category listing in the docs?



"Default = 5370"

In constants.h the value is 5.3703E3


Is the "// RTW" at line 917 of Options.cpp there for a reason?

@ilyamandel should review for physics

**Comment by reinhold-willcox** [comment]
Agreed with most of your points, those are now fixed

> What about the options category listing in the docs?
> 
> "Default = 5370"
> 
> In constants.h the value is 5.3703E3

I skipped the .3 because we don't know temperatures nearly this well, and it comes from 10^3.73, so we're approximating anyway.
 
> Is the "// RTW" at line 917 of Options.cpp there for a reason?

Nah, thanks for catching, that's how I know where I've partially edited some code to come back to it later. It is removed now.

**Comment by jeffriley** [comment]
Thanks @reinhold-willcox 

> I skipped the .3 because we don't know temperatures nearly this well, and it comes from 10^3.73, so we're approximating anyway.

Sure, I get we're approximating, but my point was the documentation should match the code - so one of them should change to match the other.  We shouldn't say we do something but actually do something slightly different.  If we don't know temperature that well, why have that precision in constants.h?

Edit: Just occurred to me that the help text and RunDetails file will show the value from constants.h, so more reason to make the the documentation show what's in constants.h (whether you change what's in constants.h is up to you, but the documentation should match the help text, RunDetails content, and the code)

**Comment by jeffriley** [comment]
Oh - what about adding the new option to the category listing in the docs?

**Review by jeffriley — APPROVED** [review]
Looks good - thanks @reinhold-willcox 

Physics looks ok to me too, but @ilyamandel might want to review

**Review by ilyamandel — CHANGES_REQUESTED** [review]
Very minor change request: @reinhold-willcox , can you please apply the same changes to Options.cpp that @jeffriley requested for the documentation?

        (
            "convective-envelope-temperature-threshold",                               
            po::value<double>(&p_Options->m_ConvectiveEnvelopeTemperatureThreshold)->default_value(p_Options->m_ConvectiveEnvelopeTemperatureThreshold),                                                                  
            ("Temperature [K] threshold, below which the envelope's of giants are convective. Requires --envelope-state-prescription is FIXED_TEMPERATURE (default = " + std::to_string(p_Options->m_ConvectiveEnvelopeTemperatureThreshold) + ")").c_str()
        )

**Review by ilyamandel — APPROVED** [review]

**Pull request merged**
