### PR TITLE
Moving defaults to Options.cpp

### PR DESCRIPTION
**Pull request by ilyamandel**
- Port defaults from preProcessing/pythonSubmit.py to options.cpp
- Minor fixes (e.g., documentation)

### CODE REVIEW

**Comment by ilyamandel** [comment]
[Setting to draft because, contrary to expectations, I do not get an identical output when running ./COMPAS from the command line vs. from pythonSubmit]

**Comment by ilyamandel** [comment]
OK, I figured out what the difference is, but not why there is a difference.  Even though I explicitly set m_Metallicity = 0.0142, I get binaries with metallicities of 0.02 (unless I again set --metallicity 0.0142 at the command line).  Now, that's weird, because my runDetails are identical when ./COMPAS --random-seed 0 from the command line or running via pythonSubmit :

< metallicity = 0.014200, DEFAULT_USED, DOUBLE
< metallicity-distribution = 'ZSOLAR', DEFAULT_USED, STRING
< metallicity-max = 0.030000, DEFAULT_USED, DOUBLE
< metallicity-min = 0.000100, DEFAULT_USED, DOUBLE
---
> metallicity = 0.014200, USER_SUPPLIED, DOUBLE
> metallicity-distribution = 'ZSOLAR', USER_SUPPLIED, STRING
> metallicity-max = 0.030000, USER_SUPPLIED, DOUBLE
> metallicity-min = 0.000100, USER_SUPPLIED, DOUBLE

Which actually means that something is wrong in my book.  @jeffriley , can you help out? :)

**Comment by jeffriley** [comment]
> Which actually means that something is wrong in my book. @jeffriley , can you help out? :)

Not with your notebook (...book :-)), but I think I can explain why you get Z = 0.02 

Look in BaseBinaryStar.cpp where we initialise metallicity for the binary (line 110 in v02.19.04).  If the user specified metallicity we use it, otherwise we sample it - we don't actually use the default value (I noticed this the other day - we do the same with secondary mass - we could think a little more about what we do here (there are several options - use what's specified, use the default, use a distribution - what's the best way to decide which?  Should we only sample if the user specified a distribution? When I say "we" I'm using the royal "we" - these choices were mine when I coded this part, so all my fault :-))).  

So, back to metallicity.  If the user doesn't specify metallicity we'll sample it, using utils::SampleMetallicity().  The default metallicity distribution is ZSOLAR, and that just returns ZSOL.  So to default to 0.0142 you should change that.  Which brings up...

I notice you've just used hard-coded constants in Options.cpp (you replace a couple of symbolic names defined in constants.h with numbers).  I ran out of time and energy when I ported the legacy code, but I had always had in the back of my mind that we would pull the hard-coded constants out of the code and put them in constants.h with symbolic names.  For the program option defaults it really doesn't matter where they are I suppose (constants used throughout the code - i.e. not program option defaults -  should be in constants.h), as long as they are all in one place, but I think replacing numbers with symbolic names (that are associated with numbers as in constants.h) might make it easier for people to find the values (I know whenever I have to find the default value for a program option I go to Options.h first to find the getter so I can see what the m_* variable name is, then I go to Options.cpp to find where the variable is initialised - I think if we had a list of "option constants" somewhere (whether that be in constants.h or (say) at the top of Options.h with symbolic names that people could recognise, it might make life easier).

**Comment by jeffriley** [comment]
Oh, and one more thing.  After this PR is merged into the code, we need to go through the methods paper to make sure any defaults we describe agree with the code (I think in my section I used C++ code defaults, whereas in other places we might have use pythonSubmit defaults)

**Comment by ilyamandel** [comment]
@jeffriley -- thank you.  As we discussed offline, I was trying to ensure that calling 
./COMPAS --random-seed 0
from the command line would produce identical results to calling default pythonSubmit.  That's now been achieved, and a new ZSOL_ASPLUND constant has been defined. :)
I'll also propose a new feature to improve documentation (for later).

**Review by jeffriley — APPROVED** [review]
All good!

**Comment by ilyamandel** [comment]
This will close #562 .

**Pull request merged**
