### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by SimonStevenson**

### CODE REVIEW

**Comment by SimonStevenson** [comment]
One of the recommended items here https://github.com/TeamCOMPAS/COMPAS/community

**Comment by ilyamandel** [comment]
Good idea, but since this isn't a hot fix, I suggest merging into dev first.  This will also help us keep master and dev synchronised.

**Comment by reinhold-willcox** [comment]
This looks good, thanks Simon! I'll give the Open Source Guides a read when I have the chance.

**Comment by ilyamandel** [comment]
I still suggest that this be changed to pull into dev, not master -- @SimonStevenson ?

**Comment by SimonStevenson** [comment]
Yeah I agree, this should be into dev

**Pull request merged**
