### PR TITLE
Defect repair:

### PR DESCRIPTION
**Pull request by jeffriley**
(1) Added checks for maximum time and timesteps to SSE code- issue #394

### CODE REVIEW

**Comment by jeffriley** [comment]
Fix for issue #394 .

Tested with:

    single_star = True
    single_star_mass_steps = 1000
    single_star_mass_min   = 0.1
    single_star_mass_max   = 100.0  

    maximum_evolution_time = 13700.0
    maximum_number_timesteps = 99999

Run completed - did not hang.  Stars with initial mass < ~0.9 Msol exceeded the allowed time, all other stars evolved ok.

**Review by ilyamandel — COMMENTED** [review]
if (m_Star->Time() > OPTIONS->MaxEvolutionTime()) {
         dt = m_Star->CalculateTimestep() * OPTIONS->TimestepMultiplier();           // calculate new timestep		             status = EVOLUTION_STATUS::TIMES_UP;                                // out of steps...

          }
         EvolveOneTimestep(dt);                      // evolve for timestep		         else if (stepNum >= OPTIONS->MaxNumberOfTimestepIterations()) {
             status = EVOLUTION_STATUS::STEPS_UP;                                // out of time...
         }

The comments "out of steps" and "out of time" are reversed relative to the code

**Comment by jeffriley** [comment]
Yes, they are :-)  Oops.  I'll fix that.

**Comment by SimonStevenson** [comment]
The changes made in this PR work, in the sense that now the evolution of a star is stopped if its lifetime exceeds the maximum_evolution_time. 

However, if I increase maximum_evolution_time to an arbitrarily large number (I just added three 0s), I still encounter isuue #394 . I need to do this to evolve these stars through to their remnant phases.

In a run of 1000 stars with masses spaced linearly between 0.7 and 0.9 solar masses, I get:

477: Allowed timesteps exceeded: RandomSeed = 477, Initial Mass = 0.7954, Metallicity = 0.0142, Core_Helium_Burning

```
    single_star = True
    single_star_mass_steps = 1000
    single_star_mass_min   = 0.7
    single_star_mass_max   = 0.9    
    maximum_evolution_time = 13700000.0 
```

In principle, this will (eventually) finish, but still takes a long time, and hasn't resolved the underlying issue.

Hence I'm happy to merge this, but we should not close #394

**Comment by ilyamandel** [comment]
@SimonStevenson -- try increasing the number of time steps and/or increasing the timestepMultiplier (so each timestep is longer).

**Review by ilyamandel — APPROVED** [review]

**Review by SimonStevenson — APPROVED** [review]
Changes are fine and make code more self consistent, but do not solve underlying issue #394

**Comment by jeffriley** [comment]
> but do not solve underlying issue #394

The problem I saw - but didn't try to find the root cause of - was that the age of the star goes a long way past 14Gyr, then goes to something very small (< 1 Gyr I think), then starts increasing again.

I don't recall without checking the code how age is calculated, but don't we at some stage use Hurley's equations to calculate age?  If that's so, do we know they produce coherent results for evolution times > 14Gyr?

**Comment by SimonStevenson** [comment]
@ilyamandel I think increasing the maximum number of steps will just effectively make it hang, but I can check. [EDIT: Seems to just be hanging ...]

`maximum_number_timesteps = 999999`

**Comment by SimonStevenson** [comment]
@jeffriley I think the SSE formulae don't know anything about a special time at 14 Gyr. Indeed, the lower mass stars (with longer lifetimes) evolve to their remnant phase fine. 

Resetting lifetimes sounds like it could be the culprit, but I have no idea why that would happen ....

(the problem seems to be during CHeB, according to my stalled evolution above)

**Comment by SimonStevenson** [comment]
Indeed eventually got 
`39: Allowed timesteps exceeded: RandomSeed = 39, Initial Mass = 0.7956, Metallicity = 0.0142, Core_Helium_Burning`
after ~10 minutes of running with maximum_number_timesteps = 999999. Will try timestep multiplier now

**Comment by SimonStevenson** [comment]
with 
`timestep_multiplier = 2.0`
it seems to have shifted the mass where I encountered the problem slightly
`9: Allowed timesteps exceeded: RandomSeed = 9, Initial Mass = 0.7836, Metallicity = 0.0142, Core_Helium_Burning`

**Comment by ilyamandel** [comment]
Looks like the code is picking unreasonable time step sizes.  Let me check.

**Comment by ilyamandel** [comment]
I can't reproduce the problem.  @jeffriley , @SimonStevenson -- can you please tell me the exact parameters?

COMPAS v02.15.12
Compact Object Mergers: Population Astrophysics and Statistics
by Team COMPAS (http://compas.science/index.html)
A binary star simulator

Start generating stars at Thu Oct  8 13:14:30 2020

0: RandomSeed = 0, Initial Mass = 0.79, Metallicity = 0.0142, Carbon-Oxygen_White_Dwarf

Generated 1 of 1 stars requested

Simulation completed

End generating stars at Thu Oct  8 13:14:31 2020

Clock time = 0.21403 CPU seconds

**Pull request merged**
