### PR TITLE
add option to use default config (and remove redundant test config file)

### PR DESCRIPTION
**Pull request by avivajpeyi**
Currently `compas_run_submit` always requires a position arg of the `config.yml` . There may be cases when a user would like to use the default config, and maybe just specify a grid file. 

This PR makes it so the `config.yml` is just an optional argument. 
It also adds the ability to specify the `--grid` filename. 

Requires #1122 to be merged first.

### CODE REVIEW

**Review by ilyamandel — CHANGES_REQUESTED** [review]
Looks fine to me (though I am not a python expert).  But is there any particular reason for the change in the grid file (removing the metallicity specification)?  

[Also note the need to merge in dev, which I am now too scared to do via github. ;-) ]

**Comment by jeffriley** [comment]
> But is there any particular reason for the change in the grid file (removing the metallicity specification)?

@ilyamandel if we leave metallicity = 0.001 we don't get any DCOs...  the pytests need minimum 2 DCOs


    $ cat grid.txt
    --initial-mass-1 32.0 --initial-mass-2 31.0 --metallicity 0.001 --eccentricity 0.0 --semi-major-axis 3.5 --kick-magnitude-1 0.0 --kick-magnitude-2 0.0
    --initial-mass-1 32.0 --initial-mass-2 31.0 --metallicity 0.001 --eccentricity 0.0 --semi-major-axis 3.5 --kick-magnitude-1 0.0 --kick-magnitude-2 0.0


    $ ./compas --grid grid.txt
    
    COMPAS v02.45.00
    Compact Object Mergers: Population Astrophysics and Statistics
    by Team COMPAS (http://compas.science/index.html)
    A binary star simulator
    
    Go to https://compas.readthedocs.io/en/latest/index.html for the online documentation
    Check https://compas.readthedocs.io/en/latest/pages/whats-new.html to see what's new in the latest release
    
    Start generating binaries at Fri May 10 08:45:11 2024
    
    0: Stars merged: (Main_Sequence_>_0.7 -> Naked_Helium_Star_MS) + (Main_Sequence_>_0.7 -> Naked_Helium_Star_MS)
    1: Stars merged: (Main_Sequence_>_0.7 -> Naked_Helium_Star_MS) + (Main_Sequence_>_0.7 -> Naked_Helium_Star_MS)
    
    Generated 2 of 2 binaries requested
    
    Simulation completed
    
    End generating binaries at Fri May 10 08:45:11 2024
    
    Clock time = 0.053216 CPU seconds
    Wall time  = 0000:00:00 (hhhh:mm:ss)


    $ cat grid.txt
    --initial-mass-1 32.0 --initial-mass-2 31.0 --eccentricity 0.0 --semi-major-axis 3.5 --kick-magnitude-1 0.0 --kick-magnitude-2 0.0
    --initial-mass-1 32.0 --initial-mass-2 31.0 --eccentricity 0.0 --semi-major-axis 3.5 --kick-magnitude-1 0.0 --kick-magnitude-2 0.0


    $ ./compas --grid grid.txt
    
    COMPAS v02.45.00
    Compact Object Mergers: Population Astrophysics and Statistics
    by Team COMPAS (http://compas.science/index.html)
    A binary star simulator
    
    Go to https://compas.readthedocs.io/en/latest/index.html for the online documentation
    Check https://compas.readthedocs.io/en/latest/pages/whats-new.html to see what's new in the latest release
    
    Start generating binaries at Fri May 10 08:45:50 2024
    
    0: DCO formed: (Main_Sequence_>_0.7 -> Black_Hole) + (Main_Sequence_>_0.7 -> Black_Hole)
    1: DCO formed: (Main_Sequence_>_0.7 -> Black_Hole) + (Main_Sequence_>_0.7 -> Black_Hole)
    
    Generated 2 of 2 binaries requested
    
    Simulation completed
    
    End generating binaries at Fri May 10 08:45:50 2024
    
    Clock time = 0.043046 CPU seconds
    Wall time  = 0000:00:00 (hhhh:mm:ss)

**Comment by ilyamandel** [comment]
OK.  Though the output is a bit misleading: this is a double-core CE between two CHeB stars during which the stars merge, so we should probably be calling it such, rather than listing it as the merger of the cores (naked He stars). :)
However, we are now, after all of the code fixes, back to our original canonical example of 35+31 forming merging a BBH (after going through CE), so I'll revert us to that manually in a second, then approve.

**Review by ilyamandel — APPROVED** [review]
All good, approved.

**Pull request merged**
