### PR TITLE
Fix pytest errors

### PR DESCRIPTION
**Pull request by avivajpeyi**
Fixing  two errors:
1. test_plot_detailed_evol: Easy, pthing issue
2. FastCosmicIntegrator: I think this has to do with a change in the 'example bbh' file not producing BBHs?

### CODE REVIEW

**Comment by avivajpeyi** [comment]
Ah, @ilyamandel and I have spoken about (2) in the past: 
#1152

TLDR: 
Instead of using a 'comfig.yaml', Ilya suggests we use the `compasConfigDefault.yaml (default settings) but only over-write the initial conditions as command-line arguments... 

Now the ticky bit for me will be getting the command-line arguments such that we produce a BBH... Hmm

**Comment by ilyamandel** [comment]
@avivajpeyi : exactly! 
The command line arguments that are my testing default are
`./COMPAS -n 1 --initial-mass-1 35 --initial-mass-2 31 -a 3.5 --random-seed 0 --metallicity 0.001 --detailed-output
`
This should be enough of an input for plotting the van den Heuvel diagrams, etc.
If you want to do this via a grid file and have more than one BBH for cosmic integration, you can just repeat this twice (without --detailed-output)

**Comment by ilyamandel** [comment]
@avivajpeyi -- see, e.g., https://github.com/TeamCOMPAS/COMPAS/actions/runs/10543006208/job/29210464333

FAILED py_tests/test_fast_cosmic_integration.py::test_fast_cosmic_integration - IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
FAILED py_tests/test_fast_cosmic_integration.py::test_compas_output_has_dcos - IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
FAILED py_tests/test_plot_detailed_evolution.py::test_plotter - FileNotFoundError: [Errno 2] No such file or directory: '/van_den_heuvel_figures/2.png'

The first two failings are presumably because we hadn't been producing DCOs (see above) -- but the last one seems to be an issue that may have been introduced in your latest fixes?

**Comment by ilyamandel** [comment]
Hi @avivajpeyi ,
Gentle ping on this one. ;-)

**Review by ilyamandel — APPROVED** [review]
Looks amazing -- thank you, @avivajpeyi !

**Pull request merged**
