### PR TITLE
Changed test grid file to address #1104, addressed #655, #1000, #1027, #1051

### PR DESCRIPTION
**Pull request by ilyamandel**

### CODE REVIEW

**Comment by ilyamandel** [comment]
Also addressed # #430 .

**Comment by ilyamandel** [comment]
Also addressed #655 .

**Comment by ilyamandel** [comment]
Documentation change for #1000

**Review by jeffriley — APPROVED** [review]
Looks good!

**Comment by ilyamandel** [comment]
Also addressing #1027 .

**Comment by ilyamandel** [comment]
Also addressed #1051

**Review by jeffriley — APPROVED** [review]
Thanks @ilyamandel - looks good!

**Pull request merged**
