### PR TITLE
Update Github Actions compile workflow

### PR DESCRIPTION
**Pull request by emanehab99**
The compile workflow now compiles and builds COMPAS on ubuntu 20.04 anc MacOS 11. It also tests python post-processing scripts to make sure they run smoothly without errors. 
Currently the plotting script fails at the end because it doesn't recognise Latex is installed (while it is!).
There workflow also attempts compiling COMPAS and running scripts on Centos 7. However, building fails. Needs further investigation to make it work, if needed, or otherwise remove Centos config

### CODE REVIEW

**Review by jeffriley — APPROVED** [review]
Looks good.  Thanks Eman!  I'll fix the merge conflicts later.

**Comment by jeffriley** [comment]
Actually, I'm not even sure why there is a merge conflict - isn't this a new branch?  (And if I pull it to my local repo I don't see any conflicts) @reinhold-willcox any ideas?

**Comment by reinhold-willcox** [comment]
@jeffriley I'm with you, I have no idea. I can merge it into `dev` locally without issue, so maybe github is just acting up.

**Comment by reinhold-willcox** [comment]
Ah wait, the target branch `TeamCOMPAS:update_GHA_compile_workflow` is not new, and it's a bit behind `dev`. Maybe try updating that branch and the compare branch to the latest dev, and see if the conflict is resolved?

**Comment by jeffriley** [comment]
That could be it - thanks @reinhold-willcox.  I'll take a look later.

**Comment by ilyamandel** [comment]
@emanehab99 -- As mentioned above, it looks like your branch is behind dev and you have a merge conflict that needs to be resolved.  Can you please resolve these, merge dev in, and then re-request a review?  I will put this into draft mode for now.

**Pull request closed without merging**
