### PR TITLE
added moe di stefano sampler

### PR DESCRIPTION
**Pull request by reinhold-willcox**
This sampler follows the Moe & DiStefano 2017 distributions. It's adapted from Max Moe, so it should be correct. Only free parameters are m1Min, m1Max, and nSamples, defaulted to 5, 100, and 1e5 respectively. 

Output is a grid file that can be immediately submitted to COMPAS.

### CODE REVIEW

**Comment by ilyamandel** [comment]
Do we have permission from Mads Sorensen (and Max Moe) to make this public as part of the COMPAS repo?

**Comment by reinhold-willcox** [comment]
I didn't think to ask! I'll do that and report back when I get an answer.

**Comment by reinhold-willcox** [comment]
Max said he's fine with it

**Comment by ilyamandel** [comment]
Did you ask Mads, since this code is his?

**Comment by reinhold-willcox** [comment]
I can't seem to find his contact. I'll keep digging.

**Comment by ilyamandel** [comment]
Responded offline.

**Comment by ilyamandel** [comment]
This would close #213 .

**Review by ilyamandel — CHANGES_REQUESTED** [review]
@reinhold-willcox -- can you provide an example of how to run this to create a grid file, ideally both in the comments at the top of this file and in the documentation on the docs web page?  In particular

```
Due to the correlated nature of these parameters, it is not 
straightforward to supply alternative constraints, e.g
including only short period systems. Thus the only free
parameters are the maximum and minimum total mass, 
and the number of systems sampled.
```

that makes sense, but how exactly should a user specify these when calling this script?

**Comment by reinhold-willcox** [comment]
Got the green light from Max and Mads, will update with the comments shortly.

Mads asked that we cite the paper where we first implemented the script: https://arxiv.org/abs/1808.06488

**Comment by ilyamandel** [comment]
Let's add that citation to the relevant bit of code, and we will be sure to add that to the next release of the COMPAS methods paper.

**Comment by reinhold-willcox** [comment]
@ilyamandel Is this PR good to go, or are there other changes you were hoping for?

**Review by ilyamandel — APPROVED** [review]

**Pull request merged**
