### PR TITLE
Remove unused RTD files (extra RTD, extra requirements.txt)

### PR DESCRIPTION
**Pull request by avivajpeyi**
The repo has a bunch of extra, unsused requirements.txt files, while all the requirements are already in the `setup.py`. 

This PR removes the redundant `requirements.txt` files, ane updates the `setup.py` with the correct versions from the old requirements.txt. 

This PR also removes an extra duplicate of an older version of the RTD config file (there should only be one file).

### CODE REVIEW

**Review by jeffriley — APPROVED** [review]
Looks good to me.  Thanks @avivajpeyi

**Comment by ilyamandel** [comment]
@avivajpeyi -- I think this might be related to the latest changes: CI is failing, again.

Error: No file in /home/runner/work/COMPAS/COMPAS matched to [**/requirements.txt or **/pyproject.toml], make sure you have checked out the target repository

(e.g., https://github.com/TeamCOMPAS/COMPAS/actions/runs/12175865123 )

**Comment by avivajpeyi** [comment]
This is rather embarrassing... I didnt think that there would be any side effects! I thought I searched for all references to `requirements.txt`. 

Ill fix this ASAP

**Comment by avivajpeyi** [comment]
Fixed in #1306

**Pull request merged**
