### PR TITLE
Initial commit of new option to eject convective envelope of over-luminous star through pulsations

### PR DESCRIPTION
**Pull request by ilyamandel**
Added option to eject the convective envelope by pulsations (ExpelConvectiveEnvelopeAboveLuminosityThreshold) if log10(m_Luminosity/m_Mass) exceeds LuminosityToMassThreshold

### CODE REVIEW

**Comment by ilyamandel** [comment]
Old (default) behavior is unchanged by the addition of this functionality.

SSE is operating correctly with the new functionality.  This is from a run of 

./COMPAS -n 1 --mode SSE --metallicity 0.0001 --initial-mass 1.191637951222871e+02 --detailed-output --expel-convective-envelope-above-luminosity-threshold --luminous-blue-variable-prescription BELCZYNSKI --luminosity-to-mass-threshold 4.65

image

**Comment by ilyamandel** [comment]
BSE tests also look reasonable (e.g., via the following), so this should be ready for review.
 
 ./COMPAS -n 1 --mode BSE --metallicity 0.0001 --initial-mass-1 120 --initial-mass-2 110 -a 1000 --detailed-output --expel-convective-envelope-above-luminosity-threshold --luminous-blue-variable-prescription BELCZYNSKI --luminosity-to-mass-threshold 4.65

**Comment by ilyamandel** [comment]
@ryosuke-hirai -- this does not yet include pulsations in the middle of a mass transfer episode; that option will have to wait for another commit.

**Review by jeffriley — CHANGES_REQUESTED** [review]
@ilyamandel not the full review, but because you highlighted the possible parse error for the yaml file, I noticed that you missed step 13 in the instructions at the top of Options.cpp for adding new options:

    13. Add the new option to the default YAML file template in yaml.h if required.

**Review by jeffriley — APPROVED** [review]
I'm happy with the code changes - but @ryosuke-hirai probably should look over the physics.

(I would like to know why those py_tests are failing though... @avivajpeyi, @reinhold-willcox any ideas?)

**Review by ryosuke-hirai — COMMENTED** [review]
There is a typo in the comments "Treshold" in the User guide.
Other than that, it all looks good to me.

**Comment by ilyamandel** [comment]
Thank you, @jeffriley and @ryosuke-hirai !

**Pull request merged**
