### PR TITLE
added the figure numbers to two of  the folders to be consistent with…

### PR DESCRIPTION
**Pull request by FloorBroekgaarden**
… the other plotting folders

Just a naming shift; nothing big. This will make the folder hierarchy clearer for readers.

### CODE REVIEW

**Comment by FloorBroekgaarden** [comment]
I also added all the other figures as suggested by Reinhold and Jeff

**Review by ilyamandel — APPROVED** [review]
Thank you very much for the awesome work, @FloorBroekgaarden !

**Comment by ilyamandel** [comment]
@FloorBroekgaarden -- no rush at all, just a reminder that there are conflicts on this branch.

**Comment by reinhold-willcox** [comment]
@FloorBroekgaarden could you merge in the latest version of dev? Otherwise looks fine, I'll be happy to approve

**Comment by ilyamandel** [comment]
@FloorBroekgaarden -- ping regarding conflicts.

**Pull request merged**
