### PR TITLE
Eddington limit fix to issue #612

### PR DESCRIPTION
**Pull request by ilyamandel**
Corrected Eddington mass accretion limits, issue #612 (very minor change for WDs and NSs, factor of a few increase for BHs)

### CODE REVIEW

**Comment by ilyamandel** [comment]
Moving the .eps file was intentional -- otherwise, I keep over-writing it every time I re-create it as a test. :)

**Review by jeffriley — APPROVED** [review]
Approved

**Comment by reinhold-willcox** [comment]
@ilyamandel should we put *.eps files into the gitignore? We can force add them if we ever need to update new plots, but that way you can run the tests and not accidentally include them in future PRs.

**Comment by ilyamandel** [comment]
@reinhold-willcox -- I agree, gitignore would probably have been a more elegant solution. ;-)

**Comment by reinhold-willcox** [comment]
Added to #622

**Pull request merged**
