### PR TITLE
Refactoring python scripts into a module "compas_python_utils"

### PR DESCRIPTION
**Pull request by themikelau**
- Refactors various COMPAS python utility scripts into an installable python module
- Adds CLI tools to make access to some scripts easier (eg `compas_h5view`)

Closes #863, #864

### CODE REVIEW

**Comment by jeffriley** [comment]
This make affect the docker image creation - need to check the script

**Comment by avivajpeyi** [comment]
> This make affect the docker image creation - need to check the script

@jeffriley could you elaborate a bit on how this affects the docker image?

**Comment by avivajpeyi** [comment]
Todos: 

- [ ] Add tests for RunSubmit
- [ ] Add tests for Stroopwaffle Interface
- [ ] Add pytest-code coverage to show the amount of code being covered by the unit-tests
- [ ] Upload test artifacts post CI run (to view plots/logs) 
- [ ] Use black/flake8 to format py-code consistently 
- [ ] Update docs on python stuff

**Comment by jeffriley** [comment]
> > This make affect the docker image creation - need to check the script
>
> @jeffriley could you elaborate a bit on how this affects the docker image?

I don't remember (and I haven't checked...), but the script to make the docker image has to get the source files from somewhere - if we're rearranging directories we just need to check that doesn't affect the script that makes the docker image.

I confess I haven't checked to see what rearranging you're doing...  if you are rearranging the src directory, we really should have src, obj, bin, directories instead of just src (but we've done it this way for so long it probably doesn't really matter now...).

**Comment by jeffriley** [comment]
Wait... didn't I see that you were rationalising directories somewhere...?  Was I dreaming?  

Edit: Ah yes - from @reinhold-willcox "significant directory rearranging..."

**Comment by reinhold-willcox** [comment]
@jeffriley I don't know what rationalizing means here, but yes this PR includes a lot of re-organizing the directories. We do not touch the `src/` or `online-docs/` directories, but the python scripts (and related objects, e.g some images) have been moved around to make it easier for the `pip install` functionality to work.

**Comment by jeffriley** [comment]
From the Oxford dictionary:

"Rationalise: make (a company, process, or industry) more efficient"

**Comment by reinhold-willcox** [comment]
@avivajpeyi @emanehab99 

I've had to manually resolve the merge to incorporate the latest dev. Specifically, some of the conflicts were in the compas-compile-ci workflow, which I don't understand very well. I saw that some of Avi's changes were already present in the GW landscape version, and so I skipped those. Other changes running the tests in the `py_tests` directory. I think I've merged these correctly, but I could use a second opinion from someone who understands these github-ci workflows better. 

Edit: tests are failing, so these changes definitely don't work!

**Comment by avivajpeyi** [comment]
Hey @reinhold-willcox , yeah the pytests require some COMPAS output generated by the previous CI step. 



So the order of these tests need to be fixed (the postprocessing stuff needs to be run only after the COMPAS output is saved)


The run-python scripts needs to be run before the python pytests.

**Comment by avivajpeyi** [comment]
1. We now have some basic tests for all python files! Coverage isn't great (the tests are currently only covering ~44% of the code)

Screen Shot 2023-02-21 at 7 46 46 pm

2. No tests for the `stroopwafel` interface atm -- having some trouble modularising it for testing...

3. Seems like `sampleMoeDiStefano` takes ~1min to execute `createParameterDistributionsAndSampler` -- @reinhold-willcox would it be possible to pass some args to generate the distributions over a fewer set of points?

4. Some changes with the detailedPlotter/example BBH run has broken the detailedPlot generation test: 
Screen Shot 2023-02-21 at 6 58 36 pm

**Comment by reinhold-willcox** [comment]
@avivajpeyi How do you run the tests to check that they are working (locally)?

Stroopwafel is being upgraded, so don't worry about building a test for that right now. For the moeDiStefano sampler, you put into the test that you only want 10 samples. It should run really fast if it's really generating just 10. If it's taking longer, my guess is it's not correctly parsing that input, but is instead using the default 1e5. The output is a standard COMPAS grid file, so the number of lines should match the input sample number. That's perhaps a simpler test that it worked.

**Comment by avivajpeyi** [comment]
Hey @reinhold-willcox , (on my cell, please excuse the brevity) 

1) to run the tests locally it'll be the same lines as written in the CI (it should just be pytest python_tests, or smth like that)

2) stoopwafel testing -- we would still ensure that it can work if we're including it (otherwise place a warning printing that it may be broken ATM)

3) I think the first part of code is what takes a while (generation of the distributions) not the second part which draws the samples?

**Comment by avivajpeyi** [comment]
Any progress with the run-plotter errors that appeared after pulling from main?

**Comment by avivajpeyi** [comment]
Also, looks like there has been a new error that has cropped up? 
The CI is now having trouble running the example binary from the methods paper 
https://github.com/TeamCOMPAS/COMPAS/actions/runs/4259063648/jobs/7410919895#step:5:1

**Comment by jeffriley** [comment]
> Any progress with the run-plotter errors that appeared after pulling from main?

dev?  If dev, see answer below...

> The CI is now having trouble running the example binary from the methods paper

Possibly because I changed the plotting code in a recent PR?  We changed some of the outputs, and removed others - so the plotting code won't work with older output files.  Either replace the data file we're using (which I should have done, but didn't think about it), or maybe we could look at checking in the plotting code what variables are available in the data file and go from there.  I can't do that tonight, but I probably could over the weekend.  Or we could just go back to the previous version of the plotting code for the example.  But that may not be the problem you're seeing...  Actually no - I just changed the plotting code - COMPAS should still run...

**Comment by jeffriley** [comment]
Possibly this:

    def runSubmit(cli_args=[DEFUALT_CONFIG_FILE], execute=True):
    NameError: name 'DEFUALT_CONFIG_FILE' is not defined

(Sorry, just trying to figure out if it was something I broke with my recent PR...)

**Comment by reinhold-willcox** [comment]
The example compas job now works, but we're still getting this error on Run pytests:

```
Run cd ${GITHUB_WORKSPACE}
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=compas_python_utils/
  inifile: None
  rootdir: /home/runner/work/COMPAS/COMPAS

Error: Process completed with exit code 4.
```
https://github.com/TeamCOMPAS/COMPAS/actions/runs/4308323755/jobs/7514468449

@avivajpeyi This is pretty cryptic to me, do you know what this means?

Separately, we have COMPAS compile tests on both push and pull_request. This is unneeded. We should change the compile yaml to only do tests on pull_requests, and only if the receiving branch is dev and if there are changes in either src/** or compas_python_utils/**. If anyone knows how to do this, please go ahead, otherwise I can take a look at some point.

**Comment by avivajpeyi** [comment]
Sure i can take a look at the pytest stuff 

> We should change the compile yaml to only do tests on pull_requests, and only if the receiving branch is dev and if there are changes in either src/** or compas_python_utils/**

sure

**Comment by avivajpeyi** [comment]
@reinhold-willcox , instead of renaming the test file, I've marked the stroopwaffel test to be skipped -- is that ok? Also, i added the fast-integration test back in (seems to work?)

**Comment by avivajpeyi** [comment]
@reinhold-willcox the CI is failing during plotting-detailed evolution (in the `Run example COMPAS Job` step). I think this fails because the COMPAS output file has changed:

```
(https://github.com/TeamCOMPAS/COMPAS/actions/runs/4379476917/jobs/7665472066#step:5:191), in h5py.h5o.open
KeyError: "Unable to open object (object 'Radius(1)|RL' doesn't exist)"
Error: Process completed with exit code 1.
```

<details>
  <summary>Full Log</summary>
  
  
```
Run example COMPAS job using the config 

COMPAS v02.35.03
Compact Object Mergers: Population Astrophysics and Statistics
by Team COMPAS (http://compas.science/index.html)
A binary star simulator

Start generating binaries at Thu Mar  9 22:54:13 2023

Evolution of current binary stopped: Double compact object
0: Evolution stopped: (Main_Sequence_>_0.7 -> Black_Hole) + (Main_Sequence_>_0.7 -> Black_Hole)
Evolution of current binary stopped: Double compact object
1: Evolution stopped: (Main_Sequence_>_0.7 -> Black_Hole) + (Main_Sequence_>_0.7 -> Black_Hole)

Generated 2 of 2 binaries requested

Simulation completed

End generating binaries at Thu Mar  9 22:54:15 2023

Clock time = 2.3586 CPU seconds
Wall time  = 0000:00:02 (hhhh:mm:ss)
python_version = 3
compas_executable_override None
grid_filename Grid_demo.txt
/home/runner/work/COMPAS/COMPAS/src/COMPAS --debug-to-file False --detailed-output  --enable-warnings False --errors-to-file False --evolve-unbound-systems False --population-data-printing False --print-bool-as-string False --quiet False --rlof-printing  --store-input-files  --switch-log False --check-photon-tiring-limit False --use-mass-loss  --allow-touching-at-birth False --angular-momentum-conservation-during-circularisation False --allow-rlof-at-birth  --circularise-binary-during-mass-transfer  --hmxr-binaries False --mass-transfer  --retain-core-mass-during-caseA-mass-transfer False --common-envelope-allow-immediate-RLOF-post-CE-survive False --common-envelope-allow-main-sequence-survive  --common-envelope-allow-radiative-envelope-survive False --common-envelope-lambda-nanjing-enhanced False --common-envelope-lambda-nanjing-interpolate-in-mass False --common-envelope-lambda-nanjing-interpolate-in-metallicity False --common-envelope-lambda-nanjing-use-rejuvenated-mass False --revised-energy-formalism-nandez-ivanova False --allow-non-stripped-ECSN  --pair-instability-supernovae  --pulsational-pair-instability  --evolve-pulsars False --debug-level 0 --logfile-common-envelopes-record-types -1 --logfile-detailed-output-record-types -1 --logfile-double-compact-objects-record-types -1 --logfile-pulsar-evolution-record-types -1 --logfile-rlof-parameters-record-types -1 --logfile-supernovae-record-types -1 --logfile-system-parameters-record-types -1 --grid-start-line 0 --hdf5-chunk-size 100000 --hdf5-buffer-size 1 --log-level 0 --maximum-evolution-time 13700.0 --maximum-number-timestep-iterations 99999 --number-of-systems 10 --timestep-multiplier 1 --cool-wind-mass-loss-multiplier 1.0 --initial-mass-min 5.0 --initial-mass-max [150](https://github.com/TeamCOMPAS/COMPAS/actions/runs/4379476917/jobs/7665472066#step:5:151).0 --initial-mass-power 0.0 --metallicity 0.0142 --metallicity-min 0.0001 --metallicity-max 0.03 --luminous-blue-variable-multiplier 1.5 --overall-wind-mass-loss-multiplier 1.0 --random-seed 0 --rotational-frequency 0.0 --rotational-frequency-1 0.0 --rotational-frequency-2 0.0 --wolf-rayet-multiplier 1.0 --eccentricity-min 0.0 --eccentricity-max 1.0 --mass-ratio-min 0.01 --mass-ratio-max 1.0 --minimum-secondary-mass 0.1 --orbital-period-min 1.1 --orbital-period-max 1000 --semi-major-axis-min 0.01 --semi-major-axis-max 1000.0 --convective-envelope-temperature-threshold 5370 --critical-mass-ratio-HG-degenerate-accretor 0.21 --critical-mass-ratio-HG-non-degenerate-accretor 0.25 --critical-mass-ratio-MS-high-mass-degenerate-accretor 0.0 --critical-mass-ratio-MS-high-mass-non-degenerate-accretor 0.625 --critical-mass-ratio-MS-low-mass-degenerate-accretor 1.0 --critical-mass-ratio-MS-low-mass-non-degenerate-accretor 1.44 --critical-mass-ratio-giant-degenerate-accretor 0.87 --critical-mass-ratio-giant-non-degenerate-accretor -1.0 --critical-mass-ratio-helium-HG-degenerate-accretor 0.21 --critical-mass-ratio-helium-HG-non-degenerate-accretor 0.25 --critical-mass-ratio-helium-MS-degenerate-accretor 0.0 --critical-mass-ratio-helium-giant-degenerate-accretor 0.0 --critical-mass-ratio-helium-MS-non-degenerate-accretor 0.87 --critical-mass-ratio-helium-giant-non-degenerate-accretor 1.28 --critical-mass-ratio-white-dwarf-degenerate-accretor 1.6 --critical-mass-ratio-white-dwarf-non-degenerate-accretor 0.0 --mass-transfer-fa 0.5 --mass-transfer-jloss 1.0 --mass-transfer-jloss-macleod-linear-fraction 0.5 --mass-transfer-thermal-limit-C 10.0 --zeta-adiabatic-arbitrary 1.0E5 --zeta-main-sequence 2.0 --zeta-radiative-envelope-giant 6.5 --common-envelope-alpha 1.0 --common-envelope-alpha-thermal 1.0 --common-envelope-lambda 0.1 --common-envelope-lambda-multiplier 1.0 --common-envelope-mass-accretion-constant 0 --common-envelope-mass-accretion-max 0.1 --common-envelope-mass-accretion-min 0.04 --common-envelope-recombination-energy-density 1.5E13 --common-envelope-slope-kruckow -0.83333333333 --maximum-mass-donor-nandez-ivanova 2.0 --eddington-accretion-factor 1 --fix-dimensionless-kick-magnitude -1.0 --fryer-22-fmix 0.5 --fryer-22-mcrit 5.75 --kick-direction-power 0.0 --kick-magnitude-sigma-CCSN-NS 265.0 --kick-magnitude-sigma-CCSN-BH 265.0 --kick-magnitude-max -1.0 --kick-magnitude-sigma-ECSN 30.0 --kick-magnitude-sigma-USSN 30.0 --kick-scaling-factor 1.0 --maximum-neutron-star-mass 2.5 --mcbur1 1.6 --muller-mandel-kick-multiplier-BH 200.0 --muller-mandel-kick-multiplier-NS 400.0 --muller-mandel-sigma-kick 0.3 --neutrino-mass-loss-BH-formation-value 0.1 --pisn-lower-limit 60.0 --pisn-upper-limit 135.0 --ppi-lower-limit 35.0 --ppi-upper-limit 60.0 --pulsar-birth-magnetic-field-distribution-min 11.0 --pulsar-birth-magnetic-field-distribution-max 13.0 --pulsar-birth-spin-period-distribution-min 10.0 --pulsar-birth-spin-period-distribution-max 100.0 --pulsar-magnetic-field-decay-timescale 1000.0 --pulsar-magnetic-field-decay-massscale 0.025 --pulsar-minimum-magnetic-field 8.0 --grid Grid_demo.txt --mode BSE --chemically-homogeneous-evolution PESSIMISTIC --envelope-state-prescription LEGACY --initial-mass-function KROUPA --luminous-blue-variable-prescription HURLEY_ADD --mass-loss-prescription VINK --metallicity-distribution ZSOLAR --pulsational-pair-instability-prescription MARCHANT --eccentricity-distribution ZERO --mass-ratio-distribution FLAT --orbital-period-distribution FLATINLOG --rotational-velocity-distribution ZERO --semi-major-axis-distribution FLATINLOG --case-BB-stability-prescription ALWAYS_STABLE --critical-mass-ratio-prescription NONE --stellar-zeta-prescription SOBERMAN --mass-transfer-angular-momentum-loss-prescription ISOTROPIC --mass-transfer-accretion-efficiency-prescription THERMAL --mass-transfer-rejuvenation-prescription STARTRACK --mass-transfer-thermal-limit-accretor CFACTOR --common-envelope-formalism ENERGY --common-envelope-lambda-prescription LAMBDA_NANJING --common-envelope-mass-accretion-prescription ZERO --black-hole-kicks FALLBACK --fryer-supernova-engine DELAYED --kick-magnitude-distribution MAXWELLIAN --kick-direction ISOTROPIC --neutron-star-equation-of-state SSE --neutrino-mass-loss-BH-formation FIXED_MASS --pulsar-birth-magnetic-field-distribution ZERO --pulsar-birth-spin-period-distribution ZERO --remnant-mass-prescription FRYER2012 --logfile-type HDF5 --output-path /home/runner/work/COMPAS/COMPAS/misc/examples/methods_paper_plots/detailed_evolution
Out files:
total 36
drwxr-xr-x 3 runner docker  4096 Mar  9 22:54 COMPAS_Output
-rw-r--r-- 1 runner docker   314 Mar  9 22:47 Grid_demo.txt
-rw-r--r-- 1 runner docker  7087 Mar  9 22:54 example_bbh.log
-rw-r--r-- 1 runner docker 13764 Mar  9 22:47 example_bbh_compas_config.yaml
-rwxr-xr-x 1 runner docker   345 Mar  9 22:47 run.sh
Generating detailed evolution plot
Traceback (most recent call last):
  File "/home/runner/.local/bin/compas_plot_detailed_evolution", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.8/site-packages/compas_python_utils/detailed_evolution_plotter/plot_detailed_evolution.py", line 27, in main
    run_main_plotter(args.data_path, outdir=args.outdir, show=args.dont_show)
  File "/home/runner/.local/lib/python3.8/site-packages/compas_python_utils/detailed_evolution_plotter/plot_detailed_evolution.py", line 38, in run_main_plotter
    makeDetailedPlots(Data, events, outdir=outdir)
  File "/home/runner/.local/lib/python3.8/site-packages/compas_python_utils/detailed_evolution_plotter/plot_detailed_evolution.py", line 91, in makeDetailedPlots
    handles, labels = specificPlot(ax=ax, Data=Data, events=events, mask=mask)
  File "/home/runner/.local/lib/python3.8/site-packages/compas_python_utils/detailed_evolution_plotter/plot_detailed_evolution.py", line 150, in plotLengthAttributes
    mask1 = mask & (Data['Radius(1)|RL'][()] != 0)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/runner/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line [190](https://github.com/TeamCOMPAS/COMPAS/actions/runs/4379476917/jobs/7665472066#step:5:191), in h5py.h5o.open
KeyError: "Unable to open object (object 'Radius(1)|RL' doesn't exist)"
Error: Process completed with exit code 1.

```
</details>

**Comment by avivajpeyi** [comment]
@reinhold-willcox -- the plotting is still failing due to 
```
File "/home/runner/work/COMPAS/COMPAS/compas_python_utils/detailed_evolution_plotter/plot_detailed_evolution.py", line 150, in plotLengthAttributes
    mask1 = mask & (Data['Radius(1)|RL'][()] != 0)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/runner/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line [190](https://github.com/TeamCOMPAS/COMPAS/actions/runs/4465451845/jobs/7842523886#step:5:191), in h5py.h5o.open
KeyError: "Unable to open object (object 'Radius(1)|RL' doesn't exist)"
```

**Comment by ilyamandel** [comment]
Should be fixed...

**Comment by ilyamandel** [comment]
@avivajpeyi -- looks like this now works. :). Do you want to mark this ready for review, so I can approve it?

**Comment by avivajpeyi** [comment]
The last few commits i made allow the CI to upload outputs from the COMPAS run (logs and plots) 

The following link will download the COMPAS plotting files (logs and plots)
https://github.com/TeamCOMPAS/COMPAS/suites/11694089492/artifacts/608165367

This next link will download info/stats about the amount of code that is being tested:
https://github.com/TeamCOMPAS/COMPAS/suites/11694089492/artifacts/608165366

It is possible to get the plots + logs to show up on the COMPAS readme w/o having to download stuff -- but for that we will need to upload the plots + logs to the [https://TeamCOMPAS.github.io/COMPAS](https://TeamCOMPAS.github.io/COMPAS) pages. 

**QS: Are the pages active?**  Can i push files to them?

**Comment by ilyamandel** [comment]
@avivajpeyi -- yes, https://teamcompas.github.io is active; we actually bought the https://compas.science/ and the github.io link redirects there.  I have no problem with having a subpage like https://teamcompas.github.io/COMPAS show automatically generated material related to the current status of the code.

**Review by ilyamandel — APPROVED** [review]
Thank you for the great work, @avivajpeyi (and @reinhold-willcox , @themikelau , et al.)!

**Pull request merged**
