### PR TITLE
added MT_TRACKER values 8 and 9 to documentation

### LINKED ISSUE #733: Question about documentation: MASS_TRANSFER_TRACKER_HISTORY = 8?
I'm looking at the MASS_TRANSFER_TRACKER_HISTORY definition on [this page](https://compas-docs-readthedocs.readthedocs.io/en/latest/standard-logfiles-record-specification-binary.html#binary-props-m) and I don't see a definition for 8 but I'm getting loads of 8 in my COMPAS results. What does it mean?

Also - where is the best place to ask questions like that which relate more to the documentation? If you want them on the github, would it be worth creating a special type of issue which is neither a bug report nor a feature request, but a documentation question?

### LINKED ISSUE #814: plot_detailed_evolution.py does not display numbers on abscissa
plot_detailed_evolution.py does not display numbers on abscissa, so can't actually tell how much time passed

### PR DESCRIPTION
**Pull request by reinhold-willcox**
Addresses issue #733

### CODE REVIEW

**Review by jeffriley — CHANGES_REQUESTED** [review]
The documentation changes look good to me, but there are changes to the code that look to be for, or in anticipation of, PR795.  Was that inadvertent? If those code changes are going to stay in this PR, then changelog and version need to be updated (happy to call the rearrangement of some of the code in Options.h cosmetic (though technically even that could cause functionality changes under some circumstances), but not the partial implementation of PR795).

**Comment by reinhold-willcox** [comment]
That was inadvertent, thanks for catching. They are removed now.

**Review by ilyamandel — CHANGES_REQUESTED** [review]
I find myself confused with the labelling here.  E.g., 3 corresponds to CE from 1 to 2.  But then 8 is CE merger with radiative envelope -- so does that mean 3 is really CE from 1 to 2 with convective envelope only?  But wait, there's 7, CE MS with CO.  If the MS star has a radiative envelope and this CE leads to a merger, would that still be labeled as 7 or 9?  It would help if the descriptions included the full set of conditions to avoid ambiguity.

**Comment by reinhold-willcox** [comment]
I'm not sure when this tracker was introduced, or who (if anyone) uses it. I agree that the conditions as do not work, since some options overlap and others are non-complementary. The full list is here:

```
 const COMPASUnorderedMap<MT_TRACKING, std::string> MT_TRACKING_LABEL = {
     { MT_TRACKING::NO_MASS_TRANSFER,   "NO MASS TRANSFER" },
     { MT_TRACKING::STABLE_FROM_1_TO_2, "MASS TRANSFER STABLE STAR1 -> STAR2" },
     { MT_TRACKING::STABLE_FROM_2_TO_1, "MASS TRANSFER STABLE STAR2 -> STAR1" },
     { MT_TRACKING::CE_FROM_1_TO_2,     "MASS TRANSFER COMMON ENVELOPE STAR1 -> STAR2" },
     { MT_TRACKING::CE_FROM_2_TO_1,     "MASS TRANSFER COMMON ENVELOPE STAR2 -> STAR1" },
     { MT_TRACKING::CE_DOUBLE_CORE,     "MASS TRANSFER COMMON ENVELOPE DOUBLE CORE" },
     { MT_TRACKING::CE_BOTH_MS,         "MASS TRANSFER WET MERGER: MS -> MS" },
     { MT_TRACKING::CE_MS_WITH_CO,      "MASS TRANSFER COMMON ENVELOPE MS -> CO" },
     { MT_TRACKING::CE_WITH_RAD_ENV,    "MASS TRANSFER COMMON ENVELOPE MERGER WITH RADIATIVE ENVELOPE STAR" },
     { MT_TRACKING::CE_IMMEDIATE_RLOF,  "MASS TRANSFER COMMON ENVELOPE MERGER DUE TO IMMEDIATE POST-CE RLOF" }
 };
```

We could either get rid of them completely, or find a way to sensibly clean them up. But unless someone is working on a project that directly uses them, it would be sort of a best guess as to the most sensible solution.

**Comment by ilyamandel** [comment]
I think @avigna may have used these.  We also use them in the pretty picture outputs for binary evolution on the website, right?

**Comment by avigna** [comment]
These are a few/several years old, I haven't used them in a similar timescale. Im sure we could simplify them if we want to.

**Comment by reinhold-willcox** [comment]
@ilyamandel Do we use them for the website? If the website only calls the detailed evolution plotter, then I think we ignore them, the plotter looks at the other parameters for stable/unstable and stellar types individually. 

I would be fine updating these to something more sensible, but that may take some time (and initiative from someone who needs them for a project). In the meantime, I think it would be good for the documentation to reflect the code, even if the code is doing something funny.

**Comment by reinhold-willcox** [comment]
I take it back, the plotter does use exactly these, my bad. Let's discuss a good way to clean these up at the next dev call.

**Comment by ilyamandel** [comment]
Suggestion: keep only the following options.  These, I believe, are mutually exclusive and cover the full range of possible outcomes, so there's no ambiguity [all but the last one do not lead to a merger -- can add "survived" at the start of the lines, but I think that's obvious].  If the user wants to know the stellar type of accretor or donor or what kind of envelope they had, they can dig deeper on their own.

     { MT_TRACKING::NO_MASS_TRANSFER,   "NO MASS TRANSFER" },
     { MT_TRACKING::STABLE_FROM_1_TO_2, "MASS TRANSFER STABLE STAR1 -> STAR2" },
     { MT_TRACKING::STABLE_FROM_2_TO_1, "MASS TRANSFER STABLE STAR2 -> STAR1" },
     { MT_TRACKING::CE_FROM_1_TO_2,     "MASS TRANSFER COMMON ENVELOPE STAR1 -> STAR2" },
     { MT_TRACKING::CE_FROM_2_TO_1,     "MASS TRANSFER COMMON ENVELOPE STAR2 -> STAR1" },
     { MT_TRACKING::CE_DOUBLE_CORE,     "MASS TRANSFER COMMON ENVELOPE DOUBLE CORE" },
     { MT_TRACKING::CE_BOTH_MS,         "MASS TRANSFER COMMON ENVELOPE MERGER" }

**Comment by reinhold-willcox** [comment]
I think you missed stable mergers. Does this work: 

```
 { MT_TRACKING::NO_MASS_TRANSFER,   "NO MASS TRANSFER" },
 { MT_TRACKING::STABLE_1_TO_2_SURV, "MASS TRANSFER STABLE STAR1 -> STAR2" },
 { MT_TRACKING::STABLE_2_TO_1_SURV, "MASS TRANSFER STABLE STAR2 -> STAR1" },
 { MT_TRACKING::STABLE_MERGER,           "MASS TRANSFER STABLE MERGER" }
 { MT_TRACKING::CE_1_TO_2_SURV,     "MASS TRANSFER COMMON ENVELOPE STAR1 -> STAR2" },
 { MT_TRACKING::CE_2_TO_1_SURV,     "MASS TRANSFER COMMON ENVELOPE STAR2 -> STAR1" },
 { MT_TRACKING::CE_DOUBLE_SURV,     "MASS TRANSFER COMMON ENVELOPE DOUBLE CORE" },
 { MT_TRACKING::CE_MERGER,         "MASS TRANSFER COMMON ENVELOPE MERGER" }
```

**Comment by ilyamandel** [comment]
Do we even have stable mergers?  I guess we do, e.g., plunge-ins after awkward SN kicks... I'd just make a single case for all mergers.

**Comment by reinhold-willcox** [comment]
We have mergers during stable MT when the radii overlap which we don't flag as CEE (for whatever reason). Arguably a bug, but not just due to awkward SN kicks.

**Comment by ilyamandel** [comment]
Hi @reinhold-willcox ,
So do we agree on the path forward for this one?

**Comment by reinhold-willcox** [comment]
@ilyamandel I think so, but I have not had time to code it up. When I do, I'll assign you as reviewer to double check we are in agreement.

**Comment by reinhold-willcox** [comment]
this PR now addresses issue #814, and supercedes PR #815, which should be closed when this one is approved. 

Specifically, the plotter has now been updated with the new MT_Tracker values, and has been fixed so that the end state (Merger, DCO, or unbound) event does not show up in the plots. This is to avoid significant compressing in the plots when these very late time events occur.

**Comment by reinhold-willcox** [comment]
@IsobelMarguarethe let me know if these changes solve your problem.

**Comment by ilyamandel** [comment]
@reinhold-willcox , looks great.  I made two minor tweaks directly -- please check:

Removed commented out                 #print("endearly? ", isEndEarly) lines
Changed arbitrary addition of 1 Myr to stop time to a 5% increase

Happy to approve at this stage.  @jeffriley , can you check / do the same, since you requested changes?

**Review by ilyamandel — APPROVED** [review]

**Comment by ilyamandel** [comment]
Aside for @reinhold-willcox :

the vdH diagram plotting script currently crashes with
Traceback (most recent call last):
 File "/Users/ilyam/Work/COMPAS/COMPAS/utils/plot_detailed_evolution.py", line 673, in <module>
  main()
 File "/Users/ilyam/Work/COMPAS/COMPAS/utils/plot_detailed_evolution.py", line 39, in main
  plotVanDenHeuvel(events=events)
 File "/Users/ilyam/Work/COMPAS/COMPAS/utils/plot_detailed_evolution.py", line 308, in plotVanDenHeuvel
  pltString = pltString.format(events[ii].time,events[ii].aprev, events[ii].a,events[ii].m1prev,events[ii].m1,events[ii].m2prev,events[ii].m2)
KeyError: '\\odot'Traceback (most recent call last):
 File "/Users/ilyam/Work/COMPAS/COMPAS/utils/plot_detailed_evolution.py", line 673, in <module>
  main()
 File "/Users/ilyam/Work/COMPAS/COMPAS/utils/plot_detailed_evolution.py", line 39, in main
  plotVanDenHeuvel(events=events)
 File "/Users/ilyam/Work/COMPAS/COMPAS/utils/plot_detailed_evolution.py", line 308, in plotVanDenHeuvel
  pltString = pltString.format(events[ii].time,events[ii].aprev, events[ii].a,events[ii].m1prev,events[ii].m1,events[ii].m2prev,events[ii].m2)
KeyError: '\\odot'

**Review by jeffriley — APPROVED** [review]
My comments have been addressed - I approve.

**Comment by reinhold-willcox** [comment]
@ilyamandel The removal of the comments and 5% maximum time increase are fine with me. 

Regarding the plotting script crash, my guess is that there's some python latex reader backend that you don't have installed, since the plotter works correctly for me. In the interest of getting this PR approved so the GW landscape team can use the changes, could you create a new issue for the \odot bug? I have limited time this week, but hopefully will find some next week.

**Pull request merged**
