### PR TITLE
Add CI test runners for runSubmit + plot_detailed_evolution

### PR DESCRIPTION
**Pull request by avivajpeyi**
Created by the ADACS GWLandscape team, this does the following:

~1. Adds CI install tests on ubuntu-20.04, ubuntu-18.04, macos-11~
 --> Removed as these take a long time --> in the future, it can be made as a weekly CI job

2. Adds some CI testing for the python scripts:
```
python3 runSubmitDemo.py
python3 plot_detailed_evolution.py
```

### CODE REVIEW

**Comment by avivajpeyi** [comment]
Running CI on these three architechtures is taking over 25 minutes -- maybe this should be done weekly rather than every PR


Screen Shot 2023-01-31 at 12 32 07 pm

**Review by reinhold-willcox — APPROVED** [review]
tentatively approving, just to see what happens.

**Comment by avivajpeyi** [comment]
NOTE: although the status shows tat the "checks haven't completed", looking at the jobs themselves you will see that the checks have been completed successfully -- just that the status has not gotten sent to the check

Screen Shot 2023-01-31 at 1 16 31 pm




@reinhold-willcox  and @jeffriley, the "Build COMPAS Expected — Waiting for status to be reported" might have to do with 
https://luxiyalu.com/expected-waiting-for-status-to-be-reported/
https://github.com/orgs/community/discussions/26698


@emanehab99 pointed out this may have something to do with branch rules to have gotten this check to get stuck in limbo

**Comment by ilyamandel** [comment]
Thank you, @emanehab99 !  

@avivajpeyi , are you good with this?

One question for github gurus (@reinhold-willcox ?) -- is there any way to see changes relative to current version of dev, rather than relative to dev as it was when this branch was first made?  This would give me more confidence that we aren't changing anything we shouldn't be (like C++ files) with this PR.

**Comment by ilyamandel** [comment]
I ran 
`git diff update_GHA_compile_workflow..dev`
locally.

This shows that changes are confined to the following files:
.github/workflows/compas-compile-ci.yml
requirements.txt
utils/cicd-scripts/centos-dependencies
utils/cicd-scripts/linux-dependencies
utils/cicd-scripts/macos-dependencies
utils/cicd-scripts/python-scripts
utils/plot_detailed_evolution.py

I am unsure about the changes to the last two in particular — can you please check, @reinhold-willcox ?

**Comment by reinhold-willcox** [comment]
I just looked at the github and you are correct, the diff is weird (you can ignore my previous comments that it should be fixed). I don't know why, this appears to be a fluke from the revert / undo-revert in the other criticalMassRatios PR, possibly because the first commit of this PR was from Eman in may of last year, before the first one from me in criticalMassRatios. 

I tried closing and re-opening the PR and surprisingly that seems to have fixed it. The diff now just shows the changes to the CI workflow, as it should. Let me know if it is or isn't fixed for you.

To the two files you've referenced, the first one is expected for this PR and contains CI workflows for the python scripts. The second one is a fix that I think Avi made to the path of image files used in the van den heuval plotter (it is now more pythonic, but works the same as before). Both make sense to include here, so I think we're good to merge.

**Comment by avivajpeyi** [comment]
Looks good -- the CI may take over 25 minutes, however...

**Comment by reinhold-willcox** [comment]
@avivajpeyi Why is that?

**Comment by avivajpeyi** [comment]
> @avivajpeyi Why is that?

Sorry I missed that most of the other OS options have been commented out (the Mac build can take a long time due to the installations of the dependencies)

**Pull request merged**
