### PR TITLE
Enhancement, defect repair, code cleanup

### LINKED ISSUE #439: COMPAS hangs on some systems.
**Describe the bug**
On some specific initial conditions, COMPAS will completely hang. Cause is unknown, but it seems to occur for massive binaries with short separations, so I would guess that these are systems in contact at ZAMS. When it happens, COMPAS does not continue evolving binaries. 

**Label the issue**
`urgency_high`     - This is a very urgent issue and should be resolved as soon as possible
`severity_major`    - This is a severe bug

**To Reproduce**
Run: `./COMPAS --initial-mass-1 9.32943617585786 --semi-major-axis 0.03341866534357877 --initial-mass-2 8.366832044672574 --metallicity 0.0142 --eccentricity 0`

**Expected behavior**
Not to hang. If it is related to contact binaries, these should probably be discarded. 

**Versioning (please complete the following information):**
 - COMPAS v02.16.03

### PR DESCRIPTION
**Pull request by jeffriley**
(1) Added SSE System Parameters file - records initial parameters and result (final stellar type) - useful when detailed output is not required
(2) Fixed typo in LogfileSwitchLog() in Options.h - only affected situation where user specified switchlog filename (overriding default filename)
(3) Removed m_LBVfactor variable from BaseBinaryStar - never used in BSE code
(4) Removed m_LBVfactor variable from BaseStar - use OPTIONS->LuminousBlueVariableFactor()
(5) Removed m_WolfRayetFactor variable from BaseBinaryStar - never used in BSE code
(6) Removed m_LBVfactor variable from BaseStar - use OPTIONS->WolfRayetFactor()

Updated docs - for these changes plus some changes for past code changes that didn't make it into the docs.

No linked issues.

### CODE REVIEW

**Comment by jeffriley** [comment]
Close Issue #439 when merged

**Review by reinhold-willcox — APPROVED** [review]
I'm happy with the part of this that fixes the ZAMS RLOF bug.

**Comment by jeffriley** [comment]
@ilyamandel Are you still reviewing, or can this be merged?

**Comment by ilyamandel** [comment]
@jeffriley -- I was eating dinner. :) Looking now.

**Review by ilyamandel — COMMENTED** [review]
I see that .github/workflows/dockerhub-ci.yml was deleted (I think in Reinhold's push) -- was that intentional?

**Review by ilyamandel — COMMENTED** [review]
Out of curiosity, why did you choose to store all of these, but not the actual supernova type?

    PROGRAM\_OPTION::KICK\_MAGNITUDE\_DISTRIBUTION\_SIGMA\_CCSN\_NS, \\
     PROGRAM\_OPTION::KICK\_MAGNITUDE\_DISTRIBUTION\_SIGMA\_CCSN\_BH, \\
     PROGRAM\_OPTION::KICK\_MAGNITUDE\_DISTRIBUTION\_SIGMA\_FOR\_ECSN, \\
     PROGRAM\_OPTION::KICK\_MAGNITUDE\_DISTRIBUTION\_SIGMA\_FOR\_USSN,

**Review by ilyamandel — COMMENTED** [review]
... or the final mass?  I'd go for final mass over the SN defaults (or along with them).

**Review by ilyamandel — APPROVED** [review]
Approving, looks good, see optional comments above.

**Comment by jeffriley** [comment]
I didn't mean for you to stop eating dinner - I just wasn't sure if you were still looking, or whether you agreed with Reinhold's approval and so had stopped looking!

> I see that .github/workflows/dockerhub-ci.yml was deleted (I think in Reinhold's push) -- was that intentional?

I believe so.


> Out of curiosity, why did you choose to store all of these, but not the actual supernova type?

The SN type is in the SNe file.  I started with the BSE sys_parms file and whittled away what wasn't common - those were common so I left them there.  Happy to add/remove whatever makes sense.

> ... or the final mass? I'd go for final mass over the SN defaults (or along with them).

Ok, I'll add it  Actually, I'll merge this, and add mass as an update in my next PR (almost ready).

**Comment by reinhold-willcox** [comment]
Ah, it was not, sorry. That was a local change that shouldn't have been pushed up.

**Comment by ilyamandel** [comment]
OK, I don't know if .github/workflows/dockerhub-ci.yml is needed for the docker workflow, but if it is, could @reinhold-willcox or @jeffriley please re-add it [in a separate PR, since this one is closed]?

**Pull request merged**
