### PR TITLE
Significant update to mass transfer functionality and other bug fixes

### PR DESCRIPTION
**Pull request by ilyamandel**
- Replaced Fast Phase Case A MT and regular RLOF MT from non-envelope stars with a single function based on a root solver rather than random guesses (significantly improves accuracy and reduces cost); removed references to fast phase case A MT
- Simplified timescale calculations in BaseBinaryStar
- Cleaned BaseBinaryStar::CalculateMassTransferOrbit()
- Dispensed with mass-transfer-prescription option
- Corrected failure to update stars in InitialiseMassTransfer if orbit circularised on mass transfer
- Corrected incorrect timestep calculation for HeHG stars
- Reduced number of objects constructed
- Minor corrections elsewhere 
- Documentation fixes

Results cannot be directly compared to earlier runs because of numerous bug fixes, but DCOs are generally very similar except for minor changes because of more accurate binary evolution. Other impacts of these changes have been carefully vetted.

Overall speed improvement by more than an order of magnitude.

### CODE REVIEW

**Review by jeffriley — COMMENTED** [review]
Code changes look good.  I'll leave it to @avigna to review the physics.

**Review by jeffriley — CHANGES_REQUESTED** [review]
Code changes are ok with the following caveats and questions:

Minor changes:

std::cout at line 698 of BaseBinaryStar.h should either be removed or changed to one of the ERROR/WARN macros

Line 869 of constants.h: ERROR_SCOPE:: ALWAYS -> ERROR_SCOPE::ALWAYS
Line 934 of constants.h: 'of the page' -> 'off the page'


Questions:

Did you mean to leave the commented line at Basestar.cpp line 1220?

What's the 0.02 in HeHG::ChooseTimestep?  Should it be something declared in constants.h?

**Comment by ilyamandel** [comment]
> Code changes are ok with the following caveats and questions:

Thank you for the quick review, @jeffriley !
> Minor changes:
> 
> std::cout at line 698 of BaseBinaryStar.h should either be removed or changed to one of the ERROR/WARN macros

Should already be fixed in a follow-up commit I pushed last night (commit 3 in this PR); can you please check again?
> 
> Line 869 of constants.h: ERROR_SCOPE:: ALWAYS -> ERROR_SCOPE::ALWAYS

Doh -- surprised the compiler didn't complain!

> Line 934 of constants.h: 'of the page' -> 'off the page'

I managed to introduce a typo while fixing one (your comment had "of fthe page" :)  Thanks!
> 
> Questions:
> 
> Did you mean to leave the commented line at Basestar.cpp line 1220?

No, I didn't -- thanks, cleaned!
> 
> What's the 0.02 in HeHG::ChooseTimestep? Should it be something declared in constants.h?

It's a direct copy from an equation of section 8 of Hurley+, 2000.  I now added an explicit comment about this.  In this case, I think leaving it in the code is more readable than declaring another constant.

**Review by jeffriley — APPROVED** [review]
All good

**Pull request merged**
