### PR TITLE
Fixes for issue 978 and 1075.

### PR DESCRIPTION
**Pull request by jeffriley**
Fixes for issue 978 and 1075.

@ilyamandel Code changes described in issue https://github.com/TeamCOMPAS/COMPAS/issues/978 .

I did a little code cleanup (sorry...).

You will also see lots (lots...) of changes for constants.h changing the string "14, 6" to "15.15". Those changes just change the precision of double values written to the csv (and tsv and txt) COMPAS log files. Variables stored in HDF5 files are full precision, so I decided we should do the same for the other logfile types, and the users can decide how many digits they want to use.

EDIT: I included the sse output files in the PR.

### CODE REVIEW

**Review by ilyamandel — APPROVED** [review]
Thank you for the wonderful work, @jeffriley !

Happy to approve, just leaving some minor comments behind for your consideration.  Note that I am not carefully reviewing the key change in HG::CalculateRadiusOnPhase(): I am satisfied that this follows the SSE code and has the expected behaviour of ensuring that the radius on the HG phase evolves continuously to its desired endpoint at the start of FGB/CHeB, which is the only real requirement here.

BaseStar.cpp, around lines 1130--1140, the following line is repeated and probably could be computed just once:
int Zind = utils::Compare(m_Metallicity, LAMBDA_NANJING_ZLIMIT) < 0 ? 0 : 1;

BaseStar.cpp, 1171, 1233: yes, I think the log's should be log10's, i.e., should use m_Log10Metallicity!  That would mean we are making a mistake in the lambda interpolation.  I think this is @themikelau 's code -- Mike, could you take a look?  [Note: I am happy to approve this PR without waiting for this to be resolved, this is just a reminder to follow up on this.]

Not sure why you changed all the comparison functions in Veome's tides code to use compare but left some normal comparisons in code you edited elsewhere (e.g., CHeB.cpp, lines 1380-1382), but I think it's fine.

HG.cpp, line 1192: 
"// The current mass would yield a core mass larger than *or equal to* the current core mass -- i.e., no unphysical core mass decrease would ensue" -- add the commented text since you changed the < to <=?

MainSequence.cpp, line 666: "double dtk = 1.0E-2 * timescales(tMS); // 0.02 of MS timescale (sse uses 0.05)" -- comment doesn't match code (1.0E-2 is 0.01, not 0.02)

constants.h, line 294: "constexpr double HIGH_MASS_THRESHOLD = 12.0; // value above which we consider stars to be high mass stars".  value -> "Mass (in solar masses)"

**Comment by ilyamandel** [comment]
P.S. @themikelau confirmed, so could you please change the metallicity logs to log10 values?

> Yes! It should be log10. Apologies for the mistake. This should be changed in both double BaseStar::CalculateMassAndZInterpolatedLambdaNanjing and  double BaseStar::CalculateZInterpolatedLambdaNanjing

**Comment by jeffriley** [comment]
Thanks @ilyamandel 

First, the pytests are failing in the COMPAS build process.  I believe the error is:

    KeyError: "Unable to synchronously open object (object 'BSE_Common_Envelopes' doesn't exist)"

but if I run COMPAS v02.44.01 with `runSubmit` and `example_bbh_compas_config.yaml` the HDF5 file produced contains a `BSE_Common_Envelopes` file.  Maybe @avivajpeyi or @reinhold-willcox could take a look at that?  I'll merge this PR anyway - the code compiles and runs ok - and seems to produce reasonable results.

As to your comments @ilyamandel :

> BaseStar.cpp, around lines 1130--1140, the following line is repeated and probably could be computed just once:
> int Zind = utils::Compare(m_Metallicity, LAMBDA_NANJING_ZLIMIT) < 0 ? 0 : 1;

I don't think that's right.  There are two instances of that line of code, but they are in different conditional clauses, so only one will be executed.

> BaseStar.cpp, 1171, 1233: yes, I think the log's should be log10's, i.e., should use m_Log10Metallicity!

Fixed.

> Not sure why you changed all the comparison functions in Veome's tides code to use compare but left some normal 
> comparisons in code you edited elsewhere (e.g., CHeB.cpp, lines 1380-1382), but I think it's fine.

I don't use utils::Compare() for age/time/timestep related comparisons - on the basis that any thresholds we (eventually) set for  utils::Compare() may need to be different for age/time/timestep related comparisons and other attributes like mass, radius etc.  My thinking is that the age/time/timestep values are sensitive to many more decimal places than the other attributes are likely to be, so I want to think about (maybe you to think about ;-)) whether the same threshold should be used.  Does that make sense?  Since we now use quantised timesteps, we are in a good position to change the code so that all our age/time/timestep values are stored as integer multiples of the TIMESTEP_QUANTUM (10^-12), and so all our age/time/timestep related comparisons could be integer comparisons - not a huge job (we'd just have to be careful), but worth thinking about.  That would fix/prevent any precision-related issues with age/time/timestep calculations.

I did, however, miss the mass related comparison in CHeB.cpp that you noted - now fixed. 

> HG.cpp, line 1192:
> "// The current mass would yield a core mass larger than or equal to the current core mass -- i.e., no unphysical core mass 
> decrease would ensue" -- add the commented text since you changed the < to <=?

Fixed.

> MainSequence.cpp, line 666: "double dtk = 1.0E-2 * timescales(tMS); // 0.02 of MS timescale (sse uses 0.05)" -- comment 
> doesn't match code (1.0E-2 is 0.01, not 0.02)

Oops - looked at the wrong digit :-)  Fixed.

> constants.h, line 294: "constexpr double HIGH_MASS_THRESHOLD = 12.0; // value above which we consider stars to be high
> mass stars". value -> "Mass (in solar masses)"

Fixed.

**Comment by jeffriley** [comment]
Ok, @avivajpeyi pointed out that the failing test actually uses `fiducial bbh-config.yaml`, not `example_bbh_compas_config.yaml`.  Running with `fiducial bbh-config.yaml` and the grid file supplied produces no CEE, so no CE file.  This has happened before (though last time it was not enough DCOs being produced), and we "fixed" it by jiggling the initial attributes in the grid file.  Maybe we could do the same here - it looks like the changes to the code in this PR were enough to mean no CE happened in the binaries in the grid file.  I'm not going to hold the PR up for this, but we need someone to look at this test and associated grid file to see what needs to be changed to make the test run (@avivajpeyi , @reinhold-willcox , @themikelau ?).

@avivajpeyi kindly agreed to start documenting the tests in the developer guide of the online documentation.  Developers need to know what tests are going to be run against new code, and what those tests are actually testing, and what their input requirements are etc., so that we can ensure the new code actually at least produces the required inputs for the tests.

**Comment by ilyamandel** [comment]
> > BaseStar.cpp, around lines 1130--1140, the following line is repeated and probably could be computed just once:
> > int Zind = utils::Compare(m_Metallicity, LAMBDA_NANJING_ZLIMIT) < 0 ? 0 : 1;
> 
> I don't think that's right. There are two instances of that line of code, but they are in different conditional clauses, so only one will be executed.

Sure, I meant it could be done before the conditional split, but it's fine as is.

**Review by ilyamandel — APPROVED** [review]

**Comment by jeffriley** [comment]
> Sure, I meant it could be done before the conditional split, but it's fine as is.

You're absolutely right :-)  I'll move it out next time.

**Pull request merged**
