### PR TITLE
Removed some setters in BinaryConstituentStar

### PR DESCRIPTION
**Pull request by jeffriley**
Removed some setters in BinaryConstituentStar.  Will address others later.

### CODE REVIEW

**Comment by jeffriley** [comment]
@ilyamandel I tweaked some of your code, and removed a couple of setters.

I am not able to produce the detailed output plot for comparison - can you check that you can?  If you can then I'll need to look at my configuration, but if you can't then we might need to look at the code.

**Review by ilyamandel — CHANGES_REQUESTED** [review]
Do we really need to split off InitialiseWindsMassLoss from CalculateMassLossValues?  It seems like we are adding an extra layer of functions which will just be more confusing to future coders -- can we avoid this?

BaseStar.cpp, line 1939:
//JR: todo: pick a better name for this...

Maybe now is a good time?  How about CalculateMassAfterWindMassLoss() [to make it clear this is all about winds?]

1942: 
should be update*d*

1932: calculated *stellar* mass *after mass loss* 

Note that because of another pull, changelog.h is now outdates, so dev needs to be merged in.

**Comment by ilyamandel** [comment]
P.S. 

> I am not able to produce the detailed output plot for comparison - can you check that you can? If you can then I'll need to look at my configuration, but if you can't then we might need to look at the code.

The following works for me on v. 2.34.06 and produces the same detailed output as previously:
make clean
make -j 4
$COMPAS_ROOT_DIR/src/COMPAS -v
cd $COMPAS_ROOT_DIR/utils/examples/methods_paper_plots/detailed_evolution/
rm -r COMPAS_Output
python3 runSubmitDemo.py
python3 plot_detailed_evolution.py

**Comment by jeffriley** [comment]
> Do we really need to split off InitialiseWindsMassLoss from CalculateMassLossValues? It seems like we are adding an extra
> layer of functions which will just be more confusing to future coders -- can we avoid this?

Unless I'm misremembering, they do different things - we don't always want to do the total of both wherever they are called individually, do we?

**Comment by ilyamandel** [comment]
InitialiseWindMassLoss does two things: it calls CalculateMassLossValues and sets m_MassLossDiff.  Is the goal to hide a setter?  I think it just makes for harder to read, messier code.  Anyway, I won't argue with you on that one, but see my other requests for changes (all minor). :)   Also, dev needs to be merged in (e.g., changelog.h is out of date).

**Comment by jeffriley** [comment]
@ilyamandel I'll get to this in a bit, but the quick answer to this:

Is the goal to hide a setter?

It is, yes (well, to remove, rather than hide, a setter) - I removed SetMassLossDiff() which just set a class member variable.  Is the new code messier?  Well, I suppose it's more indirect than using a setter, so could be considered messier, but that's not a good case for a setter in OO code...  I'll have another look and see if I can make it less messy.

**Comment by ilyamandel** [comment]
Just a gentle reminder on this one too, @jeffriley ; I suspect that with the major changes to the code between now and then, it might be easier to start whatever you wanted to accomplish from scratch than to resuscitate these old PRs, but obviously it's your call. :)

**Pull request closed without merging**
